import Cordis.Batch
import Cordis.Codec
import Cordis.Coeffect
import Cordis.CoeffectQuotient
import Cordis.ContextualEquivalence
import Cordis.DeepSeekApi
import Cordis.DeepSeekApiErrorEnvelope
import Cordis.DeepSeekRequestMode
import Cordis.DeepSeekCurlTransport
import Cordis.DeepSeekCurlStream
import Cordis.DeepSeekCurlSession
import Cordis.DeepSeekCurlIncremental
import Cordis.DeepSeekCurlPrefix
import Cordis.DeepSeekCurlPrefixSession
import Cordis.DeepSeekCurlOutcome
import Cordis.DeepSeekOutcomeSession
import Cordis.DeepSeekOutcomeConversation
import Cordis.DeepSeekOutcomeConversationLoop
import Cordis.DeepSeekOutcomeTransportLoop
import Cordis.DeepSeekStream
import Cordis.DeepSeekStreamFailure
import Cordis.DeepSeekTerminalOutcome
import Cordis.DeepSeekStreamIncremental
import Cordis.DeepSeekRichStream
import Cordis.DeepSeekRichToolStream
import Cordis.DeepSeekRichMixedStream
import Cordis.DeepSeekRichMultiStream
import Cordis.DeepSeekSessionBridge
import Cordis.DeepSeekSessionRunner
import Cordis.DeepSeekApiSession
import Cordis.DeepSeekHarness
import Cordis.DeepSeekToolSchema
import Cordis.DeepSeekToolAdmission
import Cordis.DeepSeekGenericBridge
import Cordis.DeepSeekSchemaExecution
import Cordis.DeepSeekSchemaHarness
import Cordis.DeepSeekSchemaRound
import Cordis.DeepSeekSchemaMultiRound
import Cordis.DeepSeekSchemaRegistry
import Cordis.DeepSeekSchemaConversation
import Cordis.DeepSeekSchemaConversationLoop
import Cordis.DeepSeekSchemaStreamConversation
import Cordis.DeepSeekSchemaStreamPrefixConversation
import Cordis.DeepSeekSchemaStreamErrors
import Cordis.DeepSeekHarnessPersistence
import Cordis.DeepSeekHarnessEventArchive
import Cordis.DeepSeekHarnessEventText
import Cordis.DeepSeekHarnessErrors
import Cordis.DeepSeekHarnessRetry
import Cordis.DeepSeekHarnessCancellation
import Cordis.DeepSeekStreamHarness
import Cordis.DeepSeekStreamHarnessCancellation
import Cordis.DeepSeekStreamHarnessPrefix
import Cordis.DeepSeekStreamHarnessErrors
import Cordis.DeepSeekStreamHarnessRetry
import Cordis.DeepSeekAsyncHarness
import Cordis.DeepSeekAsyncStreamHarness
import Cordis.DeepSeekAsyncStreamCancellation
import Cordis.DurableCodec
import Cordis.DurableBytes
import Cordis.DurableIO
import Cordis.DurableSettlement
import Cordis.Effect
import Cordis.Examples.DependentChoice
import Cordis.Examples.DependentChoiceSession
import Cordis.GenericSessionHarness
import Cordis.GlobalActivationOrchestrationTransposition
import Cordis.GlobalActivationTransposition
import Cordis.GlobalCalculus
import Cordis.GlobalDeletion
import Cordis.GlobalDynamics
import Cordis.GlobalIteratorIndependence
import Cordis.GlobalTransposition
import Cordis.GlobalForeignPhase
import Cordis.GlobalLandingTransposition
import Cordis.GlobalLifecycle
import Cordis.GlobalLifecycleBisimulation
import Cordis.GlobalNameAction
import Cordis.GlobalNameLifecycle
import Cordis.GlobalPaperRelation
import Cordis.GlobalPaperTraceSimulation
import Cordis.GlobalPaperTraceDeletion
import Cordis.GlobalPaperTraceNormalization
import Cordis.GlobalProgress
import Cordis.GlobalRelations
import Cordis.GlobalRegistry
import Cordis.GlobalRuleInvariance
import Cordis.GlobalRuleObservations
import Cordis.GlobalSpatial
import Cordis.GlobalSupport
import Cordis.GlobalTemporal
import Cordis.GlobalTraceFacts
import Cordis.GlobalTraceRewrite
import Cordis.GlobalVestigial
import Cordis.Harness
import Cordis.HarnessPersistenceRefinement
import Cordis.HarnessPersistenceBytes
import Cordis.HarnessPersistenceArchive
import Cordis.HarnessPersistenceIO
import Cordis.DeepSeekHarnessPersistenceIO
import Cordis.DeepSeekHarnessOpaqueMetadata
import Cordis.DeepSeekHarnessMetadataArchive
import Cordis.Lifecycle
import Cordis.MediatedIndependence
import Cordis.MediatedTheorem
import Cordis.OperationIndependence
import Cordis.ObservationalPartialTransformation
import Cordis.OperationalEquivalence
import Cordis.ParallelHarness
import Cordis.ParallelSchedule
import Cordis.AsyncHarness
import Cordis.PartialTransformation
import Cordis.Policy
import Cordis.QuotientEffect
import Cordis.Registry
import Cordis.Removal
import Cordis.RichStream
import Cordis.RuntimeRefinement
import Cordis.RuntimeFailureRefinement
import Cordis.RuntimeOutcomeRefinement
import Cordis.RuntimeOutcomeSession
import Cordis.Schedule
import Cordis.Session
import Cordis.SessionRefinement
import Cordis.SessionOpaqueMetadata
import Cordis.SessionArchive
import Cordis.SessionEventArchive
import Cordis.SessionPayloadArchive
import Cordis.SessionValidation
import Cordis.Stream
import Cordis.StreamSession
import Cordis.TextRefinement
import Cordis.Transformation
import Cordis.UnifiedContext

/-!
# Headline theorem axiom audit

Building this module prints the logical dependencies of the guarantees exposed
by the verified kernel. The repository audit separately rejects project-defined
axioms and proof placeholders.
-/

set_option format.width 200

#print axioms Cordis.Codec.decode_encode
#print axioms Cordis.Effect.seq_recovers
#print axioms Cordis.Effect.seq_assoc
#print axioms Cordis.UndoStack.recover_after
#print axioms Cordis.Observational.Effect.seq_recovers
#print axioms Cordis.Effect.IndependentAt.seq_applied_eq
#print axioms Cordis.CertifiedTwoBatch.execute_order_irrelevant
#print axioms Cordis.CertifiedTwoBatch.execute_outputs_in_model_order
#print axioms Cordis.CertifiedTwoBatch.execute_recovers
#print axioms Cordis.Registry.setAt_restore
#print axioms Cordis.Registry.setAt_commute
#print axioms Cordis.Registry.setEffect_recovers
#print axioms Cordis.Registry.setEffect_commute
#print axioms Cordis.View.provider_present
#print axioms Cordis.Decision.denied_never_allows
#print axioms Cordis.Decision.tighten_associative
#print axioms Cordis.LeasePool.consumed_absent
#print axioms Cordis.LeasePool.consume_after_consumed
#print axioms Cordis.LeasePool.cannot_consume_twice
#print axioms Cordis.LeasePool.consume_after_issue_restores
#print axioms Cordis.PolicyTransition.denied_cannot_dispatch
#print axioms Cordis.PolicyTransition.dispatched_lease_absent
#print axioms Cordis.SubjectPolicyTransition.dispatched_lease_absent
#print axioms Cordis.SubjectPolicyTransition.denied_cannot_dispatch
#print axioms Cordis.SubjectPolicyTransition.phase_strict
#print axioms Cordis.SubjectPolicyTrace.dispatchCount_le_one
#print axioms Cordis.SubjectPolicyTrace.dispatchCount_to_completed
#print axioms Cordis.SubjectPolicyTrace.cannot_dispatch_twice
#print axioms Cordis.SubjectPolicyTrace.denied_dispatchCount_eq_zero
#print axioms Cordis.SubjectPolicyTrace.phase_monotone
#print axioms Cordis.ToolWire.validate_declared
#print axioms Cordis.ToolWire.decode_encoded_result
#print axioms Cordis.ToolWire.decode_encoded_certified_result
#print axioms Cordis.Event.noOrphanResult
#print axioms Cordis.Event.preservesWellFormed
#print axioms Cordis.applyRaw_eraseEvent
#print axioms Cordis.ValidatedEvent.applies
#print axioms Cordis.replayRaw_eraseTrace
#print axioms Cordis.ValidatedTrace.replays
#print axioms Cordis.Stream.noChunkAfterFinished
#print axioms Cordis.Stream.replayRaw_eraseTrace
#print axioms Cordis.Stream.replay_completeTrace
#print axioms Cordis.Lifecycle.Transition.unload_recovers
#print axioms Cordis.Lifecycle.Transition.unload_rejects_relied
#print axioms Cordis.Lifecycle.Transition.active_successor_keeps_view
#print axioms Cordis.Lifecycle.not_withdrawable_of_relied
#print axioms Cordis.Harness.replayRaw_append
#print axioms Cordis.Harness.RecordChain.length_eq_nextCall
#print axioms Cordis.Harness.RecordChain.ids_eq_range
#print axioms Cordis.Harness.RecordChain.boundaries_eq_records
#print axioms Cordis.Harness.RecordChain.leases_threaded
#print axioms Cordis.Harness.RunnerState.callBoundaries_eq_records
#print axioms Cordis.Harness.RunnerState.leases_threaded
#print axioms Cordis.Harness.RunnerState.protocolProjection_eq_log
#print axioms Cordis.Harness.RunnerState.protocolProjection_replays
#print axioms Cordis.Harness.certifiedTwoCallTrace_replays
#print axioms Cordis.GenericHarness.CallEvidence.policyRejected_dispatchCount_eq_zero
#print axioms Cordis.GenericHarness.CallEvidence.completed_dispatchCount_eq_one
#print axioms Cordis.GenericHarness.CallEvidence.completed_terminal_lease_absent
#print axioms Cordis.GenericHarness.CallEvidence.leases_restored
#print axioms Cordis.GenericHarness.RecordChain.length_eq_nextCall
#print axioms Cordis.GenericHarness.RecordChain.ids_eq_range
#print axioms Cordis.GenericHarness.RecordChain.boundaries_eq_records
#print axioms Cordis.GenericHarness.RecordChain.models_threaded
#print axioms Cordis.GenericHarness.RecordChain.leases_threaded
#print axioms Cordis.GenericHarness.Runner.records_length_eq_nextCall
#print axioms Cordis.GenericHarness.Runner.ids_eq_range
#print axioms Cordis.GenericHarness.Runner.models_threaded
#print axioms Cordis.GenericHarness.Runner.callBoundaries_eq_records
#print axioms Cordis.GenericHarness.Runner.leases_threaded
#print axioms Cordis.GenericHarness.Runner.beginTurn_log
#print axioms Cordis.GenericHarness.Runner.beginStep_log
#print axioms Cordis.GenericHarness.Runner.finishStep_log
#print axioms Cordis.GenericHarness.Runner.finishTurn_log
#print axioms Cordis.GenericSessionHarness.RunnerState.protocolProjection_replays
#print axioms Cordis.GenericSessionHarness.RunnerState.records_length_eq_nextCall
#print axioms Cordis.GenericSessionHarness.RunnerState.models_threaded
#print axioms Cordis.GenericSessionHarness.RunnerState.leases_threaded
#print axioms Cordis.GenericSessionHarness.RunnerState.ids_eq_range
#print axioms Cordis.GenericSessionHarness.RunnerState.callBoundaries_eq_records
#print axioms Cordis.Examples.DependentChoiceSession.run_succeeds
#print axioms Cordis.Examples.DependentChoiceSession.request_is_present
#print axioms Cordis.Examples.DependentChoiceSession.retained_record_count
#print axioms Cordis.Session.SurfaceTransition.replacement_exact_shadow
#print axioms Cordis.Session.SurfaceTransition.replacement_coverage
#print axioms Cordis.Session.ValidLog.length_eq_nextSeq
#print axioms Cordis.Session.ValidLog.seqs_eq_range
#print axioms Cordis.Session.ValidLog.surface_nodup
#print axioms Cordis.Session.ValidLog.surface_references_earlier
#print axioms Cordis.Session.ValidLog.latest_header_eq
#print axioms Cordis.Session.ProtocolCertificate.replays
#print axioms Cordis.Session.Session.protocolProjection_appendRequestHeader
#print axioms Cordis.Session.Session.protocolProjection_appendUserMessage
#print axioms Cordis.Session.Session.protocolProjection_appendAssistantMessage
#print axioms Cordis.Session.certifiedSession_messages
#print axioms Cordis.Session.certifiedSession_protocol_replays
#print axioms Cordis.Session.certifiedSession_request_values
#print axioms Cordis.Session.replacementSession_messages
#print axioms Cordis.Session.replacementSession_sources_cover_shadowed
#print axioms Cordis.Examples.DependentChoice.request_selects_exact_output_type
#print axioms Cordis.Examples.DependentChoice.allowed_call_has_typed_encoded_result
#print axioms Cordis.Examples.DependentChoice.label_call_is_exact_policy_rejection
#print axioms Cordis.Examples.DependentChoice.rejected_call_has_zero_dispatches
#print axioms Cordis.Examples.DependentChoice.rejected_call_preserves_model
#print axioms Cordis.Session.ValidatedSuffix.events_eq
#print axioms Cordis.Session.replacementEvent_revalidates
#print axioms Cordis.Session.wrongSequenceEvent_rejected
#print axioms Cordis.Session.missingStartEvent_rejected
#print axioms Cordis.Session.missingEndEvent_rejected
#print axioms Cordis.Session.incompleteCoverageEvent_rejected
#print axioms Cordis.Session.shortRawLog_validates
#print axioms Cordis.Coeffect.removeAt_setAt_of_absent
#print axioms Cordis.Coeffect.setAt_removeAt_of_present
#print axioms Cordis.Coeffect.setAt_commute
#print axioms Cordis.Coeffect.setEffect_recovers
#print axioms Cordis.Coeffect.CoeffectAt.lift_recovers
#print axioms Cordis.Coeffect.activating_iff
#print axioms Cordis.Coeffect.deactivating_iff
#print axioms Cordis.Coeffect.neutral_iff
#print axioms Cordis.Coeffect.notify_exhaustive
#print axioms Cordis.Coeffect.setting_unrelated_key_is_neutral
#print axioms Cordis.Coeffect.removing_unrelated_key_is_neutral
#print axioms Cordis.Coeffect.setting_last_missing_key_activates
#print axioms Cordis.Coeffect.removing_required_key_deactivates
#print axioms Cordis.Schedule.seq_commute
#print axioms Cordis.Schedule.runEffects_eq_of_perm
#print axioms Cordis.Schedule.CertifiedSchedule.effect_eq
#print axioms Cordis.Schedule.CertifiedSchedule.after_eq
#print axioms Cordis.Schedule.CertifiedSchedule.undo_eq
#print axioms Cordis.Schedule.CertifiedSchedule.recovers
#print axioms Cordis.Schedule.example_orders_equal
#print axioms Cordis.Schedule.reverseSchedule_recovers
#print axioms Cordis.DurableSettlement.Log.entries_length
#print axioms Cordis.DurableSettlement.Log.frames_length
#print axioms Cordis.DurableSettlement.Log.entries_map_frames
#print axioms Cordis.DurableSettlement.Log.recovers
#print axioms Cordis.DurableSettlement.Log.frames_tail_is_expected
#print axioms Cordis.DurableSettlement.CrashPrefix.recovers_initial
#print axioms Cordis.DurableSettlement.CrashPrefix.retained_frames_are_prefix
#print axioms Cordis.DurableSettlement.CrashPrefix.resume_recovers
#print axioms Cordis.DurableSettlement.Example.first_after
#print axioms Cordis.DurableSettlement.Example.second_after
#print axioms Cordis.DurableSettlement.Example.second_recovers
#print axioms Cordis.DurableSettlement.Example.crash_recovers
#print axioms Cordis.DurableSettlement.Example.resumed_after
#print axioms Cordis.DurableSettlement.Example.resumed_recovers
#print axioms Cordis.DurableCodec.frameCodec_roundtrip
#print axioms Cordis.DurableCodec.scanPrefix_frames_exact
#print axioms Cordis.DurableCodec.Example.scan_valid_exact
#print axioms Cordis.DurableCodec.Example.frameCodec_rejects_torn
#print axioms Cordis.DurableCodec.Example.scan_noncontiguous_rejected
#print axioms Cordis.DurableBytes.decodeFrame_encode
#print axioms Cordis.DurableBytes.decodeFrames_encodeMany
#print axioms Cordis.DurableBytes.decodeRawFrame_encode
#print axioms Cordis.DurableBytes.scanBytesPrefix_encode
#print axioms Cordis.DurableBytes.Example.valid_bytes_scan
#print axioms Cordis.DurableBytes.Example.torn_bytes_rejected
#print axioms Cordis.DurableIO.AppendPlan.decode_bytes
#print axioms Cordis.DurableIO.RecoveryCertificate.recovers_initial
#print axioms Cordis.DurableIO.Example.firstPlan_next_is_first
#print axioms Cordis.ParallelHarness.ParallelWindow.effect_eq
#print axioms Cordis.ParallelHarness.ParallelWindow.scheduled_after_eq_canonical
#print axioms Cordis.ParallelHarness.ParallelWindow.scheduled_undo_eq_canonical
#print axioms Cordis.ParallelHarness.WindowOutcome.execute_after_eq_canonical
#print axioms Cordis.ParallelHarness.WindowOutcome.execute_undo_eq_canonical
#print axioms Cordis.ParallelHarness.WindowOutcome.execute_recovers
#print axioms Cordis.ParallelHarness.Plan.effect_eq
#print axioms Cordis.ParallelHarness.Plan.execute_after_eq_canonical
#print axioms Cordis.ParallelHarness.Plan.execute_recovers
#print axioms Cordis.ParallelHarness.Plan.barrier_is_exclusive
#print axioms Cordis.ParallelHarness.drain.ids_eq
#print axioms Cordis.ParallelHarness.drain.all_cancelled
#print axioms Cordis.AsyncHarness.Step.terminal_guard
#print axioms Cordis.AsyncHarness.Trace.model_eq_runEffects
#print axioms Cordis.AsyncHarness.Trace.no_completion_preserves_model
#print axioms Cordis.AsyncHarness.exampleRaceTrace_successful
#print axioms Cordis.AsyncHarness.exampleRaceTrace_final_model
#print axioms Cordis.DeepSeekAsyncHarness.RaceResult.winner_mem
#print axioms Cordis.DeepSeekAsyncHarness.RaceResult.phase_terminal_of_winner
#print axioms Cordis.DeepSeekAsyncHarness.RaceResult.phase_pending_iff_waiting
#print axioms Cordis.DeepSeekAsyncHarness.phase_of_example_success_is_terminal
#print axioms Cordis.DeepSeekAsyncHarness.phase_of_example_failure_is_terminal
#print axioms Cordis.DeepSeekAsyncStreamHarness.RaceResult.winner_mem
#print axioms Cordis.DeepSeekAsyncStreamHarness.RaceResult.phase_terminal_of_winner
#print axioms Cordis.DeepSeekAsyncStreamHarness.RaceResult.phase_pending_iff_waiting
#print axioms Cordis.DeepSeekAsyncStreamHarness.phase_of_example_success_is_terminal
#print axioms Cordis.DeepSeekAsyncStreamHarness.phase_of_example_failure_is_terminal
#print axioms Cordis.DeepSeekAsyncStreamCancellation.ProcessJobResult.phase_terminal_of_result
#print axioms Cordis.DeepSeekAsyncStreamCancellation.ProcessJobResult.cancelled_preserves_endpoint
#print axioms Cordis.DeepSeekAsyncStreamCancellation.RaceResult.winner_mem
#print axioms Cordis.DeepSeekAsyncStreamCancellation.RaceResult.phase_terminal_of_winner
#print axioms Cordis.DeepSeekAsyncStreamCancellation.RaceResult.phase_pending_iff_waiting
#print axioms Cordis.DeepSeekAsyncStreamCancellation.cancelTurn99_left_decision
#print axioms Cordis.DeepSeekAsyncStreamCancellation.cancelTurn99_right_decision
#print axioms Cordis.ParallelHarness.drain.drainOutcome_after_eq
#print axioms Cordis.ParallelHarness.drain.drainOutcome_reports_ids
#print axioms Cordis.ParallelHarness.example_window_after
#print axioms Cordis.ParallelHarness.example_window_committed
#print axioms Cordis.ParallelHarness.example_plan_after
#print axioms Cordis.ParallelHarness.example_plan_recovers
#print axioms Cordis.ParallelSchedule.SegmentData.effect_eq
#print axioms Cordis.ParallelSchedule.SegmentData.reports_ids
#print axioms Cordis.ParallelSchedule.Plan.effect_eq
#print axioms Cordis.ParallelSchedule.Plan.reports_eq_canonical
#print axioms Cordis.ParallelSchedule.Plan.execute_after_eq_canonical
#print axioms Cordis.ParallelSchedule.Plan.execute_undo_eq_canonical
#print axioms Cordis.ParallelSchedule.Plan.execute_recovers
#print axioms Cordis.ParallelSchedule.Plan.execute_reports_ids_nodup
#print axioms Cordis.ParallelSchedule.Plan.execute_reports_model_order
#print axioms Cordis.ParallelSchedule.example_after
#print axioms Cordis.ParallelSchedule.example_reports
#print axioms Cordis.ParallelSchedule.example_recovers
#print axioms Cordis.RichStream.AlignedMetadata.hasFinalBlockCount
#print axioms Cordis.RichStream.noEventAfterTerminal
#print axioms Cordis.RichStream.noFinishWithoutUsage
#print axioms Cordis.RichStream.applyRaw_eraseEvent
#print axioms Cordis.RichStream.replayRaw_eraseTrace
#print axioms Cordis.RichStream.ValidatedChunk.applyRaw_eq
#print axioms Cordis.RichStream.ValidatedTrace.replayRaw_eq
#print axioms Cordis.RichStream.validate_interleaved_exact
#print axioms Cordis.RichStream.replay_interleaved_exact
#print axioms Cordis.RichStream.interleaved_rawArgumentsExact
#print axioms Cordis.RichStream.interleaved_metadataAligned
#print axioms Cordis.RichStream.reject_metadataLengthMismatch
#print axioms Cordis.RichStream.reject_afterErrorFinish
#print axioms Cordis.RichStream.reject_afterAbortFinish
#print axioms Cordis.StreamSession.toSessionToolCalls_length
#print axioms Cordis.StreamSession.interleavedPayload_exact
#print axioms Cordis.StreamSession.bridgedSession_messages
#print axioms Cordis.StreamSession.interleaved_assignment_is_unique
#print axioms Cordis.Coeffect.Observational.related_iff
#print axioms Cordis.Coeffect.Observational.contextSetoid
#print axioms Cordis.Coeffect.Observational.setAt_related
#print axioms Cordis.Coeffect.Observational.removeAt_related
#print axioms Cordis.Coeffect.Observational.setApplied_recovers
#print axioms Cordis.Coeffect.Observational.satisfies_iff_of_related
#print axioms Cordis.Coeffect.Observational.notify_eq_of_related
#print axioms Cordis.Coeffect.Observational.Example.left_related_right
#print axioms Cordis.UnifiedContext.InPlace.recover_eq
#print axioms Cordis.UnifiedContext.Derived.discard_eq
#print axioms Cordis.UnifiedContext.updateAt_commute
#print axioms Cordis.UnifiedContext.IsolatedContext.resolve_isolate_same
#print axioms Cordis.UnifiedContext.IsolatedContext.resolve_isolate_other
#print axioms Cordis.UnifiedContext.IsolatedContext.isolate_reassign
#print axioms Cordis.UnifiedContext.IsolatedContext.isolate_commute
#print axioms Cordis.UnifiedContext.IsolatedContext.setEffect_recovers
#print axioms Cordis.UnifiedContext.InterceptionContext.intercept_same
#print axioms Cordis.UnifiedContext.InterceptionContext.intercept_commute
#print axioms Cordis.UnifiedContext.InterceptionContext.get_intercept_assoc
#print axioms Cordis.UnifiedContext.InterceptionContext.setEffect_recovers
#print axioms Cordis.UnifiedContext.approximation_zero
#print axioms Cordis.UnifiedContext.approximation_succ
#print axioms Cordis.UnifiedContext.Layer.record_twice_recovers
#print axioms Cordis.UnifiedContext.Layer.liftCoeffect_recovers
#print axioms Cordis.UnifiedContext.pushApproximation_discard
#print axioms Cordis.RuntimeRefinement.WireUsage.toLocal
#print axioms Cordis.RuntimeRefinement.ValidatedJsonTrace.replay_eq
#print axioms Cordis.RuntimeRefinement.decode_example_exact
#print axioms Cordis.RuntimeRefinement.validate_example_exact
#print axioms Cordis.RuntimeRefinement.example_optionalUsage_normalization
#print axioms Cordis.RuntimeRefinement.reject_opaqueReplayState
#print axioms Cordis.RuntimeRefinement.reject_unmodeledErrorFinish
#print axioms Cordis.RuntimeRefinement.reject_unmodeledAbortedFinish
#print axioms Cordis.RuntimeRefinement.reject_semantic_noncontiguousStart
#print axioms Cordis.RuntimeRefinement.reject_unmodeledImageBlock
#print axioms Cordis.RuntimeRefinement.reject_unmodeledToolResultBlock
#print axioms Cordis.RuntimeRefinement.decode_toolCallDelta_exact
#print axioms Cordis.RuntimeRefinement.reject_nestedFieldType
#print axioms Cordis.RuntimeRefinement.reject_unsafeInteger
#print axioms Cordis.RuntimeFailureRefinement.decode_example_exact
#print axioms Cordis.RuntimeFailureRefinement.validate_example_exact
#print axioms Cordis.RuntimeFailureRefinement.decode_aborted_exact
#print axioms Cordis.RuntimeFailureRefinement.ValidatedFailureTrace.decoded_exact
#print axioms Cordis.RuntimeFailureRefinement.reject_successfulFinish
#print axioms Cordis.RuntimeFailureRefinement.reject_failureBeforeEnd
#print axioms Cordis.RuntimeFailureRefinement.reject_malformedFailure
#print axioms Cordis.RuntimeFailureRefinement.reject_opaqueReplayState
#print axioms Cordis.RuntimeOutcomeRefinement.validateOutcome_success
#print axioms Cordis.RuntimeOutcomeRefinement.validateOutcome_failure
#print axioms Cordis.RuntimeOutcomeRefinement.validateOutcome_neither
#print axioms Cordis.RuntimeOutcomeRefinement.ValidatedOutcome.success_decode_exact
#print axioms Cordis.RuntimeOutcomeRefinement.ValidatedOutcome.failure_decode_exact
#print axioms Cordis.RuntimeOutcomeRefinement.validate_successfulExample
#print axioms Cordis.RuntimeOutcomeRefinement.validate_failureExample
#print axioms Cordis.RuntimeOutcomeRefinement.neitherExample_rejected_by_both
#print axioms Cordis.RuntimeOutcomeSession.finishJson
#print axioms Cordis.RuntimeOutcomeSession.appendJson_messages
#print axioms Cordis.RuntimeOutcomeSession.appendJson_nextSeq
#print axioms Cordis.RuntimeOutcomeSession.appendJson_nextCall
#print axioms Cordis.RuntimeOutcomeSession.dispatchOutcome_failure
#print axioms Cordis.RuntimeOutcomeSession.dispatchOutcome_success
#print axioms Cordis.RuntimeOutcomeSession.validateAndDispatch_failureExample
#print axioms Cordis.RuntimeOutcomeSession.validateAndDispatch_successExample
#print axioms Cordis.RuntimeOutcomeSession.validateTextAndDispatch
#print axioms Cordis.RuntimeOutcomeSession.validateBytesAndDispatch
#print axioms Cordis.Observational.Quotient.Respects.comp
#print axioms Cordis.Observational.Quotient.MapRelated.comp
#print axioms Cordis.Observational.Quotient.AppliedRelated.trans
#print axioms Cordis.Observational.Quotient.Admissible.seq
#print axioms Cordis.Observational.Quotient.Program.run_admissible
#print axioms Cordis.Observational.Quotient.Program.accumulated_inverse_respects
#print axioms Cordis.Observational.Quotient.Program.recovers
#print axioms Cordis.Observational.Quotient.ofExact_admissible
#print axioms Cordis.Observational.Quotient.Example.program_recovers
#print axioms Cordis.Coeffect.Quotient.undoAt_related
#print axioms Cordis.Coeffect.Quotient.lift_results_related
#print axioms Cordis.Coeffect.Quotient.liftApplied
#print axioms Cordis.Coeffect.Quotient.Example.counter_lifts_related
#print axioms Cordis.OperationalEquivalence.indistinguishableSetoid
#print axioms Cordis.OperationalEquivalence.indistinguishable_admissible
#print axioms Cordis.OperationalEquivalence.contained_in_indistinguishable
#print axioms Cordis.OperationalEquivalence.declaredEquivalence_admissible
#print axioms Cordis.OperationalEquivalence.declaredEquivalence_contained
#print axioms Cordis.OperationalEquivalence.withOperationalEquivalence
#print axioms Cordis.OperationalEquivalence.Example.initial_not_indistinguishable_from_bumped
#print axioms Cordis.OperationalEquivalence.Example.leftContext_related_renamedContext
#print axioms Cordis.OperationalEquivalence.PairedGap.seeds_indistinguishable
#print axioms Cordis.OperationalEquivalence.PairedGap.pairedInverseCoherent_fails
#print axioms Cordis.SessionRefinement.RefinedEvent.projection_exact
#print axioms Cordis.SessionRefinement.RefinedEvent.events_eq
#print axioms Cordis.SessionRefinement.ValidatedSequence.protocolTrace_erase
#print axioms Cordis.SessionRefinement.ValidatedSequence.sessionProjection_eq
#print axioms Cordis.SessionRefinement.ValidatedJsonLog.projection_exact
#print axioms Cordis.SessionRefinement.validate_example
#print axioms Cordis.SessionRefinement.example_turnEndStep_isDerived
#print axioms Cordis.SessionRefinement.validate_message_example
#print axioms Cordis.SessionRefinement.validate_tool_message_example
#print axioms Cordis.SessionRefinement.validate_replacement_message_example
#print axioms Cordis.SessionRefinement.validate_header_chunk_example
#print axioms Cordis.SessionRefinement.validate_header_chunk_latestHeader
#print axioms Cordis.SessionRefinement.validate_metadata_example
#print axioms Cordis.SessionRefinement.reject_todo_unknownStatus
#print axioms Cordis.SessionRefinement.reject_sessionEndSeed_nonempty
#print axioms Cordis.SessionRefinement.reject_replacement_incompleteCoverage
#print axioms Cordis.SessionRefinement.accept_assistantChunk_reasoning
#print axioms Cordis.SessionRefinement.reject_assistantChunk_nonzeroIndex
#print axioms Cordis.SessionRefinement.reject_requestHeader_temperature
#print axioms Cordis.SessionRefinement.reject_surfaceMetadataOnStepStart
#print axioms Cordis.SessionRefinement.reject_ignorableCoreEvent
#print axioms Cordis.SessionRefinement.accept_abortedTurnEndReason
#print axioms Cordis.SessionRefinement.accept_blockedTurnEndReason
#print axioms Cordis.SessionRefinement.accept_interruptedTurnEndReason
#print axioms Cordis.SessionRefinement.accept_errorTurnEndReason
#print axioms Cordis.SessionRefinement.reject_mismatchedToolResultIds
#print axioms Cordis.SessionRefinement.reject_underdeterminedTurnEnd
#print axioms Cordis.SessionOpaqueMetadata.decodeEventRetainingMetadata
#print axioms Cordis.SessionOpaqueMetadata.validateLogRetainingMetadata
#print axioms Cordis.SessionOpaqueMetadata.metadata_example_valid
#print axioms Cordis.SessionOpaqueMetadata.metadata_example_retained
#print axioms Cordis.SessionOpaqueMetadata.metadata_example_exact
#print axioms Cordis.SessionOpaqueMetadata.metadata_example_projection
#print axioms Cordis.SessionArchive.decodeEnvelope_raw
#print axioms Cordis.SessionArchive.decodeEnvelopeAtPath_raw
#print axioms Cordis.SessionArchive.classify_raw
#print axioms Cordis.SessionArchive.ArchivedEvent.raw_eq_envelope_raw
#print axioms Cordis.SessionArchive.archive_example_tags
#print axioms Cordis.SessionArchive.archive_example_raw_preserved
#print axioms Cordis.SessionEventArchive.all_known_tags_covered
#print axioms Cordis.SessionEventArchive.all_known_raw_preserved
#print axioms Cordis.SessionEventArchive.reasoning_surface_is_known_opaque
#print axioms Cordis.SessionEventArchive.tool_result_meta_is_known_opaque
#print axioms Cordis.SessionEventArchive.reject_log_only_surface_metadata
#print axioms Cordis.SessionEventArchive.reject_known_nonobject_data
#print axioms Cordis.SessionEventArchive.extensions_remain_opaque
#print axioms Cordis.SessionPayloadArchive.PayloadLog.raw_exact
#print axioms Cordis.SessionPayloadArchive.PayloadLog.length_exact
#print axioms Cordis.SessionPayloadArchive.enrichEvent_raw
#print axioms Cordis.SessionPayloadArchive.RawContent.blocks_raw_exact
#print axioms Cordis.SessionPayloadArchive.RawMessage.content_raw_exact
#print axioms Cordis.HarnessPersistenceRefinement.decodeSessionHeader
#print axioms Cordis.HarnessPersistenceArchive.archivePersistedJson
#print axioms Cordis.HarnessPersistenceArchive.ArchivedPersistedJson.rows_raw_exact
#print axioms Cordis.HarnessPersistenceArchive.archive_persistence_example_tags
#print axioms Cordis.HarnessPersistenceArchive.archive_persistence_example_rows_preserved
#print axioms Cordis.HarnessPersistenceArchive.malformed_persisted_envelope_indexed
#print axioms Cordis.HarnessPersistenceRefinement.ValidatedPersistedJson.projection_exact
#print axioms Cordis.HarnessPersistenceRefinement.ValidatedPersistedJson.split_exact
#print axioms Cordis.HarnessPersistenceRefinement.ValidatedPersistedJson.expansion_exact
#print axioms Cordis.HarnessPersistenceRefinement.packedPersistenceExample_valid
#print axioms Cordis.HarnessPersistenceRefinement.packedReasoningPersistenceExample_valid
#print axioms Cordis.HarnessPersistenceRefinement.malformedPackedRow_rejected
#print axioms Cordis.HarnessPersistenceRefinement.foreignVersion_rejected
#print axioms Cordis.HarnessPersistenceRefinement.foreignHeaderTag_rejected
#print axioms Cordis.HarnessPersistenceBytes.validatePersistedBytes
#print axioms Cordis.HarnessPersistenceBytes.fromUTF8_toUTF8
#print axioms Cordis.HarnessPersistenceBytes.ValidatedPersistedBytes.decoded_exact
#print axioms Cordis.HarnessPersistenceBytes.ValidatedPersistedBytes.parsed_exact
#print axioms Cordis.HarnessPersistenceBytes.ValidatedPersistedBytes.projection_exact
#print axioms Cordis.HarnessPersistenceBytes.invalidUtf8Bytes_rejected
#print axioms Cordis.HarnessPersistenceIO.readValidated
#print axioms Cordis.HarnessPersistenceIO.ReadCertificate.projection_exact
#print axioms Cordis.HarnessPersistenceIO.appendValidatedRow
#print axioms Cordis.TextRefinement.parseJsonLines
#print axioms Cordis.TextRefinement.parseJsonLinesBytes
#print axioms Cordis.TextRefinement.validateStreamText
#print axioms Cordis.TextRefinement.validateSessionText
#print axioms Cordis.TextRefinement.validateFailureText
#print axioms Cordis.TextRefinement.validateFailureBytes
#print axioms Cordis.TextRefinement.validateOutcomeText
#print axioms Cordis.TextRefinement.validateOutcomeBytes
#print axioms Cordis.TextRefinement.ValidatedStreamText.replay_eq
#print axioms Cordis.TextRefinement.ValidatedFailureText.decoded_exact
#print axioms Cordis.TextRefinement.ValidatedSessionText.projection_exact
#print axioms Cordis.TextRefinement.invalid_utf8_rejected
#print axioms Cordis.DeepSeekApi.ChatRequest.toJson
#print axioms Cordis.DeepSeekApi.ChatRequest.asStreaming
#print axioms Cordis.DeepSeekApi.buildRequest
#print axioms Cordis.DeepSeekApi.buildRequest_body_eq
#print axioms Cordis.DeepSeekApi.buildStreamingRequest
#print axioms Cordis.DeepSeekApi.buildStreamingRequest_body_eq
#print axioms Cordis.DeepSeekApi.buildStreamingRequest_source_stream
#print axioms Cordis.DeepSeekApi.RequestMode.streamFlag
#print axioms Cordis.DeepSeekApi.TypedRequestPlan.source_stream
#print axioms Cordis.DeepSeekApi.buildTypedCompleteRequest
#print axioms Cordis.DeepSeekApi.buildTypedStreamingRequest
#print axioms Cordis.DeepSeekApi.executeComplete
#print axioms Cordis.DeepSeekApi.decodeResponseJson
#print axioms Cordis.DeepSeekApi.validateResponse
#print axioms Cordis.DeepSeekApi.execute
#print axioms Cordis.DeepSeekApiErrorEnvelope.validateApiError
#print axioms Cordis.DeepSeekApiErrorEnvelope.validateApiError_decoded
#print axioms Cordis.DeepSeekCurlTransport.parseOutput
#print axioms Cordis.DeepSeekCurlTransport.parseOutput_of_split
#print axioms Cordis.DeepSeekCurlTransport.runProcess
#print axioms Cordis.DeepSeekCurlTransport.curlTransport
#print axioms Cordis.DeepSeekCurlStream.executeSse
#print axioms Cordis.DeepSeekCurlStream.curlProcess
#print axioms Cordis.DeepSeekCurlOutcome.executeOutcome
#print axioms Cordis.DeepSeekOutcomeSession.dispatchOutcome
#print axioms Cordis.DeepSeekOutcomeSession.executeAndDispatchOutcome
#print axioms Cordis.DeepSeekOutcomeConversation.dispatchOutcome
#print axioms Cordis.DeepSeekOutcomeConversation.executeAndDispatchOutcome
#print axioms Cordis.DeepSeekOutcomeConversation.executeOutcomeWithTools
#print axioms Cordis.DeepSeekOutcomeConversation.executeAndRunOutcome
#print axioms Cordis.DeepSeekOutcomeConversationLoop.runOutcomeBodies
#print axioms Cordis.DeepSeekOutcomeConversationLoop.exampleRun
#print axioms Cordis.DeepSeekOutcomeTransportLoop.executeOutcomeTransportRound
#print axioms Cordis.DeepSeekOutcomeTransportLoop.runOutcomeTransport
#print axioms Cordis.DeepSeekOutcomeTransportLoop.Example.run
#print axioms Cordis.DeepSeekOutcomeTransportLoop.Example.apiFailureRun
#print axioms Cordis.DeepSeekCurlSession.executeWith
#print axioms Cordis.DeepSeekCurlSession.appendProcessed_nextSeq
#print axioms Cordis.DeepSeekCurlSession.appendProcessed_nextCall
#print axioms Cordis.DeepSeekCurlSession.executeAndAppendText
#print axioms Cordis.DeepSeekCurlIncremental.readBodyLines
#print axioms Cordis.DeepSeekCurlIncremental.executeSseIncremental
#print axioms Cordis.DeepSeekCurlPrefix.executeSsePrefix
#print axioms Cordis.DeepSeekCurlPrefix.PrefixResponse.isCompleted
#print axioms Cordis.DeepSeekCurlPrefixSession.executeWith
#print axioms Cordis.DeepSeekCurlPrefixSession.appendProcessed_nextSeq
#print axioms Cordis.DeepSeekStream.decodeStreamChunkJson
#print axioms Cordis.DeepSeekStream.parseSse
#print axioms Cordis.DeepSeekStream.parseSsePrefix
#print axioms Cordis.DeepSeekStream.validateSse
#print axioms Cordis.DeepSeekStreamFailure.projectFrames
#print axioms Cordis.DeepSeekStreamFailure.validateFailureStream
#print axioms Cordis.DeepSeekStreamFailure.validateFailureStream_reason
#print axioms Cordis.DeepSeekStreamFailure.validateFailureStream_terminal_choice
#print axioms Cordis.DeepSeekTerminalOutcome.validateTerminalOutcome
#print axioms Cordis.DeepSeekTerminalOutcome.validateTerminalOutcome_failure
#print axioms Cordis.DeepSeekTerminalOutcome.validateTerminalOutcome_text
#print axioms Cordis.DeepSeekTerminalOutcome.validateTerminalOutcome_tool
#print axioms Cordis.DeepSeekStreamIncremental.consumeLines
#print axioms Cordis.DeepSeekStreamIncremental.consumeBody
#print axioms Cordis.DeepSeekStream.validateSseBytes
#print axioms Cordis.DeepSeekRichStream.projectFrames
#print axioms Cordis.DeepSeekRichStream.validateTextStream
#print axioms Cordis.DeepSeekRichToolStream.projectFrames
#print axioms Cordis.DeepSeekRichToolStream.validateToolStream
#print axioms Cordis.DeepSeekRichMixedStream.projectFrames
#print axioms Cordis.DeepSeekRichMixedStream.projectChunks
#print axioms Cordis.DeepSeekRichMixedStream.validateMixedStream
#print axioms Cordis.DeepSeekRichMixedStream.project_mixed_chunks_exact
#print axioms Cordis.DeepSeekRichMixedStream.reject_sameFrame_mixedKinds
#print axioms Cordis.DeepSeekRichMultiStream.projectFrames
#print axioms Cordis.DeepSeekRichMultiStream.projectChunks
#print axioms Cordis.DeepSeekRichMultiStream.validateMultiStream
#print axioms Cordis.DeepSeekRichMultiStream.project_multi_chunks_exact
#print axioms Cordis.DeepSeekRichMultiStream.reject_mismatched_call_id
#print axioms Cordis.DeepSeekRichMultiStream.reject_multiple_choices
#print axioms Cordis.DeepSeekSessionBridge.finishAssistant
#print axioms Cordis.DeepSeekSessionBridge.appendFinishedAssistant_messages
#print axioms Cordis.DeepSeekSessionRunner.finishText
#print axioms Cordis.DeepSeekSessionRunner.finishMixed
#print axioms Cordis.DeepSeekSessionRunner.finishMulti
#print axioms Cordis.DeepSeekSessionRunner.Runner.append
#print axioms Cordis.DeepSeekSessionRunner.Runner.appendMixed
#print axioms Cordis.DeepSeekSessionRunner.Runner.appendMulti
#print axioms Cordis.DeepSeekSessionRunner.Runner.append_session_messages
#print axioms Cordis.DeepSeekApiSession.acceptResponse
#print axioms Cordis.DeepSeekApiSession.Runner.appendApi
#print axioms Cordis.DeepSeekApiSession.Runner.appendApi_session_messages
#print axioms Cordis.DeepSeekHarness.buildChatRequest
#print axioms Cordis.DeepSeekHarness.buildTypedCompleteRequestPlan
#print axioms Cordis.DeepSeekHarness.buildTypedStreamingRequestPlan
#print axioms Cordis.DeepSeekHarness.buildTypedStreamingRequestPlan_source_stream
#print axioms Cordis.DeepSeekHarness.buildStreamingRequestPlan
#print axioms Cordis.DeepSeekHarness.buildStreamingRequestPlan_source_stream
#print axioms Cordis.DeepSeekHarness.executeFunctionCall
#print axioms Cordis.DeepSeekHarness.executeFunctionCalls
#print axioms Cordis.DeepSeekHarness.executeRound
#print axioms Cordis.DeepSeekHarness.executedTool_provider_reply
#print axioms Cordis.DeepSeekHarness.appendExecutedToolResult
#print axioms Cordis.DeepSeekHarness.executedToolResultJson_decodes
#print axioms Cordis.DeepSeekHarness.appendExecutedToolResults
#print axioms Cordis.DeepSeekHarness.appendRoundToolResults
#print axioms Cordis.DeepSeekHarness.appendRoundToolResults_messages
#print axioms Cordis.DeepSeekHarness.appendRoundToolResults_protocolProjection
#print axioms Cordis.DeepSeekHarness.executedToolMessages_toolCallCount
#print axioms Cordis.DeepSeekHarness.ConversationRunner.appendAcceptedApi
#print axioms Cordis.DeepSeekHarness.ConversationRunner.appendAcceptedApi_session_messages
#print axioms Cordis.DeepSeekHarness.ConversationRunner.appendAcceptedApi_nextCall
#print axioms Cordis.DeepSeekHarness.ConversationRunner.appendAcceptedApi_nextSeq
#print axioms Cordis.DeepSeekHarness.ConversationRunner.afterRound
#print axioms Cordis.DeepSeekHarness.ConversationRunner.afterRound_session_messages
#print axioms Cordis.DeepSeekHarness.ConversationRunner.appendToolResults
#print axioms Cordis.DeepSeekHarness.ConversationRunner.appendToolResults_session_messages
#print axioms Cordis.DeepSeekHarness.executeConversationRound
#print axioms Cordis.DeepSeekHarnessErrors.executeFunctionCallRecoverable
#print axioms Cordis.DeepSeekHarnessErrors.executeFunctionCallsRecoverable
#print axioms Cordis.DeepSeekHarnessErrors.ConversationRunner.appendRecoverableToolResults
#print axioms Cordis.DeepSeekHarnessErrors.executeConversationRoundRecoverable
#print axioms Cordis.DeepSeekHarnessRetry.executeWithRetry
#print axioms Cordis.DeepSeekHarnessRetry.executeConversationRoundRetry
#print axioms Cordis.DeepSeekHarnessCancellation.runConversationCancellable
#print axioms Cordis.DeepSeekHarness.ConversationStop.isCompleted
#print axioms Cordis.DeepSeekHarness.runConversationAux
#print axioms Cordis.DeepSeekHarness.runConversation
#print axioms Cordis.DeepSeekHarnessPersistence.restoreRunner
#print axioms Cordis.DeepSeekHarnessPersistence.RestoredRunner.session_messages_eq
#print axioms Cordis.DeepSeekHarnessPersistence.RestoredRunner.nextSeq_eq
#print axioms Cordis.DeepSeekHarnessPersistence.buildRequestCertificate
#print axioms Cordis.DeepSeekHarnessPersistence.buildRequest_session_eq_archive
#print axioms Cordis.DeepSeekHarnessPersistence.persistedToolRequest_messages
#print axioms Cordis.DeepSeekHarnessPersistenceIO.restoreRead
#print axioms Cordis.DeepSeekHarnessPersistenceIO.RestoredRunner.session_eq_read
#print axioms Cordis.DeepSeekHarnessPersistenceIO.RestoredRunner.raw_rows_eq_input
#print axioms Cordis.DeepSeekHarnessPersistenceIO.buildRequestCertificate
#print axioms Cordis.DeepSeekHarnessPersistenceIO.buildRequest_session_eq_read
#print axioms Cordis.DeepSeekHarnessPersistenceIO.readRunner
#print axioms Cordis.DeepSeekHarnessPersistenceIO.replaceAndRestore
#print axioms Cordis.DeepSeekHarnessPersistenceIO.appendAndRestore
#print axioms Cordis.DeepSeekHarnessPersistenceIO.fixtureMemory
#print axioms Cordis.DeepSeekHarnessPersistenceIO.fixtureAppend
#print axioms Cordis.DeepSeekHarnessPersistenceIO.fixtureFile
#print axioms Cordis.DeepSeekHarnessPersistenceIO.fixtureRequest
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.restoreRunner
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.RestoredRunner.session_eq_log
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.RestoredRunner.metadata_eq_source
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.buildRequestCertificate
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.buildRequest_session_eq_log
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.metadataRestored
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.metadataRestored_valid
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.metadataRestored_metadata_exact
#print axioms Cordis.DeepSeekHarnessOpaqueMetadata.metadataRestored_request_messages
#print axioms Cordis.DeepSeekHarnessMetadataArchive.validate
#print axioms Cordis.DeepSeekHarnessMetadataArchive.AttachedLog.raw_exact
#print axioms Cordis.DeepSeekHarnessMetadataArchive.AttachedLog.metadata_eq_source
#print axioms Cordis.DeepSeekHarnessMetadataArchive.AttachedLog.sanitized_eq_source
#print axioms Cordis.DeepSeekHarnessMetadataArchive.restoreRunner
#print axioms Cordis.DeepSeekHarnessMetadataArchive.RestoredRunner.session_eq_log
#print axioms Cordis.DeepSeekHarnessMetadataArchive.buildRequestCertificate
#print axioms Cordis.DeepSeekHarnessMetadataArchive.buildRequest_session_eq_log
#print axioms Cordis.DeepSeekHarnessMetadataArchive.metadataAttached
#print axioms Cordis.DeepSeekHarnessMetadataArchive.metadataAttached_valid
#print axioms Cordis.DeepSeekHarnessMetadataArchive.metadataAttached_has_one_opaque_event
#print axioms Cordis.DeepSeekHarnessMetadataArchive.metadataRestored_metadata_exact
#print axioms Cordis.DeepSeekHarnessMetadataArchive.metadataRestored_request_messages
#print axioms Cordis.DeepSeekToolSchema.validateParameters
#print axioms Cordis.DeepSeekToolSchema.ValidatedParameters.raw_eq
#print axioms Cordis.DeepSeekToolSchema.validateArguments
#print axioms Cordis.DeepSeekToolSchema.ValidatedToolDefinition.validateArguments
#print axioms Cordis.DeepSeekToolSchema.validateToolDefinition
#print axioms Cordis.DeepSeekToolSchema.validateRequestSource
#print axioms Cordis.DeepSeekToolSchema.CertifiedRequestSource.buildRequestPlan
#print axioms Cordis.DeepSeekToolSchema.CertifiedRequestSource.buildTypedStreamingRequestPlan
#print axioms Cordis.DeepSeekToolAdmission.validateFunctionCall
#print axioms Cordis.DeepSeekToolAdmission.CertifiedFunctionCall.call_name_eq
#print axioms Cordis.DeepSeekToolAdmission.CertifiedFunctionCall.arguments_parse_eq
#print axioms Cordis.DeepSeekGenericBridge.validateAndAdmit
#print axioms Cordis.DeepSeekGenericBridge.SchemaCheckedCall.provider_name_eq
#print axioms Cordis.DeepSeekGenericBridge.validateAndAdmit_provider_name_eq
#print axioms Cordis.DeepSeekGenericBridge.validateAndAdmit_generic_tool_eq
#print axioms Cordis.DeepSeekGenericBridge.Example.weatherAccepted
#print axioms Cordis.DeepSeekSchemaExecution.executeCertifiedCall
#print axioms Cordis.DeepSeekSchemaExecution.ExecutedCall.generic_tool_eq
#print axioms Cordis.DeepSeekSchemaExecution.Example.weatherExecutionAccepted
#print axioms Cordis.DeepSeekSchemaHarness.SchemaExecutedTool.toExecutedTool
#print axioms Cordis.DeepSeekSchemaHarness.executeCertifiedFunctionCall
#print axioms Cordis.DeepSeekSchemaHarness.appendCertifiedToolResult_messages
#print axioms Cordis.DeepSeekSchemaHarness.appendCertifiedToolResult_protocolProjection
#print axioms Cordis.DeepSeekSchemaHarness.Example.weatherAppended
#print axioms Cordis.DeepSeekSchemaHarness.appendCertifiedToolResultToRunner
#print axioms Cordis.DeepSeekSchemaHarness.appendCertifiedToolResultToRunner_messages
#print axioms Cordis.DeepSeekSchemaHarness.Example.weatherRunnerAppended
#print axioms Cordis.DeepSeekSchemaRound.singleToolCall
#print axioms Cordis.DeepSeekSchemaRound.executeSchemaRound
#print axioms Cordis.DeepSeekSchemaRound.SchemaRoundResult.finalRunner_nextCall
#print axioms Cordis.DeepSeekSchemaRound.Example.weatherRoundAccepted
#print axioms Cordis.DeepSeekSchemaRound.Example.emptyResponseRejected
#print axioms Cordis.DeepSeekSchemaMultiRound.acceptToolCalls
#print axioms Cordis.DeepSeekSchemaMultiRound.executeSchemaCalls
#print axioms Cordis.DeepSeekSchemaMultiRound.appendSchemaToolResultsToRunner_nextSeq
#print axioms Cordis.DeepSeekSchemaMultiRound.Example.twoWeatherRoundAccepted
#print axioms Cordis.DeepSeekSchemaMultiRound.Example.wrongSecondNameRejected
#print axioms Cordis.DeepSeekSchemaRegistry.resolveSchemaTool
#print axioms Cordis.DeepSeekSchemaRegistry.resolveSchemaTool_unique_name
#print axioms Cordis.DeepSeekSchemaRegistry.executeSchemaRegistryCalls
#print axioms Cordis.DeepSeekSchemaRegistry.appendSchemaRegistryResultsToRunner_nextSeq
#print axioms Cordis.DeepSeekSchemaRegistry.SchemaRegistryRoundResult.finalRunner_nextSeq
#print axioms Cordis.DeepSeekSchemaRegistry.Example.dualRoundAccepted
#print axioms Cordis.DeepSeekSchemaRegistry.Example.unknownToolRejected
#print axioms Cordis.DeepSeekSchemaConversation.registryToolDefinitions
#print axioms Cordis.DeepSeekSchemaConversation.executeSchemaRegistryConversationRound
#print axioms Cordis.DeepSeekSchemaConversation.SchemaRegistryConversationResult.finalRunner_nextSeq
#print axioms Cordis.DeepSeekSchemaConversationLoop.executeSchemaRegistryConversationStep
#print axioms Cordis.DeepSeekSchemaConversationLoop.runSchemaConversation
#print axioms Cordis.DeepSeekSchemaConversationLoop.SchemaConversationStop
#print axioms Cordis.DeepSeekSchemaStreamConversation.registryValidatedTools
#print axioms Cordis.DeepSeekSchemaStreamConversation.registryCertifiedRequestSource
#print axioms Cordis.DeepSeekSchemaStreamConversation.executeSchemaStreamConversationStep
#print axioms Cordis.DeepSeekSchemaStreamConversation.runSchemaStreamConversation
#print axioms Cordis.DeepSeekSchemaStreamConversation.SchemaStreamConversationStop
#print axioms Cordis.DeepSeekSchemaStreamPrefixConversation.executeSchemaStreamPrefixRound
#print axioms Cordis.DeepSeekSchemaStreamPrefixConversation.runSchemaStreamPrefixConversation
#print axioms Cordis.DeepSeekSchemaStreamPrefixConversation.SchemaPrefixConversationStop
#print axioms Cordis.DeepSeekSchemaStreamErrors.executeSchemaRegistryFunctionCallRecoverable
#print axioms Cordis.DeepSeekSchemaStreamErrors.executeSchemaRegistryCallsRecoverable
#print axioms Cordis.DeepSeekSchemaStreamErrors.executeSchemaStreamRecoverableRound
#print axioms Cordis.DeepSeekSchemaStreamErrors.runSchemaStreamRecoverable
#print axioms Cordis.DeepSeekSchemaStreamErrors.SchemaStreamRecoverableStop
#print axioms Cordis.DeepSeekHarnessEventArchive.restoreRunner
#print axioms Cordis.DeepSeekHarnessEventArchive.RestoredRunner.session_eq_archive
#print axioms Cordis.DeepSeekHarnessEventArchive.RestoredRunner.archive_raw_eq_input
#print axioms Cordis.DeepSeekHarnessEventArchive.RestoredRunner.all_events_supported
#print axioms Cordis.DeepSeekHarnessEventArchive.buildRequestCertificate
#print axioms Cordis.DeepSeekHarnessEventArchive.buildRequest_session_eq_archive
#print axioms Cordis.DeepSeekHarnessEventArchive.toolRestored
#print axioms Cordis.DeepSeekHarnessEventText.restoreTextRunner
#print axioms Cordis.DeepSeekHarnessEventText.restoreBytesRunner
#print axioms Cordis.DeepSeekHarnessEventText.RestoredTextRunner.session_eq
#print axioms Cordis.DeepSeekHarnessEventText.RestoredTextRunner.archive_raw_eq_lines
#print axioms Cordis.DeepSeekHarnessEventText.RestoredBytesRunner.decoded_eq
#print axioms Cordis.DeepSeekHarnessEventText.buildRequestCertificate
#print axioms Cordis.DeepSeekHarnessEventText.toolTextRestored
#print axioms Cordis.DeepSeekHarnessEventText.toolBytesRestored
#print axioms Cordis.DeepSeekStreamHarness.projectedToolCallToFunctionCall
#print axioms Cordis.DeepSeekStreamHarness.ConversationRunner.appendFinished
#print axioms Cordis.DeepSeekStreamHarness.ConversationRunner.appendFinished_session_messages
#print axioms Cordis.DeepSeekStreamHarness.executeConversationStreamRound
#print axioms Cordis.DeepSeekStreamHarness.executeConversationMultiStreamRound
#print axioms Cordis.DeepSeekStreamHarness.runConversationMultiStream
#print axioms Cordis.DeepSeekStreamHarnessCancellation.runConversationMultiStreamCancellable
#print axioms Cordis.DeepSeekStreamHarnessPrefix.executeConversationMultiStreamPrefixRound
#print axioms Cordis.Transformation.Closure.commute
#print axioms Cordis.Transformation.commute_of_generators
#print axioms Cordis.Transformation.seq_monoid_subset_joint
#print axioms Cordis.Transformation.inverseStable_of_generators
#print axioms Cordis.Transformation.Independent.of_generators
#print axioms Cordis.Transformation.Independent.independentAt
#print axioms Cordis.Transformation.Independent.seq_commute
#print axioms Cordis.Transformation.Example.either_order_same
#print axioms Cordis.OperationIndependence.outcomeStable_of_generators
#print axioms Cordis.OperationIndependence.ExactOperationIndependent.of_generators
#print axioms Cordis.OperationIndependence.ExactOperationIndependent.seq_effect_eq
#print axioms Cordis.OperationIndependence.applyLocal_commute
#print axioms Cordis.OperationIndependence.inspectForwardAt_stable_of_other
#print axioms Cordis.OperationIndependence.distinctKeys_finiteIndependent
#print axioms Cordis.OperationIndependence.Computation.run_recovers
#print axioms Cordis.OperationIndependence.Example.Exact.independent
#print axioms Cordis.OperationIndependence.Example.ForwardOnlyGap.inverse_stability_fails
#print axioms Cordis.GlobalRegistry.WellFormed.activeProvider_unique
#print axioms Cordis.GlobalRegistry.WellFormed.activeValue_unique
#print axioms Cordis.GlobalRegistry.activeContext_value_iff
#print axioms Cordis.GlobalRegistry.IsTargetView.unique
#print axioms Cordis.GlobalRegistry.targetView_sound
#print axioms Cordis.GlobalRegistry.targetView_eq_of_isTarget
#print axioms Cordis.GlobalRegistry.preserve_insert
#print axioms Cordis.GlobalRegistry.preserve_retire
#print axioms Cordis.GlobalRegistry.preserve_remove
#print axioms Cordis.GlobalRegistry.OrchestrationStep.preservesWellFormed
#print axioms Cordis.GlobalRegistry.Ancestor.birth_lt
#print axioms Cordis.GlobalRegistry.parent_acyclic
#print axioms Cordis.GlobalRegistry.Trace.preservesWellFormed
#print axioms Cordis.GlobalRegistry.Example.orchestrationTrace_preserves
#print axioms Cordis.Removal.execution_retainedInverses
#print axioms Cordis.Removal.RemovalTrace.step
#print axioms Cordis.Removal.buildRemovalTrace
#print axioms Cordis.Removal.removal_forward_relation
#print axioms Cordis.Removal.removal_inverse_relation
#print axioms Cordis.Removal.later_inverses_unchanged
#print axioms Cordis.Removal.RemovalTrace.suffix_occurrence_has_inverseAgreement
#print axioms Cordis.Removal.applyMaps_eq_of_perm
#print axioms Cordis.Removal.reverse_yieldedInverses_recovers
#print axioms Cordis.Removal.headInverse_commutes_yielded
#print axioms Cordis.Removal.yieldedInverses_commuting
#print axioms Cordis.Removal.inverse_permutation_recovers
#print axioms Cordis.Removal.Example.pairwise
#print axioms Cordis.Removal.Example.inverseOrder_permutation
#print axioms Cordis.MediatedIndependence.RealizedPath.run_eq_some
#print axioms Cordis.MediatedIndependence.ObservationalMediatedClosure.toExact
#print axioms Cordis.MediatedIndependence.Counterexample.results_related
#print axioms Cordis.MediatedIndependence.Counterexample.sequential_results_related
#print axioms Cordis.MediatedIndependence.Counterexample.exact_mediatedClosure_fails
#print axioms Cordis.MediatedIndependence.Counterexample.representative_coherence_fails
#print axioms Cordis.MediatedIndependence.BranchExample.firstStage_outcome
#print axioms Cordis.MediatedIndependence.BranchExample.path
#print axioms Cordis.MediatedTheorem.PairwiseOverlap.left_continuation
#print axioms Cordis.MediatedTheorem.liftedInverses_commute
#print axioms Cordis.MediatedTheorem.stageInterchangeComplete
#print axioms Cordis.MediatedTheorem.stageOutcomeAlignment
#print axioms Cordis.MediatedTheorem.swap_executed_stages
#print axioms Cordis.MediatedTheorem.evaluate_step
#print axioms Cordis.MediatedTheorem.rawStage_interchange
#print axioms Cordis.MediatedTheorem.rawStage_movesAcross
#print axioms Cordis.MediatedTheorem.rawComputation_swap_success
#print axioms Cordis.MediatedTheorem.evaluateSequential_commute
#print axioms Cordis.MediatedTheorem.RawMediatedIndependence.toBoundedPartial
#print axioms Cordis.MediatedTheorem.pairwiseOverlap_boundedPartialIndependence
#print axioms Cordis.MediatedTheorem.partialPairwiseOverlapComplete
#print axioms Cordis.MediatedTheorem.Example.old_pairwiseOverlapComplete_fails
#print axioms Cordis.MediatedTheorem.Example.IndependentBranching.overlap
#print axioms Cordis.MediatedTheorem.Example.IndependentBranching.independent
#print axioms Cordis.PartialTransformation.Closure.commute
#print axioms Cordis.PartialTransformation.inverse_mem_stageInverseClosure
#print axioms Cordis.PartialTransformation.stageInverseGenerators_commute
#print axioms Cordis.PartialTransformation.yieldedInverses_commute
#print axioms Cordis.PartialTransformation.evaluate_map_stageInverse
#print axioms Cordis.PartialTransformation.yieldedInverse_forward_commutes
#print axioms Cordis.PartialTransformation.evaluate_yield_stable_under_evaluate
#print axioms Cordis.PartialTransformation.yieldStable_forward
#print axioms Cordis.PartialTransformation.forward_commutes
#print axioms Cordis.PartialTransformation.Independent.toRawMediated
#print axioms Cordis.PartialTransformation.Independent.toBoundedPartial
#print axioms Cordis.PartialTransformation.pairwiseOverlap_independent
#print axioms Cordis.PartialTransformation.Example.fullIndependent
#print axioms Cordis.PartialTransformation.WholeRunGap.wholeRun
#print axioms Cordis.PartialTransformation.WholeRunGap.full_independence_fails
#print axioms Cordis.ObservationalPartialTransformation.Closure.respects
#print axioms Cordis.ObservationalPartialTransformation.closure_iff_exact
#print axioms Cordis.ObservationalPartialTransformation.evaluate_related
#print axioms Cordis.ObservationalPartialTransformation.computation_generators_respect
#print axioms Cordis.ObservationalPartialTransformation.independent_of_exact
#print axioms Cordis.ObservationalPartialTransformation.pairwiseOverlap_independent
#print axioms Cordis.ObservationalPartialTransformation.pairwiseOverlap_full_and_wholeRun
#print axioms Cordis.ObservationalPartialTransformation.RespectGap.bad_not_respects
#print axioms Cordis.ObservationalPartialTransformation.RespectGap.observational_commutation_fails
#print axioms Cordis.ObservationalPartialTransformation.Example.independent
#print axioms Cordis.GlobalDynamics.Dynamics.applyUndo_respects
#print axioms Cordis.GlobalDynamics.Dynamics.recover_respects
#print axioms Cordis.GlobalDynamics.Dynamics.recover_append
#print axioms Cordis.GlobalDynamics.RegistrationAdmission.after_wellFormed
#print axioms Cordis.GlobalDynamics.IterationStep.preservesWellFormed
#print axioms Cordis.GlobalDynamics.executeOne
#print axioms Cordis.GlobalDynamics.Accumulator.seq
#print axioms Cordis.GlobalDynamics.Trace.preservesWellFormed
#print axioms Cordis.GlobalDynamics.RunResult.recovers
#print axioms Cordis.GlobalDynamics.RunResult.preservesWellFormed
#print axioms Cordis.GlobalDynamics.Example.ordinary_then_registration
#print axioms Cordis.GlobalDynamics.Example.one_fuel_retains_next_code
#print axioms Cordis.GlobalDynamics.Example.complete_run_recovers_ambient
#print axioms Cordis.GlobalLifecycle.setPhase_inactive_preserves
#print axioms Cordis.GlobalLifecycle.Landing.committedSafe
#print axioms Cordis.GlobalLifecycle.Transition.preservesWellFormed
#print axioms Cordis.GlobalLifecycle.Transition.rule_inventory
#print axioms Cordis.GlobalLifecycle.Transition.iterator_map_iff
#print axioms Cordis.GlobalLifecycle.Transition.recovery_map_iff
#print axioms Cordis.GlobalLifecycle.Trace.preservesWellFormed
#print axioms Cordis.GlobalLifecycle.Example.firstStep_executed
#print axioms Cordis.GlobalLifecycle.Example.finalStep_executed
#print axioms Cordis.GlobalLifecycle.Example.bridgedPath_wellFormed
#print axioms Cordis.GlobalLifecycle.Example.unloaded_phase_exact
#print axioms Cordis.GlobalLifecycle.Example.unloaded_ambient_exact
#print axioms Cordis.GlobalLifecycle.Example.stable_leave_guard_rejected
#print axioms Cordis.GlobalLifecycle.Example.abort_guard_rejected
#print axioms Cordis.GlobalLifecycle.Example.raise_guard_rejected
#print axioms Cordis.GlobalCalculus.allRules_nodup
#print axioms Cordis.GlobalCalculus.Step.actor_exact
#print axioms Cordis.GlobalCalculus.Step.orchestration_map_identity
#print axioms Cordis.GlobalCalculus.Step.identity_map_iff_footprint
#print axioms Cordis.GlobalCalculus.Step.recovery_map_iff
#print axioms Cordis.GlobalCalculus.Step.preservesWellFormed
#print axioms Cordis.GlobalCalculus.Step.installation_semantics
#print axioms Cordis.GlobalCalculus.Step.installedAt_change_only_boundary
#print axioms Cordis.GlobalCalculus.Trace.preservesWellFormed
#print axioms Cordis.GlobalCalculus.FromEmpty.final_wellFormed
#print axioms Cordis.GlobalCalculus.Example.unified_rule_projection
#print axioms Cordis.GlobalCalculus.Example.unified_stateMap_projection
#print axioms Cordis.GlobalCalculus.Example.unified_endpoint_exact
#print axioms Cordis.GlobalTraceFacts.iteration_foreign_lookup
#print axioms Cordis.GlobalTraceFacts.iteration_owner_static
#print axioms Cordis.GlobalTraceFacts.foreignExact_of_notUnload
#print axioms Cordis.GlobalTraceFacts.foreignTables_preserved
#print axioms Cordis.GlobalTraceFacts.foreignControl_continuous
#print axioms Cordis.GlobalTraceFacts.actorStatic_continuous
#print axioms Cordis.GlobalTraceFacts.namedCommitted_continuous
#print axioms Cordis.GlobalTraceFacts.accumulatedRecovery_iff_unload
#print axioms Cordis.GlobalTraceFacts.Trace.aligned
#print axioms Cordis.GlobalTraceFacts.Trace.states_length
#print axioms Cordis.GlobalTraceFacts.Trace.installedAt_forward
#print axioms Cordis.GlobalTraceFacts.BoundedEpisode.interior_close_installed
#print axioms Cordis.GlobalTraceFacts.BoundedEpisode.open_rule
#print axioms Cordis.GlobalTraceFacts.BoundedEpisode.close_rule
#print axioms Cordis.GlobalTraceFacts.Counterexample.bareAdmission_breaks_foreignTables
#print axioms Cordis.GlobalTraceFacts.Counterexample.bareAdmission_not_recoveryConfinement
#print axioms Cordis.GlobalTemporal.Step.partialMap_source
#print axioms Cordis.GlobalTemporal.EffectEquiv.recover_respects
#print axioms Cordis.GlobalTemporal.Intervening.replay_respects
#print axioms Cordis.GlobalTemporal.Intervening.endpoint_related
#print axioms Cordis.GlobalTemporal.accumulatedCommutes_of_perStep
#print axioms Cordis.GlobalTemporal.recover_interleaved
#print axioms Cordis.GlobalTemporal.terminal_recovery
#print axioms Cordis.GlobalTemporal.terminal_unload_recovery
#print axioms Cordis.GlobalTemporal.Counterexample.iterator_has_no_totalization
#print axioms Cordis.GlobalTemporal.Counterexample.universal_relation_is_vacuous_here
#print axioms Cordis.GlobalTemporal.Counterexample.ambientRecovery_confinement
#print axioms Cordis.GlobalTemporal.Counterexample.recoveryConfinement_not_temporal
#print axioms Cordis.GlobalIteratorIndependence.YieldAgrees.trans
#print axioms Cordis.GlobalIteratorIndependence.yieldStable_identity
#print axioms Cordis.GlobalIteratorIndependence.YieldStable.comp
#print axioms Cordis.GlobalIteratorIndependence.yieldStable_of_generators
#print axioms Cordis.GlobalIteratorIndependence.Independent.of_generators
#print axioms Cordis.GlobalIteratorIndependence.Independent.symm
#print axioms Cordis.GlobalIteratorIndependence.self_independent_of_duplicate
#print axioms Cordis.GlobalIteratorIndependence.generator_respects
#print axioms Cordis.GlobalIteratorIndependence.closure_respects
#print axioms Cordis.GlobalIteratorIndependence.observationalYieldAgrees_of_exact
#print axioms Cordis.GlobalIteratorIndependence.observationalYieldStable_of_exact
#print axioms Cordis.GlobalIteratorIndependence.observationalIndependent_of_exact
#print axioms Cordis.GlobalIteratorIndependence.recovery_mem
#print axioms Cordis.GlobalIteratorIndependence.StepMapMember.of_forward
#print axioms Cordis.GlobalIteratorIndependence.StepMapMember.of_identity
#print axioms Cordis.GlobalIteratorIndependence.StepMapMember.of_recovery
#print axioms Cordis.GlobalIteratorIndependence.recoveryCommutesWithMap
#print axioms Cordis.GlobalIteratorIndependence.observationalRecoveryCommutesWithMap
#print axioms Cordis.GlobalIteratorIndependence.perStepCommutes_of_generated
#print axioms Cordis.GlobalIteratorIndependence.Example.root_reachable
#print axioms Cordis.GlobalIteratorIndependence.Example.continuation_reachable
#print axioms Cordis.GlobalIteratorIndependence.Example.root_forward_at_source
#print axioms Cordis.GlobalIteratorIndependence.Example.first_inverse_generated
#print axioms Cordis.GlobalIteratorIndependence.Example.not_self_independent
#print axioms Cordis.GlobalIteratorIndependence.RawRegistrationGap.same_component
#print axioms
  Cordis.GlobalIteratorIndependence.RawRegistrationGap.continuation_depends_on_chosen_child
#print axioms
  Cordis.GlobalIteratorIndependence.RawRegistrationGap.retirement_inverse_depends_on_chosen_child
#print axioms Cordis.GlobalIteratorIndependence.WholeRunCounterexample.duplicatedFamily_wholeRun
#print axioms
  Cordis.GlobalIteratorIndependence.WholeRunCounterexample.duplicatedFamily_not_pairwise_full
#print axioms Cordis.GlobalIteratorIndependence.TotalizationGap.exact_iterator_has_no_totalization
#print axioms Cordis.GlobalTransposition.independent_forward_diamond
#print axioms Cordis.GlobalTransposition.TotalProgramStep.commute_exact
#print axioms Cordis.GlobalTransposition.TotalProgramStep.commute_effect
#print axioms Cordis.GlobalTransposition.LifecycleYieldAgrees.toYieldAgrees
#print axioms Cordis.GlobalTransposition.setPhase_commute
#print axioms Cordis.GlobalTransposition.Counterexample.interpreted_inverses_equal
#print axioms Cordis.GlobalTransposition.Counterexample.semantic_yields_agree
#print axioms Cordis.GlobalTransposition.Counterexample.undo_codes_differ
#print axioms Cordis.GlobalTransposition.Counterexample.lifecycle_yields_do_not_agree
#print axioms Cordis.GlobalForeignPhase.IterationStep.owner_present
#print axioms Cordis.GlobalForeignPhase.insertFiber_setPhase_commute
#print axioms Cordis.GlobalForeignPhase.ForeignPhaseCompatibility.of_read_frames
#print axioms Cordis.GlobalForeignPhase.ForeignPhaseCompatibility.frame
#print axioms Cordis.GlobalForeignPhase.phase_framed_diamond
#print axioms Cordis.GlobalForeignPhase.IndependenceGap.forwards_commute
#print axioms Cordis.GlobalForeignPhase.IndependenceGap.programs_independent
#print axioms Cordis.GlobalForeignPhase.IndependenceGap.semantic_yields_agree
#print axioms Cordis.GlobalForeignPhase.IndependenceGap.foreign_edit_not_readEquivalent
#print axioms
  Cordis.GlobalForeignPhase.IndependenceGap.independent_not_foreignPhaseCompatible
#print axioms Cordis.GlobalForeignPhase.OrdinaryFrameGap.run_read_confined_at_edit
#print axioms Cordis.GlobalForeignPhase.OrdinaryFrameGap.exact_frame_fails
#print axioms Cordis.GlobalForeignPhase.OrdinaryFrameGap.no_ordinary_frame
#print axioms
  Cordis.GlobalForeignPhase.OrdinaryFrameGap.readability_does_not_supply_ordinary_frame
#print axioms Cordis.GlobalForeignPhase.OracleGap.raw_request_stable
#print axioms Cordis.GlobalForeignPhase.OracleGap.moved_executeOne_rejected
#print axioms
  Cordis.GlobalForeignPhase.OracleGap.raw_read_stability_does_not_imply_oracle_frame
#print axioms Cordis.GlobalLandingTransposition.LifecycleYieldAgrees.refl
#print axioms Cordis.GlobalLandingTransposition.LifecycleYieldAgrees.trans
#print axioms Cordis.GlobalLandingTransposition.lifecycle_forward_diamond
#print axioms Cordis.GlobalLandingTransposition.LandingProgramWitness.step_eq
#print axioms Cordis.GlobalLandingTransposition.no_program_witness_of_undo_ne
#print axioms
  Cordis.GlobalLandingTransposition.ProgramAlignedLandingActivation.transition_rule
#print axioms
  Cordis.GlobalLandingTransposition.ProgramAlignedLandingActivation.preservesWellFormed
#print axioms
  Cordis.GlobalLandingTransposition.ProgramAlignedLandingActivation.foreign_present_after
namespace Cordis.GlobalLandingTransposition.ProgramAlignedLandingActivation
#print axioms targetView_preserved_by_foreign_landing
end Cordis.GlobalLandingTransposition.ProgramAlignedLandingActivation
#print axioms Cordis.GlobalLandingTransposition.reframeActivation
#print axioms Cordis.GlobalLandingTransposition.landing_activation_diamond
#print axioms Cordis.GlobalLandingTransposition.YieldSyntaxGap.semantic_cross_yield
#print axioms Cordis.GlobalLandingTransposition.YieldSyntaxGap.no_exact_cross_yield
#print axioms Cordis.GlobalLandingTransposition.YieldSyntaxGap.programs_independent
#print axioms
  Cordis.GlobalLandingTransposition.YieldSyntaxGap.no_right_lifecycle_yield_stable
#print axioms
  Cordis.GlobalLandingTransposition.YieldSyntaxGap.not_forward_lifecycle_independent
#print axioms Cordis.GlobalLandingTransposition.Example.diamond
#print axioms Cordis.GlobalLandingTransposition.Example.executableRulePair_eq
#print axioms
  Cordis.GlobalLandingTransposition.ProviderFinishGap.before_consumer_target_none
#print axioms Cordis.GlobalLandingTransposition.ProviderFinishGap.after_consumer_target
#print axioms
  Cordis.GlobalLandingTransposition.ProviderFinishGap.consumer_begin_not_available_at_predecessor
#print axioms
  Cordis.GlobalLandingTransposition.OracleProvenanceGap.selected_children_differ
#print axioms
  Cordis.GlobalLandingTransposition.OracleProvenanceGap.landingTwo_not_aligned_with_programOne
#print axioms
  Cordis.GlobalLandingTransposition.OracleProvenanceGap.landingOne_not_aligned_with_programTwo
#print axioms Cordis.GlobalActivationTransposition.ProgramActivation.transition_rule
#print axioms Cordis.GlobalActivationTransposition.ProgramActivation.source_present
#print axioms Cordis.GlobalActivationTransposition.ProgramActivation.source_not_active
#print axioms Cordis.GlobalActivationTransposition.ProgramActivation.preservesWellFormed
#print axioms Cordis.GlobalActivationTransposition.ProgramActivation.foreignLookupFrame
#print axioms Cordis.GlobalActivationTransposition.ForeignLookupFrame.activeProvider_forward
#print axioms Cordis.GlobalActivationTransposition.ForeignLookupFrame.targetView_some_forward
#print axioms Cordis.GlobalActivationTransposition.ProgramActivation.foreign_target
#print axioms Cordis.GlobalActivationTransposition.ProgramActivation.after_unique
#print axioms Cordis.GlobalActivationTransposition.ProgramActivation.rule_unique
#print axioms Cordis.GlobalActivationTransposition.program_activation_diamond
#print axioms Cordis.GlobalActivationTransposition.transpose_program_activations
#print axioms
  Cordis.GlobalActivationTransposition.ProgramActivationTransposition.swappedTransition
#print axioms Cordis.GlobalActivationTransposition.Example.LandingPair.transposition
#print axioms Cordis.GlobalActivationTransposition.Example.LandingPair.swappedTransition
#print axioms Cordis.GlobalActivationTransposition.Example.BeginPairs.beginBeginDiamond
#print axioms Cordis.GlobalActivationTransposition.Example.BeginPairs.beginFinishDiamond
#print axioms Cordis.GlobalActivationTransposition.Example.FinishPair.independent
#print axioms Cordis.GlobalActivationTransposition.Example.FinishPair.exact
#print axioms Cordis.GlobalActivationTransposition.Example.FinishPair.compatible
#print axioms Cordis.GlobalActivationTransposition.Example.FinishPair.diamond
#print axioms Cordis.GlobalActivationTransposition.RootProvenanceGap.root_not_catalog_entry
#print axioms
  Cordis.GlobalActivationTransposition.SameOwnerGap.same_owner_phase_updates_do_not_commute
#print axioms
  Cordis.GlobalActivationTransposition.common_source_applicability_is_necessary
#print axioms Cordis.GlobalActivationTransposition.bare_landing_does_not_determine_program
#print axioms
  Cordis.GlobalActivationTransposition.semantic_independence_does_not_supply_exact_swap_laws
namespace Cordis.GlobalActivationOrchestrationTransposition
#print axioms sourceRegisteredChild_ordinary
#print axioms sourceRegisteredChild_registration
#print axioms ProgramActivation.registeredChild_begin
#print axioms ProgramActivation.registeredChild_landing
#print axioms sourceRegisteredChild_ne_none_of_registration
#print axioms orchestrationReplay_before
#print axioms ProgramActivation.lookup_after_eq_of_nonregistering
#print axioms ProgramActivation.lookup_before_of_after_of_not_registered
#print axioms ProgramActivation.owner_after_static
#print axioms ProgramActivation.endpoint_component_present
#print axioms reconstructOrchestration
#print axioms orchestration_preserves_positive_target
#print axioms retireFiber_setPhase_commute
#print axioms removeFiber_setPhase_commute
#print axioms orchestrationReplay_setPhase_commute
#print axioms Landing.reframeFromEditTemplate
#print axioms reframeActivationAcrossEdit
#print axioms transpose_activation_orchestration
#print axioms LiteralPaperGap.parent_adoption_blocks_early_insert
#print axioms LiteralPaperGap.registration_insert_birth_order_differs
#print axioms LiteralPaperGap.birth_order_not_ruleRelated
#print axioms InsertClockGap.no_insert_execution_frame
#print axioms InsertClockGap.wellformed_nonregistration_do_not_supply_frame
#print axioms RetireOracleGap.no_retire_execution_frame
#print axioms RetireOracleGap.registration_safety_does_not_supply_frame
#print axioms RetireOracleGap.raw_registration_request_is_unchanged
#print axioms BeginInsert.transposition
#print axioms BeginInsert.exposedTags_eq_executableTags
#print axioms BeginRetire.transposition
#print axioms OrdinaryFinishInsert.occurrenceFrame
#print axioms OrdinaryFinishInsert.transposition
#print axioms RegisteringFinishRetire.occurrenceFrame
#print axioms RegisteringFinishRetire.transposition
#print axioms RegisteringFinishRetire.original_safe_child
end Cordis.GlobalActivationOrchestrationTransposition
namespace Cordis.GlobalProgress
#print axioms RegistrationRejectionGap.fixed_program_rejection_gap
#print axioms RegistrationRejectionGap.raw_relation_can_change_oracle
#print axioms RegistrationRejectionGap.changed_execution_not_ready
#print axioms RegistrationRejectionGap.aborting_inertia_restores_a_rule
#print axioms FreshnessExhaustionGap.no_admission
#print axioms FreshnessExhaustionGap.no_lifecycle_transition
#print axioms FreshnessExhaustionGap.raw_progress_fails
#print axioms FreshnessExhaustionGap.no_freshSupply_bool
#print axioms FinitePrecedenceRank.wellFounded
#print axioms FinitePrecedenceRank.transGen_rank_lt
#print axioms FinitePrecedenceRank.no_transGen_self
#print axioms OracleTotal.toLandingOrRaiseTotal
#print axioms RecoveryTotal.readyAt
#print axioms unloading_provider_changes_committed_target
#print axioms relied_precedes
#print axioms ReloadingReadyAt.ofTotal
#print axioms FinitePrecedenceRank.exists_rank_maximal
#print axioms FinitePrecedenceRank.successor_not_maximal
#print axioms lifecycle_progress
#print axioms BeginExample.precedence_wellFounded
#print axioms BeginExample.precedence_acyclic
#print axioms BeginExample.true_rank_maximal
#print axioms BeginExample.no_precedence_successor
#print axioms BeginExample.progress
#print axioms BeginExample.executableRule_eq
#print axioms BeginExample.explicitTransition_witnesses_progress
#print axioms OracleExample.oracleTotal
#print axioms OracleExample.total
#print axioms OracleExample.origin_ready
#print axioms OracleExample.concrete_landing
end Cordis.GlobalProgress
namespace Cordis.GlobalSupport
#print axioms MixedCycle.final_wellFormed
#print axioms MixedCycle.precedence_wellFounded
#print axioms MixedCycle.support_cycle
#print axioms MixedCycle.supportEdge_not_wellFounded
#print axioms MixedCycle.empty_support_solution
#print axioms MixedCycle.present_support_solution
#print axioms MixedCycle.presentNames_eq_full
#print axioms MixedCycle.no_unique_support
#print axioms MixedCycle.cycleProjection_eq
#print axioms MixedCycle.cycleProjection_sound
#print axioms supported_iff
#print axioms supported_solution
#print axioms support_solution_unique
#print axioms hasUniqueSupport
#print axioms active_table_present_iff_provision
#print axioms inactive_outcome_eq_none
#print axioms activeNames_solution
#print axioms support_eq_active
#print axioms MixedCycle.activeState_wellFormed
#print axioms MixedCycle.activeState_quiescent
#print axioms MixedCycle.activeState_noFailed
#print axioms MixedCycle.activeState_total
#print axioms MixedCycle.active_parent_closed
#print axioms MixedCycle.activeState_no_unique_support
#print axioms MixedCycle.printed_hypotheses_hold
#print axioms ActiveParentGap.order
#print axioms ActiveParentGap.not_parent_closed
#print axioms ActiveParentGap.support_ne_active
#print axioms ActiveParentGap.activeNames_not_solution
#print axioms PositiveRoot.order
#print axioms PositiveRoot.support_eq_active_positive
end Cordis.GlobalSupport
namespace Cordis.GlobalTraceRewrite
#print axioms StepPair.trace_rules
#print axioms StepPair.trace_actors
#print axioms Trace.rules_append
#print axioms Trace.actors_append
#print axioms Trace.records_append
#print axioms AdjacentOccurrence.first_mem_records
#print axioms AdjacentOccurrence.second_mem_records
#print axioms AdjacentOccurrence.original_rules
#print axioms AdjacentOccurrence.rewrite_rules
#print axioms AdjacentOccurrence.original_actors
#print axioms AdjacentOccurrence.rewrite_actors
#print axioms AdjacentOccurrence.rules_perm
#print axioms AdjacentOccurrence.actors_perm
#print axioms AdjacentOccurrence.rewrite_aligned
#print axioms AdjacentOccurrence.rewrite_states_length
#print axioms AdjacentOccurrence.rewrite_preservesWellFormed
#print axioms ProgramOccurrence.rule_eq
#print axioms ProgramOccurrence.actor_eq
#print axioms TraceProgramAssignment.headOccurrence
#print axioms TraceProgramAssignment.tail
#print axioms TraceProgramAssignment.append
#print axioms AssignedAdjacentOccurrence.sourceAssignment
#print axioms AssignedAdjacentOccurrence.rewrittenAssignment
#print axioms reframeActivation_rule_eq
#print axioms program_activation_diamond_right_rule_eq
#print axioms transpose_program_activations_left_rule_eq
#print axioms transpose_program_activations_right_rule_eq
#print axioms swappedTransition_globalStep_eq
#print axioms sameOrchestrationTemplate_global_tags
#print axioms transpose_activation_orchestration_rule_eq
#print axioms transposeActivationPair
#print axioms transposeActivationOrchestrationPair
#print axioms transposeActivationOccurrence
#print axioms rewriteActivationOccurrence
#print axioms transposeActivationOrchestrationOccurrence
#print axioms rewriteActivationOrchestrationOccurrence
#print axioms Example.ActivationPair.extractedLeftOccurrence_eq
#print axioms Example.ActivationPair.extractedRightOccurrence_eq
#print axioms Example.ActivationPair.assignedSwap
#print axioms Example.ActivationOrchestration.rewritten_rules
#print axioms Example.ActivationOrchestration.rewritten_actors
#print axioms Example.ActivationOrchestration.rewritten_projection
#print axioms registering_insert_parent_gap
#print axioms registering_insert_birth_gap
#print axioms bare_landing_has_no_unique_program
end Cordis.GlobalTraceRewrite
namespace Cordis.GlobalDeletion
#print axioms descendantClosed_iff_noSurvivingParentRefs
#print axioms ParentGap.source_wellFormed
#print axioms ParentGap.registered_wellFormed
#print axioms ParentGap.adoptionAfter_wellFormed
#print axioms ParentGap.removing_child_does_not_restore_clock
#print axioms ParentGap.no_surviving_same_template_insert
#print axioms ParentGap.final_parent_closure_fails
#print axioms ParentGap.removed_final_not_wellFormed
#print axioms AssignedLocatedEpisode.masterAssignment
#print axioms DeletionReplay.decisions_length
#print axioms DeletionReplay.transportAssignment
#print axioms DeletionReplay.final_related
#print axioms DeletionReplay.rules_sublist
#print axioms DeletionReplay.actors_sublist
#print axioms DeletionReplay.shadow_aligned
#print axioms DeletionReplay.records_length_le
#print axioms DeletionReplay.rules_length_le
#print axioms DeletionReplay.actors_length_le
#print axioms forwardOrchestration_sameTemplate
#print axioms forwardOrchestration_avoidsParent
#print axioms Vestigial.remove_other
#print axioms safeForVestigialNames_iff_pointwise
#print axioms forwardNamesStep
#print axioms SameOrchestrationTraceTemplate.shadowAssignment
#print axioms forwardNamesOrchestrationTrace
#print axioms RedrawGap.redraw_trace_not_noRedraw
#print axioms Positive.names_endpoint_exact
#print axioms Positive.names_rules_exact
#print axioms Positive.names_actors_exact
#print axioms Positive.names_family_preserved
#print axioms Positive.namesMatchedAssignment
#print axioms Positive.deletionReplay
#print axioms Positive.deletion_result_shadow_eq
#print axioms Positive.filtered_rule_sublist
#print axioms Positive.filtered_actor_sublist
#print axioms Positive.deletion_final_related
#print axioms Positive.deletion_shadow_aligned
#print axioms Positive.deletion_decisions
#print axioms Positive.deletion_decisions_length
#print axioms Positive.deletionShadowAssignment
#print axioms vestigialOrAbsent_of_vestigial
#print axioms vestigialOrAbsent_after_remove
#print axioms registration_insert_birth_order_gap
#print axioms registration_insert_rule_relation_gap
end Cordis.GlobalDeletion
namespace Cordis.GlobalPaperRelation
#print axioms paperControlAt_eq_map_controlAt
#print axioms birthErasedRuleRelated_refl
#print axioms birthErasedRuleRelated_symm
#print axioms birthErasedRuleRelated_trans
#print axioms birthErasedRuleRelatedOutside_refl
#print axioms birthErasedRuleRelatedOutside_symm
#print axioms birthErasedRuleRelatedOutside_trans
#print axioms deletionRelated_refl
#print axioms deletionRelated_symm
#print axioms deletionRelated_trans
#print axioms birthErased_registry_domain
#print axioms outside_registry_none_iff
#print axioms birthErased_of_outsideEmpty
#print axioms birthErased_of_ruleRelated
#print axioms outside_mono
#print axioms deletion_mono
#print axioms paperFiberControl_installed_iff
#print axioms paperFiberControl_active_iff
#print axioms matchPaperFiber
#print axioms paperControlAt_insert_related
#print axioms paperControlAt_retire_related
#print axioms paperControlAt_remove_related
#print axioms contextRelated_after_orchestration
#print axioms matchOrchestrationForward
#print axioms matchOrchestrationBackward
#print axioms ForwardPaperOrchestrationMatch.toRetainedStep
#print axioms BackwardPaperOrchestrationMatch.toRetainedStep
#print axioms birthErasedOrchestrationSimulation
#print axioms LifecycleGap.sources_birth_erased
#print axioms LifecycleGap.inertia_not_respected
#print axioms ClockLifecycleGap.shifted_wellFormed
#print axioms ClockLifecycleGap.sources_related
#print axioms ClockLifecycleGap.no_shifted_divertAbort
#print axioms ClockLifecycleGap.no_assigned_simulation
#print axioms BirthGap.birth_erased_related
#print axioms BirthGap.strict_rule_relation_fails
#print axioms BirthGap.exact_states_differ
#print axioms BirthGap.matched_retire_successors
#print axioms BirthGap.matchedRetire_tags
#print axioms BirthGap.forwardMatchedAssignment
#print axioms BirthGap.backwardMatchedAssignment
#print axioms OneSidedWellFormedGap.related
#print axioms OneSidedWellFormedGap.malformed_not_wellFormed
#print axioms VestigialGap.deletion_related
#print axioms VestigialGap.global_rule_relation_fails
#print axioms OutsideGap.unsafe_parent_step_rejected
#print axioms OutsideGap.no_backward_same_tag_redraw
#print axioms OutsideGap.provision_conflict_is_real
#print axioms OutsideGap.parent_removal_conflict_is_real
#print axioms vestigial_remove_deletion_related
#print axioms vestigial_remove_wellFormed
#print axioms vestigial_remove_not_birthErased
#print axioms removeNames_wellFormed
#print axioms vestigialNames_deletionRelated
#print axioms replaySafeVestigialOrchestration
#print axioms replaySafeVestigialTrace
#print axioms ForwardDeletedTraceReplay.final_related
#print axioms ForwardDeletedTraceReplay.transportAssignment
#print axioms DirectedReplayExample.final_related
#print axioms DirectedReplayExample.replay_shadow_rules
#print axioms DirectedReplayExample.shadowAssignment
end Cordis.GlobalPaperRelation
namespace Cordis.GlobalPaperTraceSimulation
#print axioms detailedRule_global
#print axioms detailedRules_append
#print axioms replay_rules_eq
#print axioms replay_actors_eq
#print axioms ForwardAssignedStepMatch.toRetainedStep
#print axioms BackwardAssignedStepMatch.toRetainedStep
#print axioms ForwardAssignedStepSimulation.ofLifecycle
#print axioms AssignedStepSimulation.ofLifecycle
#print axioms ForwardAssignedStepSimulation.replayTrace
#print axioms ForwardPaperTraceReplay.final_related
#print axioms ForwardPaperTraceReplay.transportAssignment
#print axioms ForwardPaperTraceReplay.rules_eq
#print axioms ForwardPaperTraceReplay.actors_eq
#print axioms RelatedAssignedAdjacentSwap.ofExact
#print axioms RelatedAdjacentRewrite.final_related
#print axioms RelatedAdjacentRewrite.final_wellFormed
#print axioms RelatedAdjacentRewrite.assignment
#print axioms RelatedAdjacentRewrite.detailedRules_perm
#print axioms RelatedAdjacentRewrite.rules_perm
#print axioms RelatedAdjacentRewrite.actors_perm
#print axioms ForwardAssignedStepSimulation.rewriteAdjacent
#print axioms ClockGap.no_forward_step_simulation
#print axioms PositiveOrchestration.final_related
#print axioms PositiveOrchestration.rules_eq
#print axioms PositiveOrchestration.actors_eq
#print axioms PositiveOrchestration.executableDetailedRules_eq_source
#print axioms PositiveOrchestration.executableActorNames_eq_source
end Cordis.GlobalPaperTraceSimulation
namespace Cordis.GlobalPaperTraceDeletion
#print axioms detailedRule_eq_of_orchestration
#print axioms replay_detailedRules_eq
#print axioms replay_decisions_allKeep
#print axioms replaySafeVestigialTraceAssigned
#print axioms AssignedDeletedTraceReplay.final_related
#print axioms AssignedDeletedTraceReplay.rules_eq
#print axioms AssignedDeletedTraceReplay.actors_eq
#print axioms Example.executableDetailedRules_eq
#print axioms Example.executableActorNames_eq
end Cordis.GlobalPaperTraceDeletion
namespace Cordis.GlobalPaperTraceNormalization
#print axioms AnyRewriteWitness.target
#print axioms RewriteChain.single
#print axioms RewriteChain.single_terminal
#print axioms RewriteChain.terminal
#print axioms chain_final_related
#print axioms chain_rules_perm
#print axioms chain_actors_perm
#print axioms Example.empty_chain_related
#print axioms Example.empty_chain_rules
#print axioms Example.empty_chain_actors
end Cordis.GlobalPaperTraceNormalization
#print axioms Cordis.GlobalRelations.contextRelated_domain
#print axioms Cordis.GlobalRelations.ruleSetoid
#print axioms Cordis.GlobalRelations.ruleRelated_registry_domain
#print axioms Cordis.GlobalRelations.effectSetoid
#print axioms Cordis.GlobalRelations.tableAt_retireByName
#print axioms Cordis.GlobalRelations.temporalEffectEquiv
#print axioms Cordis.GlobalRelations.Example.rule_related_table_difference
#print axioms Cordis.GlobalRelations.Example.effect_rejects_table_difference
#print axioms Cordis.GlobalRelations.Example.effect_related_vestigial_absence
#print axioms Cordis.GlobalRelations.Example.rule_rejects_vestigial_absence
#print axioms Cordis.GlobalRelations.Example.dynamics_relation_not_effect_candidate
#print axioms Cordis.GlobalRelations.Example.counterexampleUndoRespect
#print axioms Cordis.GlobalSpatial.begin_dependencies_provided
#print axioms Cordis.GlobalSpatial.LocatedEpisode.records_eq
#print axioms Cordis.GlobalSpatial.LocatedEpisode.open_before_close
#print axioms Cordis.GlobalSpatial.NestedEpisodes.provider_opens_before_consumer
#print axioms Cordis.GlobalSpatial.NestedEpisodes.consumer_closes_before_provider
#print axioms Cordis.GlobalSpatial.InstalledResolution.relied
#print axioms Cordis.GlobalSpatial.relied_provider_installed
#print axioms Cordis.GlobalSpatial.unload_blocked_by_installed_consumer
#print axioms Cordis.GlobalSpatial.Trace.installedResolution_throughout
#print axioms Cordis.GlobalSpatial.Trace.noUnloadFor_of_installedResolution
#print axioms Cordis.GlobalSpatial.BoundedEpisode.provider_noUnload_core
#print axioms Cordis.GlobalSpatial.BoundedEpisode.provider_installed_at_closeBefore
#print axioms Cordis.GlobalSpatial.traceTableConfinement_of_foreign
#print axioms Cordis.GlobalSpatial.tableValue_throughout
#print axioms Cordis.GlobalSpatial.reloading_target_dichotomy
#print axioms Cordis.GlobalVestigial.Vestigial.effectRelated_remove
#print axioms Cordis.GlobalVestigial.remove_insert_commute
#print axioms Cordis.GlobalVestigial.remove_retire_commute
#print axioms Cordis.GlobalVestigial.remove_remove_commute
#print axioms Cordis.GlobalVestigial.Vestigial.forward_orchestration
#print axioms Cordis.GlobalVestigial.Vestigial.backward_orchestration
#print axioms Cordis.GlobalVestigial.Counterexample.state_wellFormed
#print axioms Cordis.GlobalVestigial.Counterexample.withoutVestigial_wellFormed
#print axioms Cordis.GlobalVestigial.Counterexample.effectRelated_withoutVestigial
#print axioms Cordis.GlobalVestigial.Counterexample.adoptingInsert_uses_vestigial_parent
#print axioms Cordis.GlobalVestigial.Counterexample.no_parent_witness_after_removal
#print axioms Cordis.GlobalVestigial.Counterexample.redrawVestigial_draws_name
#print axioms Cordis.GlobalVestigial.Counterexample.claimingInsert_claims_vestigial_provision
#print axioms Cordis.GlobalVestigial.Counterexample.removesVestigialParent
#print axioms Cordis.GlobalVestigial.Counterexample.parent_not_childless_before
#print axioms Cordis.GlobalRuleInvariance.matchFiber
#print axioms Cordis.GlobalRuleInvariance.activeValue_insert_iff
#print axioms Cordis.GlobalRuleInvariance.activeValue_retire_iff
#print axioms Cordis.GlobalRuleInvariance.activeValue_remove_iff
#print axioms Cordis.GlobalRuleInvariance.activeContext_eq_of_activeValue_iff
#print axioms Cordis.GlobalRuleInvariance.orchestration_activeContext_eq
#print axioms Cordis.GlobalRuleInvariance.contextRelated_after_orchestration
#print axioms Cordis.GlobalRuleInvariance.matchOrchestrationForward
#print axioms Cordis.GlobalRuleInvariance.matchOrchestrationBackward
#print axioms Cordis.GlobalRuleInvariance.orchestrationRuleBisimulation
#print axioms Cordis.GlobalRuleInvariance.HeterogeneousExample.source_values_are_related
#print axioms Cordis.GlobalRuleInvariance.HeterogeneousExample.states_ruleRelated
#print axioms Cordis.GlobalRuleInvariance.HeterogeneousExample.insertionMatch_successors
#print axioms Cordis.GlobalRuleInvariance.InertiaGap.baseline_ruleRelated_shifted
#print axioms Cordis.GlobalRuleInvariance.InertiaGap.ambientSensitiveInertia_not_respecting
#print axioms Cordis.GlobalRuleObservations.matchedFiber
#print axioms Cordis.GlobalRuleObservations.activeProvider_iff
#print axioms Cordis.GlobalRuleObservations.activeFiberTables_related
#print axioms Cordis.GlobalRuleObservations.isTargetView_iff
#print axioms Cordis.GlobalRuleObservations.targetView_some_iff
#print axioms Cordis.GlobalRuleObservations.targetView_none_iff
#print axioms Cordis.GlobalRuleObservations.targetView_changed_iff
#print axioms Cordis.GlobalRuleObservations.resolvesTo_iff
#print axioms Cordis.GlobalRuleObservations.relied_iff
#print axioms Cordis.GlobalRuleObservations.notRelied_iff
#print axioms Cordis.GlobalRuleObservations.quiescent_iff
#print axioms Cordis.GlobalRuleObservations.beginGuard_nonempty_iff
#print axioms Cordis.GlobalRuleObservations.reloadingTargetGuard_nonempty_iff
#print axioms Cordis.GlobalRuleObservations.leaveGuard_nonempty_iff
#print axioms Cordis.GlobalRuleObservations.divertGuard_nonempty_iff
#print axioms Cordis.GlobalRuleObservations.unloadGuard_nonempty_iff
#print axioms Cordis.GlobalRuleObservations.HeterogeneousExample.provider_counter_iff
#print axioms Cordis.GlobalRuleObservations.HeterogeneousExample.active_tables_related
#print axioms Cordis.GlobalRuleObservations.HeterogeneousExample.right_target
#print axioms Cordis.GlobalRuleObservations.HeterogeneousExample.right_quiescent
#print axioms Cordis.GlobalRuleObservations.HeterogeneousExample.ruleRelated_without_effectRelated
#print axioms Cordis.GlobalRuleObservations.EffectObservationGap.effectRelated_without_ruleRelated
#print axioms Cordis.GlobalRuleObservations.AmbientGap.ruleRelated_without_effectRelated
#print axioms Cordis.GlobalLifecycleBisimulation.ruleRelated_setPhase
#print axioms Cordis.GlobalLifecycleBisimulation.ruleRelated_setPhase_nonactive
#print axioms Cordis.GlobalLifecycleBisimulation.ruleRelated_setPhase_activate
#print axioms Cordis.GlobalLifecycleBisimulation.ruleRelated_setPhase_deactivate
#print axioms Cordis.GlobalLifecycleBisimulation.matchBeginForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchIterForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchFinishForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchDivertAbortForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchDivertLandForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchRaiseForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchLeaveForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchUnloadForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchLifecycleBackward
#print axioms Cordis.GlobalLifecycleBisimulation.lifecycleRuleBisimulation
#print axioms Cordis.GlobalLifecycleBisimulation.matchStepForward
#print axioms Cordis.GlobalLifecycleBisimulation.matchStepBackward
#print axioms Cordis.GlobalLifecycleBisimulation.wellFormedRuleBisimulation
#print axioms Cordis.GlobalLifecycleBisimulation.ReflexiveExample.existing_path_rules
#print axioms Cordis.GlobalLifecycleBisimulation.FinishSeam.sources_ruleRelated
#print axioms Cordis.GlobalLifecycleBisimulation.FinishSeam.source_tables_not_related
#print axioms Cordis.GlobalLifecycleBisimulation.FinishSeam.activated_not_ruleRelated
#print axioms Cordis.GlobalNameAction.Equiv.injective
#print axioms Cordis.GlobalNameAction.mapValues_comp
#print axioms Cordis.GlobalNameAction.reindexConst_trans
#print axioms Cordis.GlobalNameAction.actTable_trans
#print axioms Cordis.GlobalNameAction.actCommittedView_trans
#print axioms Cordis.GlobalNameAction.actUndoCode_trans
#print axioms Cordis.GlobalNameAction.actPhase_trans
#print axioms Cordis.GlobalNameAction.actFiber_trans
#print axioms Cordis.GlobalNameAction.actRegistry_trans
#print axioms Cordis.GlobalNameAction.actState_trans
#print axioms Cordis.GlobalNameAction.actState_symm_apply
#print axioms Cordis.GlobalNameAction.wellFormed_act
#print axioms Cordis.GlobalNameAction.wellFormed_act_iff
#print axioms Cordis.GlobalNameAction.actState_insertFiber
#print axioms Cordis.GlobalNameAction.actState_retireFiber
#print axioms Cordis.GlobalNameAction.actState_removeFiber
#print axioms Cordis.GlobalNameAction.actOrchestrationStep
#print axioms Cordis.GlobalNameAction.unactOrchestrationStep
#print axioms Cordis.GlobalNameAction.orchestrationEquivariance
#print axioms Cordis.GlobalNameAction.Example.acted_wellFormed
#print axioms Cordis.GlobalNameAction.Example.state_inverse
#print axioms Cordis.GlobalNameAction.Example.acted_retire_name
#print axioms Cordis.GlobalNameAction.ConstantNameGap.bad_actName_not_injective
#print axioms Cordis.GlobalNameLifecycle.actRegistrationRequest_trans
#print axioms Cordis.GlobalNameLifecycle.actRunOutput_trans
#print axioms Cordis.GlobalNameLifecycle.retireByName_equivariant
#print axioms Cordis.GlobalNameLifecycle.applyUndo_equivariant
#print axioms Cordis.GlobalNameLifecycle.recover_equivariant
#print axioms Cordis.GlobalNameLifecycle.actState_setPhase
#print axioms Cordis.GlobalNameLifecycle.actRegistrationAdmission
#print axioms Cordis.GlobalNameLifecycle.actIterationStep
#print axioms Cordis.GlobalNameLifecycle.actRegistrationOracle_certify_ok
#print axioms Cordis.GlobalNameLifecycle.executeOne_equivariant
#print axioms Cordis.GlobalNameLifecycle.actLanding
#print axioms Cordis.GlobalNameLifecycle.actRecoveryAdmission
#print axioms Cordis.GlobalNameLifecycle.activeProvider_iff
#print axioms Cordis.GlobalNameLifecycle.relied_iff
#print axioms Cordis.GlobalNameLifecycle.targetView_equivariant
#print axioms Cordis.GlobalNameLifecycle.actLifecycleTransition
#print axioms Cordis.GlobalNameLifecycle.unactLifecycleTransition
#print axioms Cordis.GlobalNameLifecycle.lifecycleNameEquivariance
#print axioms Cordis.GlobalNameLifecycle.actUnifiedStep
#print axioms Cordis.GlobalNameLifecycle.unactUnifiedStep
#print axioms Cordis.GlobalNameLifecycle.unifiedNameEquivariance
#print axioms Cordis.GlobalNameLifecycle.ReflexiveExample.existing_path_rules
#print axioms Cordis.GlobalNameLifecycle.ReflexiveExample.unloading_path_rules
#print axioms Cordis.GlobalNameLifecycle.ReflexiveExample.backward_begin_rule
#print axioms Cordis.GlobalNameLifecycle.ReflexiveExample.unified_begin_rule
#print axioms Cordis.GlobalNameLifecycle.NonidentityRaiseExample.acted_raise_endpoint
#print axioms Cordis.GlobalNameLifecycle.NonidentityRaiseExample.entryBreakingAction_not_invariant
#print axioms Cordis.GlobalNameLifecycle.NonidentityRaiseExample.successOnlyMap_loses_error_action
#print axioms Cordis.GlobalNameLifecycle.NonidentityRaiseExample.constantErrorBadRun_not_equivariant
#print axioms Cordis.DeepSeekStreamHarnessErrors.executeConversationMultiStreamRoundRecoverable
#print axioms Cordis.DeepSeekStreamHarnessErrors.runConversationMultiStreamRecoverable
#print axioms Cordis.DeepSeekStreamHarnessRetry.executeWithRetry
#print axioms Cordis.DeepSeekStreamHarnessRetry.executeConversationMultiStreamRound
#print axioms Cordis.DeepSeekStreamHarness.streamFlagFixtureProcess
