import Cordis.GlobalNameLifecycle
import Cordis.PartialTransformation
import Cordis.ObservationalPartialTransformation

/-!
# Finite iterator-family independence

This module gives a finite executable partial/Kleisli analogue of CORDIS Definition 60 at paper
revision `948a07b369c62adb3b12e102458be5c18dfb69b9`. A `Program` fixes an owner, root iterator
code, dynamics interpreter, and registration oracle. Fixing the oracle is essential in the current
API: a raw registration request does not choose the child whose name determines both the
retirement inverse and the continuation.

`Reach` is the least continuation-closed predicate generated by successful `executeOne` calls.
The program monoid is the existing least Kleisli closure of the partial forward map of every
reachable code and the totalized `Dynamics.applyUndo` map of every inverse actually yielded by
such a call. `Independent` requires cross-closure commutation and stability of the complete yield:
inverse map, continuation, and ordinary-versus-registration source kind, including the registered
component.

The exact layer is related to `GlobalTemporal` by proving that a generated accumulated recovery
commutes with any totalized foreign step whose partial map belongs to an independent closure. An
observational layer uses `GlobalTemporal.EffectEquiv`; `GlobalRelations.RuleRelated` is not used
as effect equality because it deliberately forgets ambient and private-table state. Rule
applicability remains the separate Lemma 55 concern.

This is not the paper's unrestricted total, component-only Definition 60. Forward maps may be
undefined, yield stability is conditional on successful foreign execution, continuation codes are
compared by exact equality, and the oracle is part of the program. `FiniteReachability` and
`BoundedContinuation` are explicit certificates; the generic signature does not make iterator
codes or global states finite. Full Theorem 61 still additionally needs the reordering and local
inverse-stability premises already exposed by `GlobalTemporal`.
-/

set_option autoImplicit false

namespace Cordis.GlobalIteratorIndependence

open Cordis.GlobalRegistry Cordis.GlobalDynamics Cordis.GlobalCalculus
open Cordis.GlobalTemporal

universe u

variable {sig : StaticSignature} {catalog : Catalog sig} {Ambient : Type u}

abbrev State (catalog : Catalog sig) (Ambient : Type u) := GlobalState catalog Ambient

abbrev PartialMap (catalog : Catalog sig) (Ambient : Type u) :=
  Cordis.PartialTransformation.PartialMap (State catalog Ambient)

/-! ## Oracle-specific programs and least continuation reach -/

/-- One concrete iterator family. The oracle resolves registration-dependent continuations. -/
structure Program (dynamics : Dynamics sig catalog Ambient) where
  owner : sig.Name
  RegistrationError : Type u
  oracle : RegistrationOracle dynamics owner RegistrationError
  root : sig.IteratorCode

/-- Embed one total state function in the global partial-map language. -/
def total (map : State catalog Ambient → State catalog Ambient) :
    PartialMap catalog Ambient := fun state ↦ some (map state)

/-- The least set containing the root and every continuation actually yielded by a successful
execution of a reachable code at an arbitrary state. -/
inductive Reach
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics) :
    sig.IteratorCode → Prop where
  | root : Reach program program.root
  | next {code : sig.IteratorCode} {state : State catalog Ambient}
      {step : IterationStep dynamics program.owner code state}
      {next : sig.IteratorCode} :
      Reach program code →
      executeOne dynamics program.oracle code state = .ok step →
      step.next = some next → Reach program next

/-- Executable partial forward map of one code under the fixed owner and oracle. -/
def forward
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics)
    (code : sig.IteratorCode) : PartialMap catalog Ambient := fun state ↦
  match executeOne dynamics program.oracle code state with
  | .error _ => none
  | .ok step => some step.after

/-- The branch information that Definition 60 retains for registering iterations. -/
inductive YieldKind (sig : StaticSignature) where
  | ordinary
  | registration (component : sig.ComponentId)
  deriving DecidableEq

def sourceKindOf
    {dynamics : Dynamics sig catalog Ambient} {owner : sig.Name}
    {code : sig.IteratorCode} {before after : State catalog Ambient}
    {undo : UndoCode sig} {next : Option sig.IteratorCode}
    (source : StepSource dynamics owner code before after undo next) : YieldKind sig :=
  match source with
  | .ordinary .. => .ordinary
  | .registration request .. => .registration request.component

def sourceKind
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {code : sig.IteratorCode} {state : State catalog Ambient}
    (step : IterationStep dynamics program.owner code state) : YieldKind sig :=
  sourceKindOf step.source

/-- Exact agreement of the state-dependent part of an iteration's yield. -/
structure YieldAgrees
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {code : sig.IteratorCode} {leftState rightState : State catalog Ambient}
    (left : IterationStep dynamics program.owner code leftState)
    (right : IterationStep dynamics program.owner code rightState) : Prop where
  inverse : total (dynamics.applyUndo left.undo) =
    total (dynamics.applyUndo right.undo)
  continuation : left.next = right.next
  kind : sourceKind left = sourceKind right

namespace YieldAgrees

theorem refl
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {code : sig.IteratorCode} {state : State catalog Ambient}
    (step : IterationStep dynamics program.owner code state) : YieldAgrees step step :=
  ⟨rfl, rfl, rfl⟩

theorem trans
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {code : sig.IteratorCode} {firstState secondState thirdState : State catalog Ambient}
    {first : IterationStep dynamics program.owner code firstState}
    {second : IterationStep dynamics program.owner code secondState}
    {third : IterationStep dynamics program.owner code thirdState}
    (left : YieldAgrees first second) (right : YieldAgrees second third) :
    YieldAgrees first third :=
  ⟨left.inverse.trans right.inverse, left.continuation.trans right.continuation,
    left.kind.trans right.kind⟩

end YieldAgrees

/-! ## Definition 60 generators, closure, and exact independence -/

/-- Forward maps and every actual totalized yielded inverse in `Reach`. -/
inductive Generator
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics) :
    PartialMap catalog Ambient → Prop where
  | forward {code : sig.IteratorCode} : Reach program code →
      Generator program (GlobalIteratorIndependence.forward program code)
  | inverse {code : sig.IteratorCode} {state : State catalog Ambient}
      {step : IterationStep dynamics program.owner code state} :
      Reach program code →
      executeOne dynamics program.oracle code state = .ok step →
      Generator program (total (dynamics.applyUndo step.undo))

/-- The least identity/composition Kleisli closure generated by a program. -/
abbrev Closure
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics) :
    PartialMap catalog Ambient → Prop :=
  Cordis.PartialTransformation.Closure (Generator program)

/-- A successful foreign map preserves definedness and the inverse, continuation, and branch
kind yielded by every reachable code. -/
def YieldStable
    {dynamics : Dynamics sig catalog Ambient}
    (program : Program dynamics) (foreign : PartialMap catalog Ambient) : Prop :=
  ∀ {code : sig.IteratorCode}, Reach program code →
    ∀ seed step moved,
      executeOne dynamics program.oracle code seed = .ok step →
      foreign seed = some moved →
      ∃ movedStep,
        executeOne dynamics program.oracle code moved = .ok movedStep ∧
          YieldAgrees movedStep step

theorem yieldStable_identity
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics) :
    YieldStable program Cordis.PartialTransformation.identity := by
  intro code reachable seed step moved executed transformed
  have movedEq := Option.some.inj transformed
  subst moved
  exact ⟨step, executed, YieldAgrees.refl step⟩

theorem YieldStable.comp
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {outer inner : PartialMap catalog Ambient}
    (outerStable : YieldStable program outer)
    (innerStable : YieldStable program inner) :
    YieldStable program (Cordis.PartialTransformation.comp outer inner) := by
  intro code reachable seed step moved executed transformed
  unfold Cordis.PartialTransformation.comp at transformed
  cases innerRun : inner seed with
  | none => simp [innerRun] at transformed
  | some middle =>
      rw [innerRun] at transformed
      obtain ⟨middleStep, middleExecuted, middleAgrees⟩ :=
        innerStable reachable seed step middle executed innerRun
      obtain ⟨movedStep, movedExecuted, movedAgrees⟩ :=
        outerStable reachable middle middleStep moved middleExecuted transformed
      exact ⟨movedStep, movedExecuted, movedAgrees.trans middleAgrees⟩

theorem yieldStable_of_generators
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {Generated : PartialMap catalog Ambient → Prop}
    (stable : ∀ {map}, Generated map → YieldStable program map)
    {map : PartialMap catalog Ambient}
    (member : Cordis.PartialTransformation.Closure Generated map) :
    YieldStable program map := by
  induction member with
  | identity => exact yieldStable_identity program
  | generator generated => exact stable generated
  | comp _ _ outerHypothesis innerHypothesis =>
      exact outerHypothesis.comp innerHypothesis

/-- Exact partial/Kleisli Definition 60 independence. -/
structure Independent
    {dynamics : Dynamics sig catalog Ambient} (left right : Program dynamics) : Prop where
  transformations_commute : ∀ {leftMap rightMap : PartialMap catalog Ambient},
    Closure left leftMap → Closure right rightMap →
      Cordis.PartialTransformation.Commutes leftMap rightMap
  left_yield_stable : ∀ {map : PartialMap catalog Ambient},
    Closure right map → YieldStable left map
  right_yield_stable : ∀ {map : PartialMap catalog Ambient},
    Closure left map → YieldStable right map

namespace Independent

theorem of_generators
    {dynamics : Dynamics sig catalog Ambient} {left right : Program dynamics}
    (commutes : ∀ {leftMap rightMap : PartialMap catalog Ambient},
      Generator left leftMap → Generator right rightMap →
        Cordis.PartialTransformation.Commutes leftMap rightMap)
    (leftStable : ∀ {map}, Generator right map → YieldStable left map)
    (rightStable : ∀ {map}, Generator left map → YieldStable right map) :
    Independent left right where
  transformations_commute := Cordis.PartialTransformation.Closure.commute commutes
  left_yield_stable := yieldStable_of_generators leftStable
  right_yield_stable := yieldStable_of_generators rightStable

theorem symm
    {dynamics : Dynamics sig catalog Ambient} {left right : Program dynamics}
    (independent : Independent left right) : Independent right left where
  transformations_commute := fun leftMember rightMember ↦
    (independent.transformations_commute rightMember leftMember).symm
  left_yield_stable := independent.right_yield_stable
  right_yield_stable := independent.left_yield_stable

end Independent

/-! ## Explicit finite reach, bounded continuation, and occurrence-indexed families -/

/-- A finite exact enumeration of the inductive reach predicate. This is additional data because
`StaticSignature.IteratorCode` is not globally assumed finite or decidable. -/
structure FiniteReachability
    {dynamics : Dynamics sig catalog Ambient} [DecidableEq sig.IteratorCode]
    (program : Program dynamics) where
  codes : List sig.IteratorCode
  nodup : codes.Nodup
  exact : ∀ code, Reach program code ↔ code ∈ codes

/-- One realized continuation path. Its tail lists the successive continuation codes. -/
inductive ContinuationPath
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics) :
    sig.IteratorCode → List sig.IteratorCode → Prop where
  | nil {code : sig.IteratorCode} : Reach program code →
      ContinuationPath program code []
  | cons {code next : sig.IteratorCode} {state : State catalog Ambient}
      {step : IterationStep dynamics program.owner code state}
      {tail : List sig.IteratorCode} :
      Reach program code →
      executeOne dynamics program.oracle code state = .ok step →
      step.next = some next →
      ContinuationPath program next tail →
      ContinuationPath program code (next :: tail)

/-- An explicit finite upper bound for the paper's continuation-chain length. Cyclic programs do
not admit this certificate merely from finite reachability. -/
structure BoundedContinuation
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics) where
  bound : Nat
  bounded : ∀ {code tail}, ContinuationPath program code tail →
    tail.length + 1 ≤ bound

structure FiniteProgram
    {dynamics : Dynamics sig catalog Ambient} [DecidableEq sig.IteratorCode]
    (program : Program dynamics) where
  reachability : FiniteReachability program
  continuation : BoundedContinuation program

/-- Pairwise independence is indexed by occurrences, not by distinct program values. -/
def Pairwise
    {dynamics : Dynamics sig catalog Ambient} {count : Nat}
    (programs : Fin count → Program dynamics) : Prop :=
  ∀ left right, left ≠ right → Independent (programs left) (programs right)

/-- Two distinct occurrences carrying the same program force genuine self-independence. -/
theorem self_independent_of_duplicate
    {dynamics : Dynamics sig catalog Ambient} {count : Nat}
    {programs : Fin count → Program dynamics}
    (pairwise : Pairwise programs) {left right : Fin count}
    (different : left ≠ right) (same : programs left = programs right) :
    Independent (programs left) (programs left) := by
  have independent := pairwise left right different
  rw [← same] at independent
  exact independent

/-! ## Effect-equivalence-aware independence -/

/-- Relation-aware agreement of the yielded inverse, with exact continuation and source kind. -/
structure ObservationalYieldAgrees
    {dynamics : Dynamics sig catalog Ambient} (effect : EffectEquiv dynamics)
    {program : Program dynamics} {code : sig.IteratorCode}
    {leftState rightState : State catalog Ambient}
    (left : IterationStep dynamics program.owner code leftState)
    (right : IterationStep dynamics program.owner code rightState) : Prop where
  inverse : Cordis.ObservationalPartialTransformation.FunctionsRelated
    effect.setoid.r (dynamics.applyUndo left.undo) (dynamics.applyUndo right.undo)
  continuation : left.next = right.next
  kind : sourceKind left = sourceKind right

/-- The new external obligation needed for a partial forward map to descend to the chosen effect
quotient. Yielded inverse generators already respect it through `EffectEquiv.applyUndo_respects`.
-/
structure ProgramRespects
    {dynamics : Dynamics sig catalog Ambient} (effect : EffectEquiv dynamics)
    (program : Program dynamics) : Prop where
  forward : ∀ {code}, Reach program code →
    Cordis.ObservationalPartialTransformation.Respects effect.setoid.r
      (GlobalIteratorIndependence.forward program code)

theorem generator_respects
    {dynamics : Dynamics sig catalog Ambient} {effect : EffectEquiv dynamics}
    {program : Program dynamics} (respect : ProgramRespects effect program)
    {map : PartialMap catalog Ambient} (generated : Generator program map) :
    Cordis.ObservationalPartialTransformation.Respects effect.setoid.r map := by
  cases generated with
  | forward reachable => exact respect.forward reachable
  | inverse reachable executed =>
      intro left right related
      exact Coeffect.Observational.OptionRelated.some
        (effect.applyUndo_respects _ related)

theorem closure_respects
    {dynamics : Dynamics sig catalog Ambient} {effect : EffectEquiv dynamics}
    {program : Program dynamics} (respect : ProgramRespects effect program)
    {map : PartialMap catalog Ambient} (member : Closure program map) :
    Cordis.ObservationalPartialTransformation.Respects effect.setoid.r map := by
  induction member with
  | identity =>
      exact Cordis.ObservationalPartialTransformation.respects_identity
  | generator generated => exact generator_respects respect generated
  | comp _ _ outerHypothesis innerHypothesis =>
      exact outerHypothesis.comp innerHypothesis

def ObservationalYieldStable
    {dynamics : Dynamics sig catalog Ambient} (effect : EffectEquiv dynamics)
    (program : Program dynamics) (foreign : PartialMap catalog Ambient) : Prop :=
  ∀ {code : sig.IteratorCode}, Reach program code →
    ∀ seed step moved,
      executeOne dynamics program.oracle code seed = .ok step →
      foreign seed = some moved →
      ∃ movedStep,
        executeOne dynamics program.oracle code moved = .ok movedStep ∧
          ObservationalYieldAgrees effect movedStep step

/-- The Definition 60 commutation/stability shape read through the effect-state relation used by
the temporal-recovery API. This is an `EffectEquiv`/`≈` variant, not an identification of that
relation with the paper's displayed rule observation `≃`. -/
structure ObservationalIndependent
    {dynamics : Dynamics sig catalog Ambient} (effect : EffectEquiv dynamics)
    (left right : Program dynamics) : Prop where
  left_respects : ProgramRespects effect left
  right_respects : ProgramRespects effect right
  transformations_commute : ∀ {leftMap rightMap : PartialMap catalog Ambient},
    Closure left leftMap → Closure right rightMap →
      Cordis.ObservationalPartialTransformation.Commutes
        effect.setoid.r leftMap rightMap
  left_yield_stable : ∀ {map : PartialMap catalog Ambient},
    Closure right map → ObservationalYieldStable effect left map
  right_yield_stable : ∀ {map : PartialMap catalog Ambient},
    Closure left map → ObservationalYieldStable effect right map

private theorem function_eq_of_total_eq
    {left right : State catalog Ambient → State catalog Ambient}
    (equal : total left = total right) : left = right := by
  funext state
  exact Option.some.inj (congrFun equal state)

theorem observationalYieldAgrees_of_exact
    {dynamics : Dynamics sig catalog Ambient} (effect : EffectEquiv dynamics)
    {program : Program dynamics} {code : sig.IteratorCode}
    {leftState rightState : State catalog Ambient}
    {left : IterationStep dynamics program.owner code leftState}
    {right : IterationStep dynamics program.owner code rightState}
    (exact : YieldAgrees left right) : ObservationalYieldAgrees effect left right := by
  have inverseEq : dynamics.applyUndo left.undo = dynamics.applyUndo right.undo :=
    function_eq_of_total_eq exact.inverse
  refine ⟨?_, exact.continuation, exact.kind⟩
  intro leftState rightState related
  rw [inverseEq]
  exact effect.applyUndo_respects right.undo related

theorem observationalYieldStable_of_exact
    {dynamics : Dynamics sig catalog Ambient} (effect : EffectEquiv dynamics)
    {program : Program dynamics} {map : PartialMap catalog Ambient}
    (exact : YieldStable program map) : ObservationalYieldStable effect program map := by
  intro code reachable seed step moved executed transformed
  obtain ⟨movedStep, movedExecuted, agrees⟩ :=
    exact reachable seed step moved executed transformed
  exact ⟨movedStep, movedExecuted, observationalYieldAgrees_of_exact effect agrees⟩

theorem observationalIndependent_of_exact
    {dynamics : Dynamics sig catalog Ambient} (effect : EffectEquiv dynamics)
    {left right : Program dynamics}
    (leftRespects : ProgramRespects effect left)
    (rightRespects : ProgramRespects effect right)
    (exact : Independent left right) : ObservationalIndependent effect left right where
  left_respects := leftRespects
  right_respects := rightRespects
  transformations_commute := by
    intro leftMap rightMap leftMember rightMember
    exact Cordis.ObservationalPartialTransformation.commutes_of_exact
      (exact.transformations_commute leftMember rightMember)
      (closure_respects leftRespects leftMember)
      (closure_respects rightRespects rightMember)
  left_yield_stable := by
    intro map member
    exact observationalYieldStable_of_exact effect (exact.left_yield_stable member)
  right_yield_stable := by
    intro map member
    exact observationalYieldStable_of_exact effect (exact.right_yield_stable member)

/-! ## Generated accumulators and the GlobalTemporal bridge -/

/-- Occurrence-sensitive evidence that every newest-first accumulator entry was actually yielded
by a reachable execution. -/
inductive YieldedAccumulator
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics) :
    List (UndoCode sig) → Prop where
  | nil : YieldedAccumulator program []
  | cons {code : sig.IteratorCode} {state : State catalog Ambient}
      {step : IterationStep dynamics program.owner code state}
      {rest : List (UndoCode sig)} :
      Reach program code →
      executeOne dynamics program.oracle code state = .ok step →
      YieldedAccumulator program rest →
      YieldedAccumulator program (step.undo :: rest)

/-- The totalized interpretation of an actual accumulator belongs to the program closure. -/
theorem recovery_mem
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {undos : List (UndoCode sig)}
    (yielded : YieldedAccumulator program undos) :
    Closure program (total (dynamics.recover undos)) := by
  induction yielded with
  | nil => exact .identity
  | cons reachable executed rest ih =>
      change Closure program
        (Cordis.PartialTransformation.comp
          (total (dynamics.recover _)) (total (dynamics.applyUndo _)))
      exact .comp ih (.generator (.inverse reachable executed))

/-- Evidence that an exact global step's reified partial map is one word of a program monoid. -/
structure StepMapMember
    {dynamics : Dynamics sig catalog Ambient} (program : Program dynamics)
    {inertia : GlobalLifecycle.InertiaPolicy dynamics}
    {before after : State catalog Ambient}
    (step : Step dynamics inertia before after) : Prop where
  owner_eq : step.actedName = program.owner
  member : Closure program (GlobalTemporal.Step.partialMap step)

namespace StepMapMember

theorem of_forward
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {inertia : GlobalLifecycle.InertiaPolicy dynamics}
    {before after : State catalog Ambient}
    {step : Step dynamics inertia before after} {code : sig.IteratorCode}
    (ownerEq : step.actedName = program.owner)
    (reachable : Reach program code)
    (mapEq : GlobalTemporal.Step.partialMap step = forward program code) :
    StepMapMember program step := by
  constructor
  · exact ownerEq
  rw [mapEq]
  exact .generator (.forward reachable)

theorem of_identity
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {inertia : GlobalLifecycle.InertiaPolicy dynamics}
    {before after : State catalog Ambient}
    {step : Step dynamics inertia before after}
    (ownerEq : step.actedName = program.owner)
    (mapEq : GlobalTemporal.Step.partialMap step =
      (Cordis.PartialTransformation.identity : PartialMap catalog Ambient)) :
    StepMapMember program step := by
  constructor
  · exact ownerEq
  rw [mapEq]
  exact .identity

theorem of_recovery
    {dynamics : Dynamics sig catalog Ambient} {program : Program dynamics}
    {inertia : GlobalLifecycle.InertiaPolicy dynamics}
    {before after : State catalog Ambient}
    {step : Step dynamics inertia before after} {undos : List (UndoCode sig)}
    (ownerEq : step.actedName = program.owner)
    (yielded : YieldedAccumulator program undos)
    (mapEq : GlobalTemporal.Step.partialMap step = total (dynamics.recover undos)) :
    StepMapMember program step := by
  constructor
  · exact ownerEq
  rw [mapEq]
  exact recovery_mem yielded

end StepMapMember

/-- Smallest exact bridge from Definition 60 closure commutation to the per-step law consumed by
`GlobalTemporal`. -/
theorem recoveryCommutesWithMap
    {dynamics : Dynamics sig catalog Ambient}
    {effect : EffectEquiv dynamics}
    {inertia : GlobalLifecycle.InertiaPolicy dynamics}
    {ownerProgram foreignProgram : Program dynamics}
    (independent : Independent ownerProgram foreignProgram)
    {undos : List (UndoCode sig)}
    (yielded : YieldedAccumulator ownerProgram undos)
    {before after : State catalog Ambient} {step : Step dynamics inertia before after}
    (foreign : StepMapMember foreignProgram step)
    (map : TotalStepMap effect step) :
    RecoveryCommutesWithMap dynamics effect undos map := by
  constructor
  intro state
  have commutes : Cordis.PartialTransformation.Commutes
      (total (dynamics.recover undos)) (GlobalTemporal.Step.partialMap step) :=
    independent.transformations_commute (recovery_mem yielded) foreign.member
  have equality := commutes state
  unfold Cordis.PartialTransformation.comp at equality
  rw [map.total state] at equality
  simp only [total, Option.bind_some] at equality
  rw [map.total (dynamics.recover undos state)] at equality
  have exact := Option.some.inj equality
  rw [exact]
  exact effect.setoid.refl _

/-- Observational bridge, avoiding an unnecessary exact representative equality. -/
theorem observationalRecoveryCommutesWithMap
    {dynamics : Dynamics sig catalog Ambient}
    {effect : EffectEquiv dynamics}
    {inertia : GlobalLifecycle.InertiaPolicy dynamics}
    {ownerProgram foreignProgram : Program dynamics}
    (independent : ObservationalIndependent effect ownerProgram foreignProgram)
    {undos : List (UndoCode sig)}
    (yielded : YieldedAccumulator ownerProgram undos)
    {before after : State catalog Ambient} {step : Step dynamics inertia before after}
    (foreign : StepMapMember foreignProgram step)
    (map : TotalStepMap effect step) :
    RecoveryCommutesWithMap dynamics effect undos map := by
  constructor
  intro state
  have commutes : Cordis.ObservationalPartialTransformation.Commutes
      effect.setoid.r (total (dynamics.recover undos))
        (GlobalTemporal.Step.partialMap step) :=
    independent.transformations_commute (recovery_mem yielded) foreign.member
  have outputs := commutes (leftState := state) (rightState := state)
    (effect.setoid.refl state)
  change Coeffect.Observational.OptionRelated effect.setoid.r
    ((GlobalTemporal.Step.partialMap step state).bind
      (total (dynamics.recover undos)))
    ((total (dynamics.recover undos) state).bind
      (GlobalTemporal.Step.partialMap step)) at outputs
  rw [map.total state] at outputs
  simp only [total, Option.bind_some] at outputs
  rw [map.total (dynamics.recover undos state)] at outputs
  cases outputs with
  | some related => exact related

/-- Per-step membership and pairwise independence data for an existing foreign trace. -/
inductive ObservationalPerStepGenerated
    {dynamics : Dynamics sig catalog Ambient} {effect : EffectEquiv dynamics}
    {inertia : GlobalLifecycle.InertiaPolicy dynamics}
    (ownerProgram : Program dynamics) :
    {before after : State catalog Ambient} →
    {trace : Trace dynamics inertia before after} →
    Intervening dynamics effect inertia ownerProgram.owner trace → Prop where
  | nil (state : State catalog Ambient) :
      ObservationalPerStepGenerated ownerProgram (.nil state)
  | cons
      {before middle after : State catalog Ambient}
      {head : Step dynamics inertia before middle}
      {tail : Trace dynamics inertia middle after}
      (foreign : head.actedName ≠ ownerProgram.owner)
      (map : TotalStepMap effect head)
      (rest : Intervening dynamics effect inertia ownerProgram.owner tail)
      (foreignProgram : Program dynamics)
      (independent : ObservationalIndependent effect ownerProgram foreignProgram)
      (member : StepMapMember foreignProgram head)
      (generated : ObservationalPerStepGenerated ownerProgram rest) :
      ObservationalPerStepGenerated ownerProgram (.cons foreign map rest)

/-- The iterator-family certificate discharges `GlobalTemporal.PerStepCommutes`; the existing
temporal theorems may then compose those per-step squares. -/
theorem perStepCommutes_of_generated
    {dynamics : Dynamics sig catalog Ambient} {effect : EffectEquiv dynamics}
    {inertia : GlobalLifecycle.InertiaPolicy dynamics}
    {ownerProgram : Program dynamics} {undos : List (UndoCode sig)}
    (yielded : YieldedAccumulator ownerProgram undos)
    {before after : State catalog Ambient}
    {trace : Trace dynamics inertia before after}
    {intervening : Intervening dynamics effect inertia ownerProgram.owner trace}
    (generated : ObservationalPerStepGenerated ownerProgram intervening) :
    PerStepCommutes undos intervening := by
  induction generated with
  | nil => trivial
  | cons foreign map rest foreignProgram independent member generated ih =>
      exact ⟨observationalRecoveryCommutesWithMap independent yielded member map,
        ih⟩

/-! ## Existing executable iterator example -/

namespace Example

open Cordis.GlobalLifecycle.Example

def program : Program dynamics where
  owner := 0
  RegistrationError := String
  oracle := oracle
  root := 10

theorem root_reachable : Reach program 10 := .root

theorem continuation_reachable : Reach program 0 :=
  .next root_reachable firstStep_executed rfl

theorem root_forward_at_source :
    forward program 10 beginState = some firstStep.after := by
  simp [forward, program, firstStep_executed]

theorem first_inverse_generated :
    Generator program (total (dynamics.applyUndo firstStep.undo)) :=
  .inverse root_reachable firstStep_executed

theorem oneContinuation : ContinuationPath program 10 [0] :=
  .cons root_reachable firstStep_executed rfl (.nil continuation_reachable)

/-- Same registry as the existing source, but at the Nat boundary where increment and truncated
decrement expose noncommutation. -/
def zeroState : ExampleState := { beginState with ambient := 0 }

theorem root_forward_not_commute_first_inverse :
    ¬Cordis.PartialTransformation.Commutes
      (forward program 10) (total (dynamics.applyUndo firstStep.undo)) := by
  intro commutes
  have atZero := commutes zeroState
  have ambientEq := congrArg
    (fun result ↦ result.map (fun state ↦ state.ambient)) atZero
  change some 1 = some 0 at ambientEq
  cases ambientEq

/-- Independence is intentionally not reflexive: even one real program can fail it. -/
theorem not_self_independent : ¬Independent program program := by
  intro independent
  exact root_forward_not_commute_first_inverse
    (independent.transformations_commute
      (.generator (.forward root_reachable))
      (.generator first_inverse_generated))

end Example

/-! ## Counterexamples and representation boundaries -/

namespace RawRegistrationGap

open Cordis.GlobalNameAction.Example

def request : RegistrationRequest Signature where
  component := .provider
  next child := some child

theorem same_component : request.component = .provider := rfl

theorem continuation_depends_on_chosen_child :
    request.next false ≠ request.next true := by
  intro equal
  have childEq := Option.some.inj equal
  cases childEq

theorem retirement_inverse_depends_on_chosen_child :
    (UndoCode.retire false : UndoCode Signature) ≠ .retire true := by
  intro equal
  cases equal

end RawRegistrationGap

namespace WholeRunCounterexample

open Cordis.MediatedTheorem Cordis.PartialTransformation
open Cordis.PartialTransformation.WholeRunGap

def duplicatedFamily (_label : Bool) :
    OperationIndependence.Computation gapCoeffects := computation

theorem duplicatedFamily_wholeRun (left right : Bool) :
    BoundedPartialIndependence
      (duplicatedFamily left) (duplicatedFamily right) :=
  wholeRun

/-- Two distinct family occurrences may carry the same iterator; whole-run interchange still
does not provide the self-independence of the generated monoid. -/
theorem duplicatedFamily_not_pairwise_full :
    ¬(∀ {left right : Bool}, left ≠ right →
      Cordis.PartialTransformation.Independent
        (duplicatedFamily left) (duplicatedFamily right)) := by
  intro pairwise
  have different : false ≠ true := by decide
  exact full_independence_fails (pairwise different)

end WholeRunCounterexample

namespace TotalizationGap

/-- Definition 60's paper-total maps cannot be recovered from an indexed successful step alone:
the existing iterator map is defined at its source and fails at another state. -/
theorem exact_iterator_has_no_totalization :
    ∀ effect : EffectEquiv GlobalLifecycle.Example.dynamics,
      TotalStepMap effect GlobalCalculus.Example.iterStep → False :=
  GlobalTemporal.Counterexample.iterator_has_no_totalization

end TotalizationGap

end Cordis.GlobalIteratorIndependence
