import Cordis.MediatedTheorem

/-!
# Partial transformation monoids for mediated computations

This module closes the finite partial/Kleisli analogue of the gap between the whole-run
interchange theorem and CORDIS Definition 19/Theorem 42 at paper revision
`948a07b369c62adb3b12e102458be5c18dfb69b9`. The paper's total setting remains a distinct claim.

The paper uses total endomorphisms. Here a computation can be undefined because a dependent
binding is absent or an operation is disabled, so transformations are Kleisli maps
`Context → Option Context`. Their equality includes domain equality. A computation generates its
partial forward map and the total Kleisli lift of every inverse it actually yields; the latter is
the concrete `CoeffectAt.lift` inverse, including its identity behavior at an absent current
binding. The least identity/composition closure is therefore a source-honest partial analogue of
Definition 17.

`Independent` is the corresponding bounded Definition 19 certificate: every cross-closure pair
commutes, and every successful foreign transformation preserves definedness and the complete
inverse yielded by the other computation. Whole-run order equality is only a consequence and is
never used as the definition.

An outcome-dependent computation's global forward map is kept as its own generator. The proof
does not assume that this adaptive map is a fixed composition of the forward maps on every
syntactic branch. Instead, forward/inverse commutation and forward yield stability are proved by
structural induction while retaining the exact outcome that selects each continuation. Complete
yielded inverses do lie in the closure of the totalized stage inverses along their realized branch,
which is proved separately.

The scope remains finite, pure, sequential, and exact. No claim is made about arbitrary external
effects, infinite computation trees, asynchronous execution, or the paper's total setting without
the explicit partial-domain reading above.
-/

set_option autoImplicit false

namespace Cordis.PartialTransformation

open Cordis.MediatedIndependence
open Cordis.MediatedTheorem

universe u v w x

variable {Key : Type u} [DecidableEq Key] {Value : Key → Type v}

variable {coeffects : CoeffectFamily.{u, v, w} Key Value}

abbrev DepState (Key : Type u) [DecidableEq Key] (Value : Key → Type v) :=
  Coeffect.Context Key Value

/-!
## Kleisli transformation monoids
-/

/-- A possibly undefined state transformation. -/
abbrev PartialMap (S : Type x) := S → Option S

variable {S : Type x}

/-- Kleisli identity. -/
def identity : PartialMap S := some

/-- Kleisli composition: `inner` runs first and `outer` runs second. -/
def comp (outer inner : PartialMap S) : PartialMap S :=
  fun state ↦ (inner state).bind outer

/-- Pointwise commutation includes equality of both domains. -/
def Commutes (left right : PartialMap S) : Prop :=
  ∀ state, comp left right state = comp right left state

@[simp]
theorem comp_identity_left (map : PartialMap S) : comp identity map = map := by
  funext state
  simp [comp, identity]

@[simp]
theorem comp_identity_right (map : PartialMap S) : comp map identity = map := by
  rfl

theorem comp_assoc (outer middle inner : PartialMap S) :
    comp (comp outer middle) inner = comp outer (comp middle inner) := by
  funext state
  unfold comp
  cases inner state <;> rfl

theorem Commutes.symm {left right : PartialMap S}
    (commutes : Commutes left right) : Commutes right left :=
  fun state ↦ (commutes state).symm

theorem Commutes.comp_left
    {first second other : PartialMap S}
    (firstCommutes : Commutes first other)
    (secondCommutes : Commutes second other) :
    Commutes (comp first second) other := by
  unfold Commutes comp at firstCommutes secondCommutes ⊢
  intro state
  calc
    (other state).bind (fun middle ↦ (second middle).bind first) =
        ((other state).bind second).bind first := (Option.bind_assoc ..).symm
    _ = ((second state).bind other).bind first :=
      congrArg (fun result ↦ result.bind first) (secondCommutes state)
    _ = (second state).bind (fun middle ↦ (other middle).bind first) :=
      Option.bind_assoc ..
    _ = (second state).bind (fun middle ↦ (first middle).bind other) := by
      congr 1
      funext middle
      exact firstCommutes middle
    _ = ((second state).bind first).bind other := (Option.bind_assoc ..).symm

theorem Commutes.comp_right
    {map first second : PartialMap S}
    (firstCommutes : Commutes map first)
    (secondCommutes : Commutes map second) :
    Commutes map (comp first second) :=
  (firstCommutes.symm.comp_left secondCommutes.symm).symm

/-- The least Kleisli submonoid generated by a predicate. -/
inductive Closure (Generator : PartialMap S → Prop) : PartialMap S → Prop where
  | identity : Closure Generator identity
  | generator {map} : Generator map → Closure Generator map
  | comp {outer inner} : Closure Generator outer → Closure Generator inner →
      Closure Generator (comp outer inner)

namespace Closure

theorem mono
    {First Second : PartialMap S → Prop}
    (included : ∀ {map}, First map → Second map)
    {map : PartialMap S} : Closure First map → Closure Second map := by
  intro member
  induction member with
  | identity => exact .identity
  | generator generated => exact .generator (included generated)
  | comp _ _ outerHypothesis innerHypothesis =>
      exact .comp outerHypothesis innerHypothesis

/-- Kleisli generator commutation promotes to both complete closures. -/
theorem commute
    {First Second : PartialMap S → Prop}
    (generatorsCommute : ∀ {left right}, First left → Second right → Commutes left right)
    {left right : PartialMap S}
    (leftMember : Closure First left) (rightMember : Closure Second right) :
    Commutes left right := by
  induction leftMember with
  | identity =>
      intro state
      simp
  | generator leftGenerated =>
      induction rightMember with
      | identity =>
          intro state
          simp
      | generator rightGenerated => exact generatorsCommute leftGenerated rightGenerated
      | comp _ _ firstHypothesis secondHypothesis =>
          exact firstHypothesis.comp_right secondHypothesis
  | comp _ _ firstHypothesis secondHypothesis =>
      exact firstHypothesis.comp_left secondHypothesis

end Closure

/-!
## Computation generators and partial Definition 19
-/

/-- The partial forward transformation of one mediated computation. -/
def forward (computation : OperationIndependence.Computation coeffects) :
    PartialMap (DepState Key Value) :=
  fun state ↦ (evaluate computation state).map RawResult.after

/-- Embed a total inverse into the partial transformation monoid. -/
def total (undo : DepState Key Value → DepState Key Value) : PartialMap (DepState Key Value) :=
  fun state ↦ some (undo state)

/-- Definition 17 generators for a partial mediated computation. -/
inductive Generator
    (computation : OperationIndependence.Computation coeffects) :
    PartialMap (DepState Key Value) → Prop where
  | forward : Generator computation (forward computation)
  | inverse (seed : DepState Key Value) (result : RawResult Key Value)
      (ran : evaluate computation seed = some result) :
      Generator computation (total result.undo)

/-- The partial transformation monoid generated by one mediated computation. -/
abbrev OfComputation
    (computation : OperationIndependence.Computation coeffects) :
    PartialMap (DepState Key Value) → Prop :=
  Closure (Generator computation)

/-- A successful foreign partial transformation preserves definedness and the complete inverse
yielded by a computation.
-/
def YieldStable
    (computation : OperationIndependence.Computation coeffects)
    (map : PartialMap (DepState Key Value)) : Prop :=
  ∀ seed result moved,
    evaluate computation seed = some result →
    map seed = some moved →
    ∃ movedResult,
      evaluate computation moved = some movedResult ∧ movedResult.undo = result.undo

theorem yieldStable_identity
    (computation : OperationIndependence.Computation coeffects) :
    YieldStable computation identity := by
  intro seed result moved ran transformed
  have movedEq := Option.some.inj transformed
  subst moved
  exact ⟨result, ran, rfl⟩

theorem YieldStable.comp
    {computation : OperationIndependence.Computation coeffects}
    {outer inner : PartialMap (DepState Key Value)}
    (outerStable : YieldStable computation outer)
    (innerStable : YieldStable computation inner) :
    YieldStable computation (comp outer inner) := by
  intro seed result moved ran transformed
  unfold Cordis.PartialTransformation.comp at transformed
  cases innerRun : inner seed with
  | none => simp [innerRun] at transformed
  | some middle =>
      rw [innerRun] at transformed
      obtain ⟨middleResult, middleRan, middleUndo⟩ :=
        innerStable seed result middle ran innerRun
      obtain ⟨movedResult, movedRan, movedUndo⟩ :=
        outerStable middle middleResult moved middleRan transformed
      exact ⟨movedResult, movedRan, movedUndo.trans middleUndo⟩

theorem yieldStable_of_generators
    {Generator : PartialMap (DepState Key Value) → Prop}
    {computation : OperationIndependence.Computation coeffects}
    (generatorsStable : ∀ {map}, Generator map → YieldStable computation map)
    {map : PartialMap (DepState Key Value)} (member : Closure Generator map) :
    YieldStable computation map := by
  induction member with
  | identity => exact yieldStable_identity computation
  | generator generated => exact generatorsStable generated
  | comp _ _ outerHypothesis innerHypothesis =>
      exact outerHypothesis.comp innerHypothesis

/-- Partial/Kleisli analogue of Definition 19. -/
structure Independent
    (left right : OperationIndependence.Computation coeffects) : Prop where
  transformations_commute : ∀ {leftMap rightMap},
    OfComputation left leftMap → OfComputation right rightMap →
    Commutes leftMap rightMap
  left_yield_stable : ∀ {map}, OfComputation right map → YieldStable left map
  right_yield_stable : ∀ {map}, OfComputation left map → YieldStable right map

namespace Independent

theorem of_generators
    {left right : OperationIndependence.Computation coeffects}
    (commute : ∀ {leftMap rightMap},
      Generator left leftMap → Generator right rightMap → Commutes leftMap rightMap)
    (leftStable : ∀ {map}, Generator right map → YieldStable left map)
    (rightStable : ∀ {map}, Generator left map → YieldStable right map) :
    Independent left right where
  transformations_commute := Closure.commute commute
  left_yield_stable := yieldStable_of_generators leftStable
  right_yield_stable := yieldStable_of_generators rightStable

theorem symm
    {left right : OperationIndependence.Computation coeffects}
    (independent : Independent left right) : Independent right left where
  transformations_commute := fun leftMember rightMember ↦
    (independent.transformations_commute rightMember leftMember).symm
  left_yield_stable := independent.right_yield_stable
  right_yield_stable := independent.left_yield_stable

end Independent

/-!
## Realized inverse generators
-/

/-- One totalized inverse yielded by a syntactically occurring stage at a successful inspection.
This is the concrete inverse generator, including identity on an absent current binding.
-/
def StageInverseGenerator
    (computation : OperationIndependence.Computation coeffects)
    (map : PartialMap (DepState Key Value)) : Prop :=
  ∃ stage : StageSyntax coeffects,
    Occurs stage computation ∧
    ∃ context data,
      OperationIndependence.inspectForwardAt coeffects stage.key stage.op stage.input context =
          some data ∧
        map = total (rawStage stage.key context data).undo

abbrev StageInverseClosure
    (computation : OperationIndependence.Computation coeffects) :
    PartialMap (DepState Key Value) → Prop :=
  Closure (StageInverseGenerator computation)

/-- A continuation's realized inverse generators remain occurrences of the enclosing stage. -/
theorem stageInverseGenerator_continuation
    {key : Key} {op : (coeffects key).Op} {input : (coeffects key).Input op} {next}
    (outcome : (coeffects key).Outcome op)
    {map : PartialMap (DepState Key Value)}
    (generated : StageInverseGenerator (coeffects := coeffects) (next outcome) map) :
    StageInverseGenerator (coeffects := coeffects) (.step key op input next) map := by
  obtain ⟨stage, occurs, context, data, inspected, equal⟩ := generated
  exact ⟨stage, .continuation outcome occurs, context, data, inspected, equal⟩

/-- Every complete inverse yielded by a computation is a composite of the totalized inverses
yielded along its realized branch.
-/
theorem inverse_mem_stageInverseClosure
    (computation : OperationIndependence.Computation coeffects)
    (seed : DepState Key Value) (result : RawResult Key Value)
    (ran : evaluate computation seed = some result) :
    StageInverseClosure (coeffects := coeffects) computation (total result.undo) := by
  induction computation generalizing seed result with
  | pure =>
      rw [evaluate_pure] at ran
      have equal := Option.some.inj ran
      subst result
      have mapsEqual : total (RawResult.identity seed).undo =
          (identity : PartialMap (DepState Key Value)) := by
        funext state
        rfl
      rw [mapsEqual]
      exact Closure.identity
  | step key op input next induction =>
      rw [evaluate_step] at ran
      cases inspected : OperationIndependence.inspectForwardAt coeffects key op input seed with
      | none => simp [inspected] at ran
      | some data =>
          rw [inspected] at ran
          change
            (match evaluate (next data.outcome) (rawStage key seed data).after with
            | none => none
            | some tail => some ((rawStage key seed data).comp tail)) = some result at ran
          cases tailRun : evaluate (next data.outcome) (rawStage key seed data).after with
          | none => simp [tailRun] at ran
          | some tail =>
              rw [tailRun] at ran
              have equal := Option.some.inj ran
              subst result
              have rootMember : StageInverseClosure (coeffects := coeffects)
                  (.step key op input next) (total (rawStage key seed data).undo) :=
                .generator ⟨⟨key, op, input⟩, .root key op input next,
                  seed, data, inspected, rfl⟩
              have tailMember := induction data.outcome (rawStage key seed data).after tail
                tailRun
              have tailMember' : StageInverseClosure (coeffects := coeffects)
                  (.step key op input next) (total tail.undo) :=
                Closure.mono (stageInverseGenerator_continuation data.outcome) tailMember
              have mapsEqual : total ((rawStage key seed data).comp tail).undo =
                  comp (total (rawStage key seed data).undo) (total tail.undo) := by
                funext state
                rfl
              rw [mapsEqual]
              exact Closure.comp rootMember tailMember'

/-- Any two totalized inverses yielded by cross-occurring stages commute on every current
context, including contexts where either binding is absent.
-/
theorem stageInverseGenerators_commute
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    {leftMap rightMap : PartialMap (DepState Key Value)}
    (leftGenerated : StageInverseGenerator (coeffects := coeffects) left leftMap)
    (rightGenerated : StageInverseGenerator (coeffects := coeffects) right rightMap) :
    Commutes leftMap rightMap := by
  obtain ⟨leftStage, leftOccurs, leftContext, leftData, leftInspected, leftEqual⟩ :=
    leftGenerated
  obtain ⟨rightStage, rightOccurs, rightContext, rightData, rightInspected, rightEqual⟩ :=
    rightGenerated
  subst leftMap
  subst rightMap
  let leftWitness := inspect_has_witness leftStage.key leftStage.op leftStage.input
    leftContext leftData leftInspected
  let rightWitness := inspect_has_witness rightStage.key rightStage.op rightStage.input
    rightContext rightData rightInspected
  have independent := overlap leftStage rightStage leftOccurs rightOccurs
  intro current
  unfold comp total
  rw [leftWitness.data_eq, rightWitness.data_eq]
  apply congrArg some
  change
    Coeffect.Quotient.undoAt
        ((coeffects leftStage.key).run leftStage.op leftStage.input leftWitness.seed
          leftWitness.enabled).1
        (Coeffect.Quotient.undoAt
          ((coeffects rightStage.key).run rightStage.op rightStage.input rightWitness.seed
            rightWitness.enabled).1 current) =
      Coeffect.Quotient.undoAt
        ((coeffects rightStage.key).run rightStage.op rightStage.input rightWitness.seed
          rightWitness.enabled).1
        (Coeffect.Quotient.undoAt
          ((coeffects leftStage.key).run leftStage.op leftStage.input leftWitness.seed
            leftWitness.enabled).1 current)
  exact liftedInverses_commute leftStage.key leftStage.op leftStage.input leftWitness.seed
    leftWitness.enabled rightStage.key rightStage.op rightStage.input rightWitness.seed
    rightWitness.enabled independent current

/-- Inverse-only submonoids of pairwise-overlapping computations commute completely. -/
theorem stageInverseClosures_commute
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    {leftMap rightMap : PartialMap (DepState Key Value)}
    (leftMember : StageInverseClosure (coeffects := coeffects) left leftMap)
    (rightMember : StageInverseClosure (coeffects := coeffects) right rightMap) :
    Commutes leftMap rightMap :=
  Closure.commute (stageInverseGenerators_commute left right overlap) leftMember rightMember

/-- Arbitrary complete inverses yielded by pairwise-overlapping computations commute. -/
theorem yieldedInverses_commute
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    (leftSeed rightSeed : DepState Key Value)
    (leftResult rightResult : RawResult Key Value)
    (leftRun : evaluate left leftSeed = some leftResult)
    (rightRun : evaluate right rightSeed = some rightResult) :
    Commutes (total leftResult.undo) (total rightResult.undo) :=
  stageInverseClosures_commute left right overlap
    (inverse_mem_stageInverseClosure left leftSeed leftResult leftRun)
    (inverse_mem_stageInverseClosure right rightSeed rightResult rightRun)

/-!
## One totalized stage inverse against foreign partial semantics
-/

/-- On a present binding, the partial inverse word agrees with the actual totalized lifted
inverse. The absent case is intentionally excluded: the word is undefined there while the
concrete yielded inverse is identity.
-/
theorem transformAt_inverse_of_present
    (key : Key) (op : (coeffects key).Op) (input : (coeffects key).Input op)
    (seed : Value key) (enabled : (coeffects key).Enabled op input seed)
    (data : OperationIndependence.ForwardData (coeffects key) op)
    (dataEq : data =
      ⟨((coeffects key).run op input seed enabled).1.after,
        ((coeffects key).run op input seed enabled).1.undo,
        ((coeffects key).run op input seed enabled).2⟩)
    (context : DepState Key Value) (value : Value key)
    (lookup : context key = some value) :
    OperationIndependence.transformAt coeffects key
        [.inverse op input seed enabled] context =
      some (liftDataUndo key data context) := by
  subst data
  simp [OperationIndependence.transformAt, OperationIndependence.applyLocal,
    OperationIndependence.localTransition, OperationIndependence.runLocal,
    liftDataUndo, lookup]

/-- Every foreign forward operation sees exactly the same complete data after applying a fixed
totalized inverse generator.
-/
theorem inspectForward_stable_under_stageInverse
    (leftKey : Key) (leftOp : (coeffects leftKey).Op)
    (leftInput : (coeffects leftKey).Input leftOp)
    (leftData : OperationIndependence.ForwardData (coeffects leftKey) leftOp)
    {leftContext : DepState Key Value}
    (leftWitness : InspectWitness (coeffects := coeffects)
      leftKey leftOp leftInput leftContext leftData)
    (rightKey : Key) (rightOp : (coeffects rightKey).Op)
    (rightInput : (coeffects rightKey).Input rightOp)
    (independent : OperationIndependence.FiniteKeyIndependent
      coeffects leftKey rightKey)
    (current : DepState Key Value) :
    OperationIndependence.inspectForwardAt coeffects rightKey rightOp rightInput
        (liftDataUndo leftKey leftData current) =
      OperationIndependence.inspectForwardAt coeffects rightKey rightOp rightInput current := by
  cases lookup : current leftKey with
  | none => simp [liftDataUndo, lookup]
  | some value =>
      let word : OperationalEquivalence.Test (coeffects leftKey) :=
        [.inverse leftOp leftInput leftWitness.seed leftWitness.enabled]
      have ran : OperationIndependence.transformAt coeffects leftKey word current =
          some (liftDataUndo leftKey leftData current) := by
        exact transformAt_inverse_of_present leftKey leftOp leftInput leftWitness.seed
          leftWitness.enabled leftData leftWitness.data_eq current value lookup
      exact independent.right_data_stable rightOp rightInput word current _ ran

/-- A fixed totalized inverse generator commutes with one successful foreign forward stage at
the successor level.
-/
theorem stageInverse_rawStage_after
    (leftKey : Key) (leftOp : (coeffects leftKey).Op)
    (leftInput : (coeffects leftKey).Input leftOp)
    (leftData : OperationIndependence.ForwardData (coeffects leftKey) leftOp)
    {leftContext : DepState Key Value}
    (leftWitness : InspectWitness (coeffects := coeffects)
      leftKey leftOp leftInput leftContext leftData)
    (rightKey : Key) (rightOp : (coeffects rightKey).Op)
    (rightInput : (coeffects rightKey).Input rightOp)
    (rightData : OperationIndependence.ForwardData (coeffects rightKey) rightOp)
    {current : DepState Key Value}
    (rightInspected : OperationIndependence.inspectForwardAt coeffects rightKey rightOp
      rightInput current = some rightData)
    (independent : OperationIndependence.FiniteKeyIndependent
      coeffects leftKey rightKey) :
    liftDataUndo leftKey leftData (rawStage rightKey current rightData).after =
      (rawStage rightKey (liftDataUndo leftKey leftData current) rightData).after := by
  cases leftLookup : current leftKey with
  | none =>
      by_cases same : leftKey = rightKey
      · subst rightKey
        simp [OperationIndependence.inspectForwardAt, leftLookup] at rightInspected
      · simp [rawStage, liftDataUndo, leftLookup, Coeffect.setAt_other, same]
  | some leftValue =>
      let leftWord : OperationalEquivalence.Test (coeffects leftKey) :=
        [.inverse leftOp leftInput leftWitness.seed leftWitness.enabled]
      let rightWord := forwardWord rightKey rightOp rightInput
      have leftRun : OperationIndependence.transformAt coeffects leftKey leftWord current =
          some (liftDataUndo leftKey leftData current) := by
        exact transformAt_inverse_of_present leftKey leftOp leftInput leftWitness.seed
          leftWitness.enabled leftData leftWitness.data_eq current leftValue leftLookup
      have rightRun : OperationIndependence.transformAt coeffects rightKey rightWord current =
          some (rawStage rightKey current rightData).after := by
        have transformed := inspectForward_transform rightKey rightOp rightInput current
        rw [rightInspected] at transformed
        simpa [rightWord, rawStage] using transformed.symm
      have movedInspected := inspectForward_stable_under_stageInverse leftKey leftOp leftInput
        leftData leftWitness rightKey rightOp rightInput independent current
      rw [rightInspected] at movedInspected
      have movedRightRun : OperationIndependence.transformAt coeffects rightKey rightWord
          (liftDataUndo leftKey leftData current) =
            some (rawStage rightKey (liftDataUndo leftKey leftData current) rightData).after := by
        have transformed := inspectForward_transform rightKey rightOp rightInput
          (liftDataUndo leftKey leftData current)
        rw [movedInspected] at transformed
        simpa [rightWord, rawStage] using transformed.symm
      have afterLookup :
          ((rawStage rightKey current rightData).after leftKey).isSome = true := by
        by_cases same : leftKey = rightKey
        · subst rightKey
          simp [rawStage]
        · simp [rawStage, Coeffect.setAt_other, same, leftLookup]
      cases afterLookupEq : (rawStage rightKey current rightData).after leftKey with
      | none => simp [afterLookupEq] at afterLookup
      | some afterValue =>
          have leftAfterRun : OperationIndependence.transformAt coeffects leftKey leftWord
              (rawStage rightKey current rightData).after =
                some (liftDataUndo leftKey leftData
                  (rawStage rightKey current rightData).after) := by
            exact transformAt_inverse_of_present leftKey leftOp leftInput leftWitness.seed
              leftWitness.enabled leftData leftWitness.data_eq _ afterValue afterLookupEq
          have commute := independent.words_commute leftWord rightWord current
          rw [leftRun, rightRun] at commute
          simp only [Option.bind_some] at commute
          rw [movedRightRun, leftAfterRun] at commute
          exact (Option.some.inj commute).symm

/-- Act on a raw result's successor while retaining its complete yielded inverse. -/
def RawResult.mapAfter
    (map : DepState Key Value → DepState Key Value)
    (result : RawResult Key Value) : RawResult Key Value :=
  ⟨map result.after, result.undo⟩

/-- A fixed totalized inverse generator transports every successful foreign computation result
and preserves its complete yielded inverse. Equality of `Option` values also proves exact domain
preservation.
-/
theorem evaluate_map_stageInverse
    (leftKey : Key) (leftOp : (coeffects leftKey).Op)
    (leftInput : (coeffects leftKey).Input leftOp)
    (leftData : OperationIndependence.ForwardData (coeffects leftKey) leftOp)
    {leftContext : DepState Key Value}
    (leftWitness : InspectWitness (coeffects := coeffects)
      leftKey leftOp leftInput leftContext leftData)
    (right : OperationIndependence.Computation coeffects)
    (overlap : RootOverlaps (coeffects := coeffects) leftKey right)
    (current : DepState Key Value) :
    evaluate right (liftDataUndo leftKey leftData current) =
      (evaluate right current).map
        (RawResult.mapAfter (liftDataUndo leftKey leftData)) := by
  induction right generalizing current with
  | pure =>
      simp [evaluate_pure, RawResult.mapAfter, RawResult.identity]
  | step rightKey rightOp rightInput rightNext induction =>
      rw [evaluate_step, evaluate_step]
      have independent := overlap ⟨rightKey, rightOp, rightInput⟩
        (.root rightKey rightOp rightInput rightNext)
      have inspectedStable := inspectForward_stable_under_stageInverse leftKey leftOp leftInput
        leftData leftWitness rightKey rightOp rightInput independent current
      cases inspected : OperationIndependence.inspectForwardAt coeffects rightKey rightOp
        rightInput current with
      | none =>
          have movedInspected : OperationIndependence.inspectForwardAt coeffects rightKey
              rightOp rightInput (liftDataUndo leftKey leftData current) = none := by
            exact inspectedStable.trans inspected
          rw [movedInspected]
          rfl
      | some rightData =>
          have movedInspected : OperationIndependence.inspectForwardAt coeffects rightKey
              rightOp rightInput (liftDataUndo leftKey leftData current) = some rightData := by
            exact inspectedStable.trans inspected
          rw [movedInspected]
          have afterEqual := stageInverse_rawStage_after leftKey leftOp leftInput leftData
            leftWitness rightKey rightOp rightInput rightData inspected independent
          have tailOverlap := overlap.continuation rightData.outcome
          have tailEqual := induction rightData.outcome tailOverlap
            (rawStage rightKey current rightData).after
          rw [afterEqual] at tailEqual
          change
            (match evaluate (rightNext rightData.outcome)
              (rawStage rightKey (liftDataUndo leftKey leftData current) rightData).after with
            | none => none
            | some tail =>
                some ((rawStage rightKey
                  (liftDataUndo leftKey leftData current) rightData).comp tail)) =
              Option.map (RawResult.mapAfter (liftDataUndo leftKey leftData))
                (match evaluate (rightNext rightData.outcome)
                  (rawStage rightKey current rightData).after with
                | none => none
                | some tail => some ((rawStage rightKey current rightData).comp tail))
          rw [tailEqual]
          cases tailRun : evaluate (rightNext rightData.outcome)
            (rawStage rightKey current rightData).after with
          | none => rfl
          | some tail =>
              apply congrArg some
              apply RawResult.ext
              · rfl
              · rfl

/-- A realized stage inverse generator commutes with the complete foreign forward map. -/
theorem stageInverseGenerator_forward_commutes
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    {leftMap : PartialMap (DepState Key Value)}
    (leftGenerated : StageInverseGenerator (coeffects := coeffects) left leftMap) :
    Commutes leftMap (forward right) := by
  obtain ⟨leftStage, leftOccurs, leftContext, leftData, leftInspected, leftEqual⟩ :=
    leftGenerated
  subst leftMap
  let leftWitness := inspect_has_witness leftStage.key leftStage.op leftStage.input
    leftContext leftData leftInspected
  have rootOverlap : RootOverlaps (coeffects := coeffects) leftStage.key right := by
    intro rightStage rightOccurs
    exact overlap leftStage rightStage leftOccurs rightOccurs
  intro current
  unfold comp total forward
  have evaluated := evaluate_map_stageInverse leftStage.key leftStage.op leftStage.input
    leftData leftWitness right rootOverlap current
  change
    evaluate right ((rawStage leftStage.key leftContext leftData).undo current) =
      (evaluate right current).map
        (RawResult.mapAfter (rawStage leftStage.key leftContext leftData).undo) at evaluated
  cases run : evaluate right current with
  | none =>
      rw [run] at evaluated
      simp only [Option.map_none] at evaluated
      simp [evaluated]
  | some result =>
      rw [run] at evaluated
      simp only [Option.map_some] at evaluated
      simp [evaluated, RawResult.mapAfter]

/-- Every composite of realized inverse generators commutes with the foreign whole forward map. -/
theorem stageInverseClosure_forward_commutes
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    {leftMap : PartialMap (DepState Key Value)}
    (leftMember : StageInverseClosure (coeffects := coeffects) left leftMap) :
    Commutes leftMap (forward right) := by
  induction leftMember with
  | identity =>
      intro state
      simp
  | generator generated =>
      exact stageInverseGenerator_forward_commutes left right overlap generated
  | comp _ _ outerHypothesis innerHypothesis =>
      exact outerHypothesis.comp_left innerHypothesis

/-- Every complete inverse yielded by one computation commutes with the other computation's
partial forward generator.
-/
theorem yieldedInverse_forward_commutes
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    (leftSeed : DepState Key Value) (leftResult : RawResult Key Value)
    (leftRun : evaluate left leftSeed = some leftResult) :
    Commutes (total leftResult.undo) (forward right) :=
  stageInverseClosure_forward_commutes left right overlap
    (inverse_mem_stageInverseClosure left leftSeed leftResult leftRun)

/-- The symmetric forward/inverse generator pair also commutes. -/
theorem forward_yieldedInverse_commutes
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    (rightSeed : DepState Key Value) (rightResult : RawResult Key Value)
    (rightRun : evaluate right rightSeed = some rightResult) :
    Commutes (forward left) (total rightResult.undo) :=
  (yieldedInverse_forward_commutes right left (PairwiseOverlap.symm overlap)
    rightSeed rightResult rightRun).symm

/-- A foreign realized stage inverse preserves the domain and complete yielded inverse of the
other computation.
-/
theorem yieldStable_stageInverseGenerator
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    {rightMap : PartialMap (DepState Key Value)}
    (generated : StageInverseGenerator (coeffects := coeffects) right rightMap) :
    YieldStable left rightMap := by
  obtain ⟨rightStage, rightOccurs, rightContext, rightData, rightInspected, rightEqual⟩ :=
    generated
  subst rightMap
  let rightWitness := inspect_has_witness rightStage.key rightStage.op rightStage.input
    rightContext rightData rightInspected
  have rootOverlap : RootOverlaps (coeffects := coeffects) rightStage.key left := by
    intro leftStage leftOccurs
    exact finiteKeyIndependent_symm (overlap leftStage rightStage leftOccurs rightOccurs)
  intro seed result moved ran transformed
  unfold total at transformed
  have movedEq := Option.some.inj transformed
  subst moved
  have evaluated := evaluate_map_stageInverse rightStage.key rightStage.op rightStage.input
    rightData rightWitness left rootOverlap seed
  rw [ran] at evaluated
  let movedResult := RawResult.mapAfter (liftDataUndo rightStage.key rightData) result
  exact ⟨movedResult, evaluated, rfl⟩

/-- Stability under every realized stage inverse promotes to the inverse-only closure. -/
theorem yieldStable_stageInverseClosure
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    {rightMap : PartialMap (DepState Key Value)}
    (member : StageInverseClosure (coeffects := coeffects) right rightMap) :
    YieldStable left rightMap :=
  yieldStable_of_generators (yieldStable_stageInverseGenerator left right overlap) member

/-- A successful foreign computation preserves the complete inspected data of a fixed root
operation. This strengthens the conditional whole-run stability field by proving the moved root
is defined and chooses the same outcome.
-/
theorem inspectForward_stable_under_evaluate
    (targetKey : Key) (targetOp : (coeffects targetKey).Op)
    (targetInput : (coeffects targetKey).Input targetOp)
    (foreign : OperationIndependence.Computation coeffects)
    (overlap : RootOverlaps (coeffects := coeffects) targetKey foreign)
    (before : DepState Key Value) (result : RawResult Key Value)
    (ran : evaluate foreign before = some result) :
    OperationIndependence.inspectForwardAt coeffects targetKey targetOp targetInput
        result.after =
      OperationIndependence.inspectForwardAt coeffects targetKey targetOp targetInput before := by
  induction foreign generalizing before result with
  | pure =>
      rw [evaluate_pure] at ran
      have equal := Option.some.inj ran
      subst result
      rfl
  | step foreignKey foreignOp foreignInput foreignNext induction =>
      rw [evaluate_step] at ran
      cases inspected : OperationIndependence.inspectForwardAt coeffects foreignKey foreignOp
        foreignInput before with
      | none => simp [inspected] at ran
      | some foreignData =>
          rw [inspected] at ran
          change
            (match evaluate (foreignNext foreignData.outcome)
              (rawStage foreignKey before foreignData).after with
            | none => none
            | some tail => some ((rawStage foreignKey before foreignData).comp tail)) =
              some result at ran
          cases tailRun : evaluate (foreignNext foreignData.outcome)
            (rawStage foreignKey before foreignData).after with
          | none => simp [tailRun] at ran
          | some tail =>
              rw [tailRun] at ran
              have equal := Option.some.inj ran
              subst result
              have independent := overlap ⟨foreignKey, foreignOp, foreignInput⟩
                (.root foreignKey foreignOp foreignInput foreignNext)
              have transformed := inspectForward_transform foreignKey foreignOp foreignInput
                before
              rw [inspected] at transformed
              have wordRun : OperationIndependence.transformAt coeffects foreignKey
                  (forwardWord foreignKey foreignOp foreignInput) before =
                    some (rawStage foreignKey before foreignData).after := by
                simpa [rawStage] using transformed.symm
              have rootStable := independent.left_data_stable targetOp targetInput
                (forwardWord foreignKey foreignOp foreignInput) before
                (rawStage foreignKey before foreignData).after wordRun
              have tailStable := induction foreignData.outcome
                (overlap.continuation foreignData.outcome)
                (rawStage foreignKey before foreignData).after tail tailRun
              exact tailStable.trans rootStable

/-- A successful root inspection is exactly the raw result of its singleton computation. -/
theorem evaluate_singleton_of_inspect
    (key : Key) (op : (coeffects key).Op) (input : (coeffects key).Input op)
    (context : DepState Key Value)
    (data : OperationIndependence.ForwardData (coeffects key) op)
    (inspected : OperationIndependence.inspectForwardAt coeffects key op input context =
      some data) :
    evaluate (singleton key op input) context = some (rawStage key context data) := by
  unfold Cordis.MediatedTheorem.singleton
  rw [evaluate_step, inspected]
  change
    (match evaluate (.pure : OperationIndependence.Computation coeffects)
      (rawStage key context data).after with
    | none => none
    | some tail => some ((rawStage key context data).comp tail)) =
      some (rawStage key context data)
  rw [evaluate_pure]
  apply congrArg some
  apply RawResult.ext
  · rfl
  · funext current
    rfl

/-- Successful execution of a foreign computation preserves definedness and the complete inverse
yielded by the other computation. This is the forward-generator instance of Definition 19(2),
stronger than the earlier fallback-style conditional field.
-/
theorem evaluate_yield_stable_under_evaluate
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right)
    (seed : DepState Key Value)
    (leftResult rightResult : RawResult Key Value)
    (leftRun : evaluate left seed = some leftResult)
    (rightRun : evaluate right seed = some rightResult) :
    ∃ movedLeft,
      evaluate left rightResult.after = some movedLeft ∧
        movedLeft.undo = leftResult.undo := by
  induction left generalizing seed leftResult rightResult with
  | pure =>
      rw [evaluate_pure] at leftRun
      have equal := Option.some.inj leftRun
      subst leftResult
      exact ⟨RawResult.identity rightResult.after, evaluate_pure rightResult.after, rfl⟩
  | step leftKey leftOp leftInput leftNext induction =>
      rw [evaluate_step] at leftRun
      cases leftInspected : OperationIndependence.inspectForwardAt coeffects leftKey leftOp
        leftInput seed with
      | none => simp [leftInspected] at leftRun
      | some leftData =>
          rw [leftInspected] at leftRun
          change
            (match evaluate (leftNext leftData.outcome)
              (rawStage leftKey seed leftData).after with
            | none => none
            | some tail => some ((rawStage leftKey seed leftData).comp tail)) =
              some leftResult at leftRun
          cases tailRun : evaluate (leftNext leftData.outcome)
            (rawStage leftKey seed leftData).after with
          | none => simp [tailRun] at leftRun
          | some tailResult =>
              rw [tailRun] at leftRun
              have equal := Option.some.inj leftRun
              subst leftResult
              have rootOverlap : RootOverlaps (coeffects := coeffects) leftKey right := by
                intro rightStage rightOccurs
                exact overlap ⟨leftKey, leftOp, leftInput⟩ rightStage
                  (.root leftKey leftOp leftInput leftNext) rightOccurs
              have movedInspected := inspectForward_stable_under_evaluate leftKey leftOp
                leftInput right rootOverlap seed rightResult rightRun
              rw [leftInspected] at movedInspected
              let movedRoot := rawStage leftKey rightResult.after leftData
              have movedRootRun : evaluate (singleton leftKey leftOp leftInput)
                  rightResult.after = some movedRoot :=
                evaluate_singleton_of_inspect leftKey leftOp leftInput rightResult.after
                  leftData movedInspected
              have singletonOverlap : PairwiseOverlap coeffects right
                  (singleton leftKey leftOp leftInput) := by
                intro rightStage leftStage rightOccurs leftOccurs
                cases leftOccurs with
                | root =>
                    exact finiteKeyIndependent_symm
                      (overlap ⟨leftKey, leftOp, leftInput⟩ rightStage
                        (.root leftKey leftOp leftInput leftNext) rightOccurs)
                | continuation _ impossible => cases impossible
              obtain ⟨rootAtStart, rightAfterRoot, rootAtStartRun, rightAfterRootRun,
                  finalAfter, rightUndo, rootUndo, orderEq⟩ :=
                rawComputation_swap_success right (singleton leftKey leftOp leftInput)
                  singletonOverlap seed rightResult rightRun movedRoot movedRootRun
              have expectedRootRun := evaluate_singleton_of_inspect leftKey leftOp leftInput
                seed leftData leftInspected
              have rootAtStartEq : rootAtStart = rawStage leftKey seed leftData :=
                Option.some.inj (rootAtStartRun.symm.trans expectedRootRun)
              subst rootAtStart
              have tailOverlap := PairwiseOverlap.left_continuation overlap leftData.outcome
              obtain ⟨movedTail, movedTailRun, movedTailUndo⟩ :=
                induction leftData.outcome tailOverlap (rawStage leftKey seed leftData).after
                  tailResult rightAfterRoot tailRun rightAfterRootRun
              have movedTailRun' : evaluate (leftNext leftData.outcome) movedRoot.after =
                  some movedTail := by
                rw [finalAfter]
                exact movedTailRun
              let movedLeft := movedRoot.comp movedTail
              have movedLeftRun : evaluate
                  (.step leftKey leftOp leftInput leftNext) rightResult.after =
                    some movedLeft := by
                rw [evaluate_step, movedInspected]
                change
                  (match evaluate (leftNext leftData.outcome) movedRoot.after with
                  | none => none
                  | some tail => some (movedRoot.comp tail)) = some movedLeft
                rw [movedTailRun']
              refine ⟨movedLeft, movedLeftRun, ?_⟩
              funext current
              exact congrArg (rawStage leftKey seed leftData).undo
                (congrFun movedTailUndo current)

/-- Pairwise overlap supplies forward-generator yield stability with explicit domain
preservation.
-/
theorem yieldStable_forward
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right) :
    YieldStable left (forward right) := by
  intro seed leftResult moved leftRun transformed
  cases rightRun : evaluate right seed with
  | none => simp [forward, rightRun] at transformed
  | some rightResult =>
      rw [forward, rightRun] at transformed
      have movedEq := Option.some.inj transformed
      subst moved
      exact evaluate_yield_stable_under_evaluate left right overlap seed leftResult rightResult
        leftRun rightRun

/-!
## The partial forward generator
-/

/-- Kleisli composition of two partial forward maps is the successor projection of the complete
sequential evaluator.
-/
theorem comp_forward_eq_evaluateSequential
    (left right : OperationIndependence.Computation coeffects)
    (state : DepState Key Value) :
    comp (forward right) (forward left) state =
      (evaluateSequential left right state).map RawResult.after := by
  cases leftRun : evaluate left state with
  | none => simp [comp, forward, evaluateSequential, leftRun]
  | some leftResult =>
      cases rightRun : evaluate right leftResult.after with
      | none =>
          simp [comp, forward, evaluateSequential, leftRun, rightRun]
      | some rightResult =>
          simp [comp, forward, evaluateSequential, leftRun, rightRun, RawResult.comp]

/-- Pairwise overlap already proves commutation of the two whole forward generators, including
equality of their partial domains. This is one generator pair, not monoid independence.
-/
theorem forward_commutes
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right) :
    Commutes (forward left) (forward right) := by
  intro state
  rw [comp_forward_eq_evaluateSequential, comp_forward_eq_evaluateSequential]
  exact congrArg (Option.map RawResult.after)
    (evaluateSequential_commute left right overlap state).symm

/-- Successful sequential raw evaluation exposes both constituent results. -/
theorem evaluateSequential_eq_some_iff
    (left right : OperationIndependence.Computation coeffects)
    (before : DepState Key Value) (result : RawResult Key Value) :
    evaluateSequential left right before = some result ↔
      ∃ leftResult rightResult,
        evaluate left before = some leftResult ∧
        evaluate right leftResult.after = some rightResult ∧
        result = leftResult.comp rightResult := by
  constructor
  · intro ran
    cases leftRun : evaluate left before with
    | none => simp [evaluateSequential, leftRun] at ran
    | some leftResult =>
        cases rightRun : evaluate right leftResult.after with
        | none => simp [evaluateSequential, leftRun, rightRun] at ran
        | some rightResult =>
            rw [evaluateSequential, leftRun] at ran
            change
              (match evaluate right leftResult.after with
              | none => none
              | some result => some (leftResult.comp result)) = some result at ran
            rw [rightRun] at ran
            exact ⟨leftResult, rightResult, rfl, rightRun, (Option.some.inj ran).symm⟩
  · rintro ⟨leftResult, rightResult, leftRun, rightRun, equal⟩
    subst result
    rw [evaluateSequential, leftRun]
    change
      (match evaluate right leftResult.after with
      | none => none
      | some result => some (leftResult.comp result)) = _
    rw [rightRun]

namespace Independent

/-- Full partial transformation independence implies exact whole-run interchange and conditional
inverse stability. Thus whole-run equality is a consequence, never the definition.
-/
theorem toRawMediated
    {left right : OperationIndependence.Computation coeffects}
    (independent : Independent (coeffects := coeffects) left right) :
    RawMediatedIndependence (coeffects := coeffects) left right := by
  constructor
  · intro before
    have forwardEqual := independent.transformations_commute
      (Closure.generator (Generator.forward : Generator left (forward left)))
      (Closure.generator (Generator.forward : Generator right (forward right))) before
    rw [comp_forward_eq_evaluateSequential, comp_forward_eq_evaluateSequential] at forwardEqual
    cases leftOrderRun : evaluateSequential left right before with
    | none =>
        cases rightOrderRun : evaluateSequential right left before with
        | none => rfl
        | some rightOrder =>
            rw [leftOrderRun, rightOrderRun] at forwardEqual
            cases forwardEqual
    | some leftOrder =>
        cases rightOrderRun : evaluateSequential right left before with
        | none =>
            rw [leftOrderRun, rightOrderRun] at forwardEqual
            cases forwardEqual
        | some rightOrder =>
            obtain ⟨leftInitial, rightMoved, leftInitialRun, rightMovedRun, leftOrderEq⟩ :=
              (evaluateSequential_eq_some_iff left right before leftOrder).1 leftOrderRun
            obtain ⟨rightInitial, leftMoved, rightInitialRun, leftMovedRun, rightOrderEq⟩ :=
              (evaluateSequential_eq_some_iff right left before rightOrder).1 rightOrderRun
            have leftForwardRun : forward left before = some leftInitial.after := by
              simp [forward, leftInitialRun]
            have rightForwardRun : forward right before = some rightInitial.after := by
              simp [forward, rightInitialRun]
            obtain ⟨leftMoved', leftMovedRun', leftUndo⟩ :=
              independent.left_yield_stable
                (Closure.generator (Generator.forward : Generator right (forward right)))
                before leftInitial rightInitial.after leftInitialRun rightForwardRun
            have leftMovedEq : leftMoved' = leftMoved :=
              Option.some.inj (leftMovedRun'.symm.trans leftMovedRun)
            subst leftMoved'
            obtain ⟨rightMoved', rightMovedRun', rightUndo⟩ :=
              independent.right_yield_stable
                (Closure.generator (Generator.forward : Generator left (forward left)))
                before rightInitial leftInitial.after rightInitialRun leftForwardRun
            have rightMovedEq : rightMoved' = rightMoved :=
              Option.some.inj (rightMovedRun'.symm.trans rightMovedRun)
            subst rightMoved'
            have inverseCommutes := independent.transformations_commute
              (Closure.generator (Generator.inverse before leftInitial leftInitialRun))
              (Closure.generator (Generator.inverse before rightInitial rightInitialRun))
            have inverseOrder : ∀ current,
                leftInitial.undo (rightInitial.undo current) =
                  rightInitial.undo (leftInitial.undo current) := by
              intro current
              have atCurrent := inverseCommutes current
              unfold comp total at atCurrent
              exact Option.some.inj atCurrent
            have resultEqual : leftOrder = rightOrder := by
              subst leftOrder
              subst rightOrder
              apply RawResult.ext
              · rw [leftOrderRun, rightOrderRun] at forwardEqual
                exact (Option.some.inj forwardEqual).symm
              · funext current
                change leftInitial.undo (rightMoved.undo current) =
                  rightInitial.undo (leftMoved.undo current)
                rw [rightUndo, leftUndo]
                exact inverseOrder current
            exact congrArg some resultEqual
  · intro before leftInitial rightInitial leftRun rightRun
    constructor
    · have rightForwardRun : forward right before = some rightInitial.after := by
        simp [forward, rightRun]
      obtain ⟨leftMoved, leftMovedRun, leftUndo⟩ :=
        independent.left_yield_stable
          (Closure.generator (Generator.forward : Generator right (forward right)))
          before leftInitial rightInitial.after leftRun rightForwardRun
      rw [leftMovedRun]
      exact leftUndo
    · have leftForwardRun : forward left before = some leftInitial.after := by
        simp [forward, leftRun]
      obtain ⟨rightMoved, rightMovedRun, rightUndo⟩ :=
        independent.right_yield_stable
          (Closure.generator (Generator.forward : Generator left (forward left)))
          before rightInitial leftInitial.after rightRun leftForwardRun
      rw [rightMovedRun]
      exact rightUndo

/-- Reinsert the proof-carrying `Applied` layer after deriving the whole-run consequence. -/
theorem toBoundedPartial
    {left right : OperationIndependence.Computation coeffects}
    (independent : Independent (coeffects := coeffects) left right) :
    BoundedPartialIndependence (coeffects := coeffects) left right :=
  independent.toRawMediated.toBoundedPartial

end Independent

/-!
## Full partial transformation independence
-/

/-- Partial/Kleisli analogue of Theorem 42. Pairwise operation overlap proves every pair of
computation transformation generators commutes and proves yield stability for every foreign
generator. Closure then gives the full partial Definition 19 certificate.
-/
theorem pairwiseOverlap_independent
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right) :
    Independent (coeffects := coeffects) left right := by
  apply Independent.of_generators
  · intro leftMap rightMap leftGenerated rightGenerated
    cases leftGenerated with
    | forward =>
        cases rightGenerated with
        | forward => exact forward_commutes left right overlap
        | inverse rightSeed rightResult rightRun =>
            exact forward_yieldedInverse_commutes left right overlap rightSeed rightResult
              rightRun
    | inverse leftSeed leftResult leftRun =>
        cases rightGenerated with
        | forward =>
            exact yieldedInverse_forward_commutes left right overlap leftSeed leftResult leftRun
        | inverse rightSeed rightResult rightRun =>
            exact yieldedInverses_commute left right overlap leftSeed rightSeed leftResult
              rightResult leftRun rightRun
  · intro map generated
    cases generated with
    | forward => exact yieldStable_forward left right overlap
    | inverse seed result ran =>
        exact yieldStable_stageInverseClosure left right overlap
          (inverse_mem_stageInverseClosure right seed result ran)
  · intro map generated
    cases generated with
    | forward => exact yieldStable_forward right left (PairwiseOverlap.symm overlap)
    | inverse seed result ran =>
        exact yieldStable_stageInverseClosure right left (PairwiseOverlap.symm overlap)
          (inverse_mem_stageInverseClosure left seed result ran)

/-- The full closure theorem and the earlier whole-run theorem are separate consequences of the
same non-circular operation hypothesis; the second is not used to define the first.
-/
theorem pairwiseOverlap_full_and_wholeRun
    (left right : OperationIndependence.Computation coeffects)
    (overlap : PairwiseOverlap coeffects left right) :
    Independent (coeffects := coeffects) left right ∧
      BoundedPartialIndependence (coeffects := coeffects) left right :=
  let full := pairwiseOverlap_independent left right overlap
  ⟨full, full.toBoundedPartial⟩

/-!
## Heterogeneous branching example
-/

namespace Example

open Cordis.MediatedTheorem.Example.IndependentBranching

/-- The `Nat → String` branching computation and the independent `Bool` computation satisfy the
full partial transformation-monoid certificate, not merely adjacent whole-run equality.
-/
theorem fullIndependent : Independent leftComputation rightComputation :=
  pairwiseOverlap_independent leftComputation rightComputation overlap

theorem leftRaw_isSome : (evaluate leftComputation initial).isSome = true := rfl
theorem rightRaw_isSome : (evaluate rightComputation initial).isSome = true := rfl

def leftRaw : RawResult DemoKey DemoValue :=
  (evaluate leftComputation initial).get leftRaw_isSome

def rightRaw : RawResult DemoKey DemoValue :=
  (evaluate rightComputation initial).get rightRaw_isSome

theorem leftRaw_run : evaluate leftComputation initial = some leftRaw := by
  rfl

theorem rightRaw_run : evaluate rightComputation initial = some rightRaw := by
  rfl

/-- One concrete yielded inverse generator commutes with the foreign partial forward generator. -/
example : Commutes (total leftRaw.undo) (forward rightComputation) :=
  fullIndependent.transformations_commute
    (Closure.generator (Generator.inverse initial leftRaw leftRaw_run))
    (Closure.generator Generator.forward)

/-- The same foreign forward generator preserves the left computation's domain and complete
yielded inverse.
-/
example : YieldStable leftComputation (forward rightComputation) :=
  fullIndependent.left_yield_stable (Closure.generator Generator.forward)

/-- Whole-run equality remains a separate consequence of the common overlap proof. -/
example : BoundedPartialIndependence
    (coeffects := demoCoeffects) leftComputation rightComputation :=
  fullIndependent.toBoundedPartial

end Example

/-!
## Whole-run equality is strictly weaker
-/

namespace WholeRunGap

inductive GapKey where
  | cell
deriving DecidableEq, Repr

def GapValue : GapKey → Type
  | .cell => Bool

/-- The forward map is identity, while the yielded inverse is the constant map to its seed. -/
def seedCoeffect : Coeffect.CoeffectAt Bool where
  equivalence := {
    r := Eq
    iseqv := ⟨Eq.refl, Eq.symm, Eq.trans⟩
  }
  Op := Unit
  Input := fun _ ↦ Unit
  Outcome := fun _ ↦ Unit
  Enabled := fun _ _ _ ↦ True
  enabledDecidable := fun _ _ _ ↦ isTrue trivial
  run := fun _ _ before _ ↦
    ({
      after := before
      undo := fun _ ↦ before
      undo_after := rfl
    }, ())
  enabled_respects := by simp
  after_respects := by
    intro _ _ left right equal _ _
    exact equal
  undo_respects := by
    intro _ _ left right equal _ _ _ _ _
    exact equal
  outcome_respects := by simp

def gapCoeffects : (key : GapKey) → Coeffect.CoeffectAt (GapValue key)
  | .cell => seedCoeffect

def gapOp : (gapCoeffects .cell).Op := show Unit from ()
def gapInput : (gapCoeffects .cell).Input gapOp := show Unit from ()

def computation : OperationIndependence.Computation gapCoeffects :=
  singleton .cell gapOp gapInput

def falseValue : GapValue .cell := show Bool from false
def trueValue : GapValue .cell := show Bool from true

def falseContext : DepState GapKey GapValue :=
  Coeffect.setAt Coeffect.empty .cell falseValue

def trueContext : DepState GapKey GapValue :=
  Coeffect.setAt Coeffect.empty .cell trueValue

theorem result_after_eq
    (before : DepState GapKey GapValue) (result : RawResult GapKey GapValue)
    (ran : evaluate computation before = some result) : result.after = before := by
  unfold computation Cordis.MediatedTheorem.singleton at ran
  rw [evaluate_step] at ran
  cases inspected : OperationIndependence.inspectForwardAt gapCoeffects .cell gapOp gapInput
    before with
  | none => simp [inspected] at ran
  | some data =>
      rw [inspected] at ran
      change
        (match evaluate (.pure : OperationIndependence.Computation gapCoeffects)
          (rawStage .cell before data).after with
        | none => none
        | some tail => some ((rawStage .cell before data).comp tail)) = some result at ran
      rw [evaluate_pure] at ran
      have equal := Option.some.inj ran
      subst result
      let witness := inspect_has_witness .cell gapOp gapInput before data inspected
      change Coeffect.setAt before .cell data.after = before
      rw [witness.data_eq]
      exact Coeffect.setAt_present before .cell ⟨witness.seed, witness.lookup⟩

/-- At the same predecessor both orders are literally the same, and identity forward motion
cannot change the yielded inverse. -/
theorem wholeRun : BoundedPartialIndependence
    (coeffects := gapCoeffects) computation computation := by
  apply RawMediatedIndependence.toBoundedPartial
  constructor
  · intro before
    rfl
  · intro before leftResult rightResult leftRun rightRun
    have equal := Option.some.inj (leftRun.symm.trans rightRun)
    subst rightResult
    have afterEqual := result_after_eq before leftResult leftRun
    rw [afterEqual, leftRun]
    exact ⟨rfl, rfl⟩

theorem false_isSome : (evaluate computation falseContext).isSome = true := rfl
theorem true_isSome : (evaluate computation trueContext).isSome = true := rfl

def falseResult : RawResult GapKey GapValue :=
  (evaluate computation falseContext).get false_isSome

def trueResult : RawResult GapKey GapValue :=
  (evaluate computation trueContext).get true_isSome

theorem falseRun : evaluate computation falseContext = some falseResult := by rfl
theorem trueRun : evaluate computation trueContext = some trueResult := by rfl

theorem false_then_true_lookup :
    (falseResult.undo (trueResult.undo falseContext)) .cell = some falseValue := by
  rfl

theorem true_then_false_lookup :
    (trueResult.undo (falseResult.undo falseContext)) .cell = some trueValue := by
  rfl

/-- Whole-run equality at every predecessor does not imply cross-seed inverse commutation, hence
does not imply the transformation-monoid certificate.
-/
theorem full_independence_fails :
    ¬Independent (coeffects := gapCoeffects) computation computation := by
  intro independent
  have commute := independent.transformations_commute
    (Closure.generator (Generator.inverse falseContext falseResult falseRun))
    (Closure.generator (Generator.inverse trueContext trueResult trueRun))
  have atContext := commute falseContext
  unfold comp total at atContext
  have contextsEqual := Option.some.inj atContext
  have lookupEqual := congrArg (fun context ↦ context .cell) contextsEqual
  rw [false_then_true_lookup, true_then_false_lookup] at lookupEqual
  have valuesEqual := Option.some.inj lookupEqual
  cases valuesEqual

end WholeRunGap

end Cordis.PartialTransformation
