import Cordis.ObservationalPartialTransformation

/-!
# A totalized quotient specialization of the finite independence theorem

`Cordis.ObservationalPartialTransformation` proves the complete finite
partial/Kleisli analogue of CORDIS Theorem 42.  This file isolates the
additional certificate needed to read a computation as a total operation on
the contexts under consideration.  It does not silently totalize an
undefined computation: `TotalComputation.total` is an explicit proof that
every context has a successful erased result.

The resulting `TotalIndependent` theorem is a finite totalized/quotient
specialization.  It retains the paper boundary: no unrestricted external,
asynchronous, infinite, or quotient-only operation theorem is claimed.
-/

set_option autoImplicit false

namespace Cordis.TotalQuotientIndependence

open Cordis.MediatedIndependence
open Cordis.MediatedTheorem

universe u v w

variable {Key : Type u} [DecidableEq Key] {Value : Key → Type v}
variable {coeffects : CoeffectFamily.{u, v, w} Key Value}

abbrev Context (Key : Type u) [DecidableEq Key] (Value : Key → Type v) :=
  Coeffect.Context Key Value

abbrev Relation (coeffects : CoeffectFamily.{u, v, w} Key Value) :
    Context Key Value → Context Key Value → Prop :=
  Cordis.ObservationalPartialTransformation.contextRelation coeffects

/-!
## Explicit totality
-/

/-/ A computation together with a successful proof-erased result at every context. -/
structure TotalComputation
    (coeffects : CoeffectFamily.{u, v, w} Key Value) where
  computation : OperationIndependence.Computation coeffects
  total : ∀ context : Context Key Value, ∃ result,
    evaluate computation context = some result

noncomputable def resultAt
    (program : TotalComputation coeffects)
    (context : Context Key Value) : RawResult Key Value :=
  Classical.choose (program.total context)

theorem resultAt_spec
    (program : TotalComputation coeffects)
    (context : Context Key Value) :
    evaluate program.computation context = some (resultAt program context) :=
  Classical.choose_spec (program.total context)

/-/ The total forward operation selected by the certificate. -/
noncomputable def forward
    (program : TotalComputation coeffects) : Context Key Value → Context Key Value :=
  fun context ↦ (resultAt program context).after

/-/ The complete inverse yielded by the successful execution from `seed`. -/
noncomputable def yieldedInverse
    (program : TotalComputation coeffects)
    (seed : Context Key Value) : Context Key Value → Context Key Value :=
  (resultAt program seed).undo

/-/ Embed a total map into the partial/Kleisli map used by the existing theorem. -/
def liftTotal (map : Context Key Value → Context Key Value) :
    Cordis.PartialTransformation.PartialMap (Context Key Value) :=
  fun context ↦ some (map context)

theorem evaluate_recovers
    (computation : OperationIndependence.Computation coeffects)
    {context : Context Key Value} {result : RawResult Key Value}
    (ran : evaluate computation context = some result) :
    result.undo result.after = context := by
  unfold evaluate at ran
  cases run : computation.run coeffects context with
  | none => simp [run] at ran
  | some applied =>
      rw [run] at ran
      have equal := Option.some.inj ran
      subst result
      exact applied.undo_after

/-!
## Total words and their exact partial images
-/

/-/ The least finite word language generated by a total computation. -/
inductive Closure
    (program : TotalComputation coeffects) :
    (Context Key Value → Context Key Value) → Prop where
  | identity : Closure program id
  | forward : Closure program (forward program)
  | inverse (seed : Context Key Value) : Closure program (yieldedInverse program seed)
  | comp {outer inner : Context Key Value → Context Key Value} :
      Closure program outer → Closure program inner →
      Closure program (fun context ↦ outer (inner context))

theorem liftTotal_identity :
    liftTotal (id : Context Key Value → Context Key Value) =
      (Cordis.PartialTransformation.identity :
        Cordis.PartialTransformation.PartialMap (Context Key Value)) := by
  rfl

theorem liftTotal_comp (outer inner : Context Key Value → Context Key Value) :
    liftTotal (fun context ↦ outer (inner context)) =
      Cordis.PartialTransformation.comp (liftTotal outer) (liftTotal inner) := by
  rfl

theorem liftTotal_forward
    (program : TotalComputation coeffects) :
    liftTotal (forward program) =
      Cordis.PartialTransformation.forward program.computation := by
  funext context
  unfold liftTotal Cordis.PartialTransformation.forward forward
  rw [resultAt_spec program context]
  rfl

theorem Closure.toExact
    (program : TotalComputation coeffects)
    {map : Context Key Value → Context Key Value} (member : Closure program map) :
    Cordis.PartialTransformation.OfComputation program.computation (liftTotal map) := by
  induction member with
  | identity =>
      rw [liftTotal_identity]
      exact .identity
  | forward =>
      rw [liftTotal_forward]
      exact .generator .forward
  | inverse seed =>
      exact .generator (.inverse seed (resultAt program seed) (resultAt_spec program seed))
  | comp outerMember innerMember ihOuter ihInner =>
      rw [liftTotal_comp]
      exact .comp ihOuter ihInner

/-!
## Totalized quotient independence
-/

/-/ A total operation-level consequence of the finite quotient closure theorem. -/
structure TotalIndependent
    (left right : TotalComputation coeffects) : Prop where
  transformations_commute : ∀ {leftMap rightMap : Context Key Value → Context Key Value},
    Closure left leftMap → Closure right rightMap →
    ∀ before, Relation coeffects (leftMap (rightMap before)) (rightMap (leftMap before))
  left_yield_stable : ∀ {map : Context Key Value → Context Key Value}, Closure right map →
    ∀ {seed : Context Key Value} {result : RawResult Key Value},
      evaluate left.computation seed = some result →
      ∃ movedResult,
        evaluate left.computation (map seed) = some movedResult ∧
          Cordis.ObservationalPartialTransformation.FunctionsRelated
            (Relation coeffects) movedResult.undo result.undo
  right_yield_stable : ∀ {map : Context Key Value → Context Key Value}, Closure left map →
    ∀ {seed : Context Key Value} {result : RawResult Key Value},
      evaluate right.computation seed = some result →
      ∃ movedResult,
        evaluate right.computation (map seed) = some movedResult ∧
          Cordis.ObservationalPartialTransformation.FunctionsRelated
            (Relation coeffects) movedResult.undo result.undo

theorem independent_of_partial
    (left right : TotalComputation coeffects)
    (certificate : Cordis.ObservationalPartialTransformation.Independent
      (Relation coeffects) left.computation right.computation) :
    TotalIndependent left right where
  transformations_commute := by
    intro leftMap rightMap leftMember rightMember before
    have related := certificate.transformations_commute
      (Cordis.ObservationalPartialTransformation.observationalClosure_of_exact
        left.computation (Closure.toExact left leftMember))
      (Cordis.ObservationalPartialTransformation.observationalClosure_of_exact
        right.computation (Closure.toExact right rightMember))
      (leftState := before) (rightState := before)
      (Coeffect.Observational.related_refl
        (Coeffect.Observational.equivalencesOf coeffects) before)
    change Coeffect.Observational.OptionRelated (Relation coeffects)
      (some (leftMap (rightMap before)))
      (some (rightMap (leftMap before))) at related
    cases related with
    | some related => exact related
  left_yield_stable := by
    intro map mapMember seed result ran
    have stable := certificate.left_yield_stable
      (Cordis.ObservationalPartialTransformation.observationalClosure_of_exact
        right.computation (Closure.toExact right mapMember))
      seed result (map seed) ran (by rfl)
    exact stable
  right_yield_stable := by
    intro map mapMember seed result ran
    have stable := certificate.right_yield_stable
      (Cordis.ObservationalPartialTransformation.observationalClosure_of_exact
        left.computation (Closure.toExact left mapMember))
      seed result (map seed) ran (by rfl)
    exact stable

/-/ Pairwise overlap supplies the totalized quotient theorem. -/
theorem pairwiseOverlap_independent
    (left right : TotalComputation coeffects)
    (overlap : PairwiseOverlap coeffects left.computation right.computation) :
    TotalIndependent left right :=
  independent_of_partial left right
    (ObservationalPartialTransformation.pairwiseOverlap_independent
      left.computation right.computation overlap)

/-!
## A quotient-effect view of one total computation
-/

noncomputable def effect
    (program : TotalComputation coeffects) :
    @Cordis.Observational.Effect (Context Key Value)
      (Coeffect.Observational.contextSetoid
        (Coeffect.Observational.equivalencesOf coeffects)) :=
  by
    letI : Setoid (Context Key Value) :=
      Coeffect.Observational.contextSetoid
        (Coeffect.Observational.equivalencesOf coeffects)
    exact fun before ↦
      let result := resultAt program before
      {
        after := result.after
        undo := result.undo
        undo_respects := by
          intro left right related
          have results := Cordis.ObservationalPartialTransformation.evaluate_related
            program.computation
            (Coeffect.Observational.related_refl
              (Coeffect.Observational.equivalencesOf coeffects) before)
          rw [resultAt_spec program before] at results
          cases results with
          | some resultRelated => exact resultRelated.undo related
        undo_after := by
          rw [evaluate_recovers program.computation (resultAt_spec program before)]
          exact Setoid.refl before
      }

theorem effect_admissible
    (program : TotalComputation coeffects) :
    @Cordis.Observational.Quotient.Admissible (Context Key Value)
      (Coeffect.Observational.contextSetoid
        (Coeffect.Observational.equivalencesOf coeffects)) (effect program) := by
  letI : Setoid (Context Key Value) :=
    Coeffect.Observational.contextSetoid
      (Coeffect.Observational.equivalencesOf coeffects)
  refine { effect_respects := ?_ }
  intro left right related
  have results := Cordis.ObservationalPartialTransformation.evaluate_related
    program.computation related
  rw [resultAt_spec program left, resultAt_spec program right] at results
  cases results with
  | some resultRelated => exact {
      after := resultRelated.after
      undo := fun current ↦ resultRelated.undo
        (Coeffect.Observational.related_refl
          (Coeffect.Observational.equivalencesOf coeffects) current)
    }

/-!
## Concrete total fixture
-/

namespace Example

open Cordis.MediatedTheorem.Example.IndependentBranching

theorem pure_total (context : Context DemoKey DemoValue) :
    ∃ result, evaluate (.pure : OperationIndependence.Computation demoCoeffects) context =
      some result := by
  exact ⟨RawResult.identity context, evaluate_pure context⟩

def leftTotal : TotalComputation demoCoeffects :=
  ⟨.pure, pure_total⟩

def rightTotal : TotalComputation demoCoeffects :=
  ⟨.pure, pure_total⟩

theorem pure_overlap :
    PairwiseOverlap demoCoeffects
      (.pure : OperationIndependence.Computation demoCoeffects)
      (.pure : OperationIndependence.Computation demoCoeffects) := by
  intro leftStage rightStage leftOccurs rightOccurs
  cases leftOccurs

theorem totalIndependent : TotalIndependent leftTotal rightTotal :=
  pairwiseOverlap_independent leftTotal rightTotal pure_overlap

theorem executable_forward_pair :
    forward leftTotal initial = initial ∧ forward rightTotal initial = initial :=
  by
    have leftEqual : resultAt leftTotal initial = RawResult.identity initial := by
      exact Option.some.inj ((resultAt_spec leftTotal initial).symm.trans
        (evaluate_pure initial))
    have rightEqual : resultAt rightTotal initial = RawResult.identity initial := by
      exact Option.some.inj ((resultAt_spec rightTotal initial).symm.trans
        (evaluate_pure initial))
    simp [forward, leftEqual, rightEqual, RawResult.identity]

theorem executable_recovery_left :
    (yieldedInverse leftTotal initial) (forward leftTotal initial) = initial := by
  exact evaluate_recovers leftTotal.computation (resultAt_spec leftTotal initial)

end Example

end Cordis.TotalQuotientIndependence
