import Cordis.Schedule

/-!
# Transformation monoids and effect independence

This module mechanizes CORDIS paper Definition 17, Lemma 18, and Definition 19 for the exact
proof-carrying `Cordis.Effect` type. A transformation monoid is represented intrinsically as the
least predicate containing identity and generators and closed under composition. An effect's
generators are its forward map and every state-indexed inverse it can yield.

`Independent` states the paper's two full conditions: every transformation commutes across the
two generated monoids, and every foreign transformation leaves the inverse the other effect
yields unchanged. Generator-level commutation and inverse stability are promoted to the full
closures. The resulting paper-style certificate implies the repository's stronger adjacent
`Effect.IndependentAt` certificate at every predecessor, connecting this layer to `Batch` and
`Schedule` without identifying their weaker hypotheses with Definition 19.

The module proves Lemma 18(2) for `Effect.seq`: every transformation of a composite lies in the
monoid generated by the two constituent transformation monoids. It does not yet mechanize
Theorem 20's arbitrary removal sequence or Corollary 21's arbitrary inverse order.
-/

set_option autoImplicit false

namespace Cordis.Transformation

universe u

abbrev Endomorphism (State : Type u) := State → State

variable {State : Type u}

/-- Two state transformations commute pointwise. -/
def Commutes (left right : Endomorphism State) : Prop :=
  ∀ state, left (right state) = right (left state)

/-- Identity commutes with every state transformation. -/
theorem commutes_id_left (map : Endomorphism State) : Commutes id map :=
  fun _ ↦ rfl

/-- Commutation is symmetric. -/
theorem Commutes.symm {left right : Endomorphism State}
    (commutes : Commutes left right) : Commutes right left :=
  fun state ↦ (commutes state).symm

/-- A composite of two maps commuting with `other` also commutes with `other`. -/
theorem Commutes.comp_left
    {first second other : Endomorphism State}
    (firstCommutes : Commutes first other)
    (secondCommutes : Commutes second other) :
    Commutes (first ∘ second) other := by
  intro state
  exact Eq.trans (congrArg first (secondCommutes state))
    (firstCommutes (second state))

/-- A map commuting with two maps commutes with their composite. -/
theorem Commutes.comp_right
    {map first second : Endomorphism State}
    (firstCommutes : Commutes map first)
    (secondCommutes : Commutes map second) :
    Commutes map (first ∘ second) :=
  (firstCommutes.symm.comp_left secondCommutes.symm).symm

/-- The least transformation monoid generated by one predicate. -/
inductive Closure (Generator : Endomorphism State → Prop) : Endomorphism State → Prop where
  /-- Every generated monoid contains identity. -/
  | identity : Closure Generator id
  /-- Every named generator lies in the closure. -/
  | generator {map} : Generator map → Closure Generator map
  /-- The closure is closed under function composition. -/
  | comp {outer inner} : Closure Generator outer → Closure Generator inner →
      Closure Generator (outer ∘ inner)

namespace Closure

/-- A generator inclusion extends to an inclusion of generated monoids. -/
theorem mono
    {First Second : Endomorphism State → Prop}
    (included : ∀ {map}, First map → Second map)
    {map : Endomorphism State} : Closure First map → Closure Second map := by
  intro member
  induction member with
  | identity => exact .identity
  | generator generated => exact .generator (included generated)
  | comp _ _ outerHypothesis innerHypothesis =>
      exact .comp outerHypothesis innerHypothesis

/-- Commutation of every pair of generators extends to both generated monoids. -/
theorem commute
    {First Second : Endomorphism State → Prop}
    (generatorsCommute : ∀ {left right}, First left → Second right → Commutes left right)
    {left right : Endomorphism State}
    (leftMember : Closure First left) (rightMember : Closure Second right) :
    Commutes left right := by
  induction leftMember with
  | identity => exact commutes_id_left right
  | generator leftGenerated =>
      induction rightMember with
      | identity => exact (commutes_id_left _).symm
      | generator rightGenerated => exact generatorsCommute leftGenerated rightGenerated
      | comp _ _ firstHypothesis secondHypothesis =>
          exact firstHypothesis.comp_right secondHypothesis
  | comp _ _ firstHypothesis secondHypothesis =>
      exact firstHypothesis.comp_left secondHypothesis

end Closure

/-- Definition 17's generating set: one forward map and every yielded inverse. -/
inductive EffectGenerator (effect : Cordis.Effect State) : Endomorphism State → Prop where
  /-- The state transition selected by the effect at every input. -/
  | forward : EffectGenerator effect (fun state ↦ (effect state).after)
  /-- The concrete inverse yielded when the effect is applied at `seed`. -/
  | inverse (seed : State) : EffectGenerator effect (effect seed).undo

/-- Definition 17's transformation monoid of an effect. -/
abbrev OfEffect (effect : Cordis.Effect State) : Endomorphism State → Prop :=
  Closure (EffectGenerator effect)

/-- The monoid generated by the union of two already generated transformation monoids. -/
abbrev Joint (first second : Cordis.Effect State) : Endomorphism State → Prop :=
  Closure (fun map ↦ OfEffect first map ∨ OfEffect second map)

/-- Embed a transformation of the first constituent into the joint closure. -/
theorem left_mem_joint
    (first second : Cordis.Effect State)
    {map : Endomorphism State} (member : OfEffect first map) :
    Joint first second map :=
  Closure.generator (Or.inl member)

/-- Embed a transformation of the second constituent into the joint closure. -/
theorem right_mem_joint
    (first second : Cordis.Effect State)
    {map : Endomorphism State} (member : OfEffect second map) :
    Joint first second map :=
  Closure.generator (Or.inr member)

/-- Lemma 18(1): generator commutation promotes to full transformation monoids. -/
theorem commute_of_generators
    {first second : Cordis.Effect State}
    (generatorsCommute : ∀ {left right},
      EffectGenerator first left → EffectGenerator second right → Commutes left right)
    {left right : Endomorphism State}
    (leftMember : OfEffect first left) (rightMember : OfEffect second right) :
    Commutes left right :=
  Closure.commute generatorsCommute leftMember rightMember

/-- One generator of a sequential effect belongs to the joint constituent closure. -/
theorem seq_generator_mem_joint
    (first second : Cordis.Effect State)
    {map : Endomorphism State}
    (generated : EffectGenerator (Cordis.Effect.seq first second) map) :
    Joint first second map := by
  cases generated with
  | forward =>
      change Joint first second
        ((fun state ↦ (second state).after) ∘ (fun state ↦ (first state).after))
      exact Closure.comp
        (right_mem_joint first second (Closure.generator EffectGenerator.forward))
        (left_mem_joint first second (Closure.generator EffectGenerator.forward))
  | inverse seed =>
      change Joint first second
        ((first seed).undo ∘ (second (first seed).after).undo)
      exact Closure.comp
        (left_mem_joint first second
          (Closure.generator (EffectGenerator.inverse seed)))
        (right_mem_joint first second
          (Closure.generator (EffectGenerator.inverse (first seed).after)))

/-- Lemma 18(2): sequential composition introduces no new transformation source. -/
theorem seq_monoid_subset_joint
    (first second : Cordis.Effect State)
    {map : Endomorphism State}
    (member : OfEffect (Cordis.Effect.seq first second) map) :
    Joint first second map := by
  induction member with
  | identity => exact .identity
  | generator generated => exact seq_generator_mem_joint first second generated
  | comp _ _ outerHypothesis innerHypothesis =>
      exact .comp outerHypothesis innerHypothesis

/-- A transformation leaves the inverse yielded by `effect` unchanged at every state. -/
def InverseStable (effect : Cordis.Effect State) (map : Endomorphism State) : Prop :=
  ∀ state, (effect (map state)).undo = (effect state).undo

/-- Identity leaves every yielded inverse unchanged. -/
theorem inverseStable_id (effect : Cordis.Effect State) : InverseStable effect id :=
  fun _ ↦ rfl

/-- Inverse stability is closed under transformation composition. -/
theorem InverseStable.comp
    {effect : Cordis.Effect State} {outer inner : Endomorphism State}
    (outerStable : InverseStable effect outer)
    (innerStable : InverseStable effect inner) :
    InverseStable effect (outer ∘ inner) := by
  intro state
  exact Eq.trans (outerStable (inner state)) (innerStable state)

/-- Stability under every generator extends to the generated monoid. -/
theorem inverseStable_of_generators
    {Generator : Endomorphism State → Prop}
    {effect : Cordis.Effect State}
    (generatorsStable : ∀ {map}, Generator map → InverseStable effect map)
    {map : Endomorphism State} (member : Closure Generator map) :
    InverseStable effect map := by
  induction member with
  | identity => exact inverseStable_id effect
  | generator generated => exact generatorsStable generated
  | comp _ _ outerHypothesis innerHypothesis => exact outerHypothesis.comp innerHypothesis

/-- Definition 19's full independence conditions for two exact effects. -/
structure Independent (first second : Cordis.Effect State) : Prop where
  /-- Every transformation of the first commutes with every transformation of the second. -/
  transformations_commute : ∀ {left right},
    OfEffect first left → OfEffect second right → Commutes left right
  /-- Transformations of the second do not disturb the inverse yielded by the first. -/
  first_inverse_stable : ∀ {map}, OfEffect second map → InverseStable first map
  /-- Transformations of the first do not disturb the inverse yielded by the second. -/
  second_inverse_stable : ∀ {map}, OfEffect first map → InverseStable second map

namespace Independent

/-- Definition 19 independence is symmetric. -/
theorem symm
    {first second : Cordis.Effect State}
    (independent : Independent first second) : Independent second first where
  transformations_commute := fun leftMember rightMember ↦
    (independent.transformations_commute rightMember leftMember).symm
  first_inverse_stable := independent.second_inverse_stable
  second_inverse_stable := independent.first_inverse_stable

/-- Generator laws suffice for the complete Definition 19 certificate. -/
theorem of_generators
    {first second : Cordis.Effect State}
    (commute : ∀ {left right},
      EffectGenerator first left → EffectGenerator second right → Commutes left right)
    (firstStable : ∀ {map}, EffectGenerator second map → InverseStable first map)
    (secondStable : ∀ {map}, EffectGenerator first map → InverseStable second map) :
    Independent first second where
  transformations_commute := commute_of_generators commute
  first_inverse_stable := inverseStable_of_generators firstStable
  second_inverse_stable := inverseStable_of_generators secondStable

/-- Definition 19 implies equality of both adjacent proof-carrying evaluation orders. -/
theorem independentAt
    {first second : Cordis.Effect State}
    (independent : Independent first second) (before : State) :
    Cordis.Effect.IndependentAt first second before where
  successor_eq := by
    let firstForward : Endomorphism State := fun state ↦ (first state).after
    let secondForward : Endomorphism State := fun state ↦ (second state).after
    have commute := independent.transformations_commute
      (Closure.generator (EffectGenerator.forward : EffectGenerator first firstForward))
      (Closure.generator (EffectGenerator.forward : EffectGenerator second secondForward))
    exact (commute before).symm
  recovery_eq := by
    intro current
    let firstForward : Endomorphism State := fun state ↦ (first state).after
    let secondForward : Endomorphism State := fun state ↦ (second state).after
    have firstStable := independent.first_inverse_stable
      (Closure.generator (EffectGenerator.forward : EffectGenerator second secondForward)) before
    have secondStable := independent.second_inverse_stable
      (Closure.generator (EffectGenerator.forward : EffectGenerator first firstForward)) before
    have inverseCommutes := independent.transformations_commute
      (Closure.generator (EffectGenerator.inverse before :
        EffectGenerator first (first before).undo))
      (Closure.generator (EffectGenerator.inverse before :
        EffectGenerator second (second before).undo)) current
    change
      (first before).undo ((second (first before).after).undo current) =
        (second before).undo ((first (second before).after).undo current)
    rw [secondStable, firstStable]
    exact inverseCommutes

/-- Paper-style independence implies the schedule module's global adjacent commutation. -/
theorem seq_commute
    {first second : Cordis.Effect State}
    (independent : Independent first second) :
    Cordis.Effect.seq first second = Cordis.Effect.seq second first :=
  Cordis.Schedule.seq_commute (fun before ↦ independent.independentAt before)

end Independent

/-!
## Independent coordinate example
-/

namespace Example

structure Model where
  left : Nat
  right : Nat
deriving DecidableEq, Repr

def bumpLeft : Cordis.Effect Model := fun before ↦
  {
    after := { before with left := before.left + 1 }
    undo := fun current ↦ { current with left := current.left - 1 }
    undo_after := by cases before; simp
  }

def bumpRight : Cordis.Effect Model := fun before ↦
  {
    after := { before with right := before.right + 1 }
    undo := fun current ↦ { current with right := current.right - 1 }
    undo_after := by cases before; simp
  }

theorem generators_commute : ∀ {leftMap rightMap : Endomorphism Model},
    EffectGenerator bumpLeft leftMap → EffectGenerator bumpRight rightMap →
      Commutes leftMap rightMap := by
  intro leftMap rightMap leftGenerated rightGenerated
  cases leftGenerated <;> cases rightGenerated <;> intro state <;> cases state <;> rfl

theorem left_inverse_stable : ∀ {map : Endomorphism Model},
    EffectGenerator bumpRight map → InverseStable bumpLeft map := by
  intro map generated state
  cases generated <;> rfl

theorem right_inverse_stable : ∀ {map : Endomorphism Model},
    EffectGenerator bumpLeft map → InverseStable bumpRight map := by
  intro map generated state
  cases generated <;> rfl

theorem independent : Independent bumpLeft bumpRight :=
  Independent.of_generators generators_commute left_inverse_stable right_inverse_stable

def initial : Model := { left := 2, right := 5 }

theorem either_order_same :
    Cordis.Effect.seq bumpLeft bumpRight initial =
      Cordis.Effect.seq bumpRight bumpLeft initial :=
  congrArg (fun effect : Cordis.Effect Model ↦ effect initial) independent.seq_commute

end Example

end Cordis.Transformation
